### ISSUE TITLE
380.61 Hitting View List under Clients on Home Page Logs Out of WebUI

### ISSUE THREAD

**Issue by slamanna212** [RMerl/asuswrt-merlin#1000]
On the RT-N66u, when i click on view list under Clients on the homepage, the list never fully loads and then it sends me to the login screen. On the previous release, it would send me to a white screen. It is improved now, but still not exhibiting the expected behavior

**Comment by RMerl** [comment]
Probably tied to issue #959 .

**Comment by twinology** [comment]
Try setting the auto logout to 0 (zero) minutes on ///Advanced_System_Content.asp
This worked for me :)
