### ISSUE TITLE
No successfull connection with openVPN client. password length issue?

### ISSUE THREAD

**Issue by a3rosol** [RMerl/asuswrt-merlin#1001]
Hi,
I have a working(!) VPN account with my provider. I know it's working, because I can successfully connect with Tunnelblick. The account data is kind of unusual though. To bolster anonymity, the username and password is the same 64 character alphanumeric string. Carefully pasting the string into the fields and trying to connect leaves the message 
` Aug 16 17:23:19 openvpn[19309]: AUTH: Received control message: AUTH_FAILED`
` Aug 16 17:23:19 openvpn[19309]: TCP/UDP: Closing socket`
` Aug 16 17:23:19 openvpn[19309]: SIGTERM[soft,auth-failure] received, process exiting`
I am using the most current version of merlin 380.61 on a RT-AC87U.
Can anyone reproduce this issue?

**Comment by RMerl** [comment]
The username and password fields are currently limited to 50 characters.

64 is kinda silly IMHO, but if that's what a commercial provider out there uses, I can see if it's doable to increase these limits, provided the firmware's internals and openvpn itself don't have other buffers that would further limit it.
