### ISSUE TITLE
Adding new USB devices in cdc-acm.c

### ISSUE THREAD

**Issue by jvonhoff** [RMerl/asuswrt-merlin#1002]
My particular USB modem works in Ubuntu 16.04, but AsusWrt gives a "failed with error -22" in dmesg.  

Ubuntu has an entry for my exact modem [in the "quirks" section](https://github.com/Canonical-kernel/Ubuntu-kernel/blob/master/drivers/usb/class/cdc-acm.c): 
```
	{ USB_DEVICE(0x0572, 0x1329), /* Hummingbird huc56s (Conexant) */
	.driver_info = NO_UNION_NORMAL, /* union descriptor misplaced on
					   data interface instead of
					   communications interface.
					   Maybe we should define a new
					   quirk for this. */
	},
```
and asuswrt has one for a similar modem (same family, different device ID):
```
	{ USB_DEVICE(0x0572, 0x1321), /* Conexant USB MODEM CX93010 */
	.driver_info = NO_UNION_NORMAL, /* has no union descriptor */
	},
```

Is it possible to pull in Ubuntu's quirk (at least for my modem) to get it recognized as a ttyACM0 device?

**Comment by RMerl** [comment]
Different kernels, and no way to test it.
