### ISSUE TITLE
Supporting DSL modem routers?

### ISSUE THREAD

**Issue by kq01526** [RMerl/asuswrt-merlin#1004]
Hi @RMerl ,

does asuswrt-merlin also support the various DSL modem routers from ASUS, see:

http://www.asus.com/Networking/xDSL-Modem-Routers-Products/

?

Regards

**Comment by kq01526** [comment]
Just came across the following issue:

https://github.com/RMerl/asuswrt-merlin/issues/716

Is the info from that issue still up-to-date?

Regards

**Comment by RMerl** [comment]
That's correct, I have no intention on supporting any DSL model.
