### ISSUE TITLE
Invalid legend for cooler status

### ISSUE THREAD

**Issue by noplay** [RMerl/asuswrt-merlin#1005]
I think the legend for cooler status in performance tuning is incorrect
![image](https://cloud.githubusercontent.com/assets/345437/17838283/f3818b4a-67c9-11e6-8064-c97bc91a4932.png)

**Comment by noplay** [comment]
I think it's me that just don't understand the relation between temperature and GHz

**Comment by RMerl** [comment]
First is the temperature for the 2.4 GHz controller, second is the temperature for the 5 Ghz controller.
