### ISSUE TITLE
Add tooltip to wireless log

### ISSUE THREAD

**Issue by pepeEL** [RMerl/asuswrt-merlin#1006]
Hi
I have a question and request. Because when name client wifi is long it is not show full in wireless logs full name. Name is butting. Is any chance to add tooltip to show in tooltip full name clients ? It was very good solution...
![tooltip](https://cloud.githubusercontent.com/assets/16692223/17838571/b5667c38-67d0-11e6-8de4-8339dd5d067d.jpg)

**Comment by RMerl** [comment]
I'll have to take a look, but it should be doable, as long the name isn't truncated before reaching the browser.

**Comment by pepeEL** [comment]
Ok thanks i am waiting to test :)

**Comment by pepeEL** [comment]
Thanks
