### ISSUE TITLE
OpenVPN server couldn't initialize

### ISSUE THREAD

**Issue by Frostman** [RMerl/asuswrt-merlin#1008]
I'm trying to setup OpenVPN server and it couldn't initialize. It's not working for both #1 and #2 slots. It's continuously showing following message under "Export OpenVPN configuration file" section:

> Initialinzing the settings of OpenVPN server now, please wait a few minutes to let the server to setup completed before VPN clients establish the connection. 

I find the following log messages:

```
Aug 23 09:37:12 openvpn[9648]: Options error: --up script fails with 'updown.sh': Permission denied
Aug 23 09:37:12 openvpn[9648]: Options error: Please correct this error.
Aug 23 09:37:12 openvpn[9648]: Use --help for more information.
```

I've tried to reset to defaults, bit it doesn't help.

Router: AC68U
Firmware: 380.61

**Comment by RMerl** [comment]
Please use the forums for support requests.
