### ISSUE TITLE
Smbd high cpu usage

### ISSUE THREAD

**Issue by Roman-Skripka** [RMerl/asuswrt-merlin#1009]
@RMerl hi, when I read/write to external ext4 USB 3.0 drive (plugged into USB 3.0 port) via samba I have the same speeds ~40Mb/s. I noticed ~100% cpu load during this operation. Is it some kind of software/configuration issue or just a hardware limitation?
![screenshot4](https://cloud.githubusercontent.com/assets/7115589/17909646/0837d7ae-698e-11e6-88f1-2f96c63722f7.PNG)

**Comment by RMerl** [comment]
This is the limitation of a 800 MHz CPU with a USB-based storage architecture.  You need a real NAS for any reasonable performance.

Not a firmware issue.

**Comment by Roman-Skripka** [comment]
@RMerl fyi, got additional ~8Mb/s with enabled 9k jumbo frames.
