### ISSUE TITLE
Setup DNS to point to local IP when inside network

### ISSUE THREAD

**Issue by chrleon** [RMerl/asuswrt-merlin#1013]
How can I setup my system to give out local IP-address for my Dynamic DNS URL, when inside my network?

Going to dynamic.example.com from work takes me to my server at home, but when I'm home I would like to go directly to 192.168.1.100, when I access dynamic.example.com.

Is there a way to do this or is it already done automagically?

**Comment by RMerl** [comment]
Please use the forums for support requests.
