### ISSUE TITLE
SSH not enabled from WAN disregarding of web settings configuration

### ISSUE THREAD

**Issue by er-nun-vogelfrei-ist** [RMerl/asuswrt-merlin#1016]
Hi,

I'm observing problems with the latest firmware. Enabling SSH with access from LAN+WAN should take care of the iptables rules for forwarding and so on. Apparently this is not the case. Same for the VPN services. I can't access either of them from the WAN/outside world.

Web configuration for forwarding to other LAN hosts works fine as usual, though.

**Comment by RMerl** [comment]
Works for me, both SSH and VPN (which is very widely used).  THe issue lies with your configuration or your modem blocking access to those ports.
