### ISSUE TITLE
Traffic Monitor Wired Tab

### ISSUE THREAD

**Issue by antonlobanov** [RMerl/asuswrt-merlin#1017]
in traffic monitor, wire tab, not drawn download graph

**Comment by RMerl** [comment]
Works for everyone else, so most likely an issue on your end.  Try a different browser.

**Comment by antonlobanov** [comment]
<img width="1280" alt="wired" src="https://cloud.githubusercontent.com/assets/2478787/18035544/7617fed6-6d60-11e6-8a26-c0765da9f5fa.png">
<img width="1280" alt="wan" src="https://cloud.githubusercontent.com/assets/2478787/18035543/76151c7a-6d60-11e6-9d81-f390a3afb982.png">

It's look like not browser issue, i try on chrome and explorer.
I running speedtest.net on screens. You may see that total received bytes on wired tab much less than in wan tab. That why i cant see graph, it is not visible because of the scale.

**Comment by RMerl** [comment]
See the note about NAT acceleration on that page - it must be disabled for accurate results.
