### ISSUE TITLE
Option to extend client scan

### ISSUE THREAD

**Issue by mondahl** [RMerl/asuswrt-merlin#1020]
As it stands now client scan only performs the scan on the routers' own IP address/24 network.

This presents a problem if someone changes the IP Pool Starting/Ending Address to a range other than the routers'  IP address/24 network. The same applies if you manually assign a static IP:
e.g. 
Router IP=192.168.1.1 
Subnet Mask=255.255.128.0
IP Pool range=192.168.2.10-192.168.2.100 wouldn't show any DHCP connected clients in the client list
device static IP=192.168.3.2 wouldn't show said static device in the client list

Would it be possible to add an option to do a IP Pool Starting/Ending range and static IP scan with the current router IP address/24 network scan?

**Comment by RMerl** [comment]
Networkmap was designed with only a /24 in mind.  Allowing it to handle larger subnets would require quite a bit of design changes, which would be outside the scope of this project - this is something that would have to be done upstream by Asus.
