### ISSUE TITLE
PPTP only works for first connection.

### ISSUE THREAD

**Issue by CKret** [RMerl/asuswrt-merlin#1024]
When enabling the PPTP server and connecting to it VPN works as expected.
If disconnecting and trying to reconnect a connection cannot be established.
Disabling PPTP and enabling it again will allow the user to connect again, but only once before another disable/enable is required.

**Comment by RMerl** [comment]
Can't reproduce the issue here, I was able to repeatedly disconnect and reconnect to the PPTPD server.

**Comment by CKret** [comment]
Forgot to mention: on an AC-66U router.
I've had this problem since... well... a couple of years ago...
Asus firmware or Merlin... Same problem....
No big deal since there is a way around the problem but still an annoyance...

**Comment by RMerl** [comment]
Can't reproduce and never had any other report of such a behaviour, so I suspect it's related to the client.
