### ISSUE TITLE
Block Intranet access seems broken

### ISSUE THREAD

**Issue by Fuechslein** [RMerl/asuswrt-merlin#1026]
Hi,

When I set up a guest network and block Intranet acess it all works for devices on the same subnet, but devices on another subnet which is connected over vpn can still be accessed from guest WiFi. Is it really only the same subnet that gets locked down, or does it not work because the others subnet is connected over vpn?

**Comment by RMerl** [comment]
That option only handles the local LAN and its subnet, it does not handle other subnets neither other interfaces such as VPN tunnels.
