### ISSUE TITLE
RT-AC66U - 380.61 -- WPS turned on

### ISSUE THREAD

**Issue by thezoggy** [RMerl/asuswrt-merlin#1030]
Upgraded to latest, which changed the firmware format.. upon updating I just discovered that WPS was turned on... it was previously off.

not sure if this was by design or just fallout from the firmware format change.. just noting in case others are as surprised as I was.

**Comment by RMerl** [comment]
Firmware defaults to WPS being enabled if you did a factory default reset.

App icon has been there for quite some time already, it's a shortcut to Asus's iOS/Android app on their respective stores.

**Comment by thezoggy** [comment]
app icon doesnt do anything for me when clicked (firefox). it wasnt there on `380.59`.. and pretty sure I didnt reset defaults unless it just did it automatically.

**Comment by RMerl** [comment]
The icon popup only works on some browsers, like Chrome.
