### ISSUE TITLE
[380.61] [RT-AC66U] Connection possible after 10 minutes only

### ISSUE THREAD

**Issue by kill0rz** [RMerl/asuswrt-merlin#1031]
When booting the router it will accept WiFi connections but disconnects after a few seconds (2-4).

This behavior will last until ~10 minutes running time. Then connections are possible as usual.
380.59 hasn't got this bug.

**Comment by erice67** [comment]
my ac66 has the same behavior, the running time is ~30s, then all ok

**Comment by RMerl** [comment]
Not a bug with the firmware, most likely reasons are you are using a DFS channel, or you have a source of interference.

Please use the support forums for wifi troubleshooting.

**Comment by kill0rz** [comment]
Both firmwares have got the exact same settings and an interference can be ruled out.
