### ISSUE TITLE
Cannot revert to firmware before 380.61

### ISSUE THREAD

**Issue by dahmage** [RMerl/asuswrt-merlin#1032]
Assus RT-N66U

I updated to 380.61 yesterday, and had a lockup today, so i decided to try to revert to 380.59.

380.61 rejects the previous firmware with the error message:
To comply with regulatory requirements, we have modified our certification rule to ensure better firmware quality.  This version is not compatible with all previously released ASUS firmware and uncertified third party firmware.  Please check our official websites for the certified firmware.

![image](https://cloud.githubusercontent.com/assets/6607767/18371612/b98f0028-7603-11e6-9c29-ba1810c669fd.png)

**Comment by RMerl** [comment]
Not a bug, and already documented in the [Changelog](http://asuswrt.lostrealm.ca/changelog), on the support forums as well as in the [documentation](https://github.com/RMerl/asuswrt-merlin/wiki/Reverting).
