### ISSUE TITLE
No data in table displayed when a MAC address is added on the Wireless MAC Filter page

### ISSUE THREAD

**Issue by existentia** [RMerl/asuswrt-merlin#1034]
Hi,

I have an RT-AC87U and I'm running 380.61. The issue I've found is that on the Wireless MAC Filter page if you add a MAC address for rejection it doesn't get listed on the filter list table (so it can't be removed if needed). Steps to reproduce:

1. Browse to the Wireless Mac Filter page.
2. Set Enable MAC Filter to Yes and select the relevant band.
3. Set MAC Filter Mode to Reject.
4. Paste in a MAC address (I didn't use the drop-down values, as the MAC address I was looking for wasn't listed).
5. Click Add. The page refreshes but the MAC address isn't listed in the MAC filter list table (No data in table).

It looks like the actual rejection of the MAC address I added is working fine, it just isn't getting listed on the page.

**Comment by RMerl** [comment]
Works for me.  You probably have a corrupted existing filter list, which happened a few versions ago as both Asus and myself were changing the format of that nvram setting.
