### ISSUE TITLE
Latency Spikes

### ISSUE THREAD

**Issue by atomyuk** [RMerl/asuswrt-merlin#1035]
Hi.

I've bought a new one RT-AC87U and upgraded it to 380.61 firmware.
Simple ping to asus device shows abnormal latency spikes on 5g or regular 2.4 frequncy. 
Router stands on my desk near the laptop. 
My laptop is MacBook Air (13-inch, Mid 2013).

**Comment by atomyuk** [comment]
![image](https://cloud.githubusercontent.com/assets/9460920/18557908/84702da6-7b79-11e6-9105-3a9ea92df5ae.png)

**Comment by RMerl** [comment]
Please use the support forums at SNBForums for support requests.
