### ISSUE TITLE
Time management doesn't kill existing connections

### ISSUE THREAD

**Issue by apenney** [RMerl/asuswrt-merlin#1036]
I rely on the parental controls stuff to timebox my daughter to 6 hours of Internet access a day (man, what I'd have given for 6 hours a day of internet access when I was a teen, we were stuck on a 14.4 modem with paid local calls).

I noticed the other day that if she has an established connection to Skype it doesn't disconnect when the time management stuff kicks in, it only stops new connections.  She was able to keep that connection up for an additional 3 hours, which is uncool.

Not sure if it's easily fixable, I guess you'd have to force a RST to all connections from the mac address whenever the time management system kicks in, but I thought I'd at least mention it here.

**Comment by RMerl** [comment]
Disable NAT acceleration, as it causes established connections to bypass iptables.

**Comment by apenney** [comment]
Will give it a go! Thanks.
