### ISSUE TITLE
[Feature] Advanced routing policy for OpenVPN Client Settings

### ISSUE THREAD

**Issue by Redsandro** [RMerl/asuswrt-merlin#1037]
You can have multiple VPN Clients configured, and have different local ip addresses use different OpenVPN connections using the _"Rules for routing client traffic through the tunnel"_ setting:

![image](https://cloud.githubusercontent.com/assets/1702193/18609580/8be81e80-7d05-11e6-8bc7-910adc03d3a3.png)

It would be interesting to be able to redirect only traffic from or towards specific ports.

**Comment by RMerl** [comment]
Not possible because policy routing is handled by the kernel's RPDB, which works at the IP level, not at the TCP/UP level.
