### ISSUE TITLE
PPTP client - no internet 

### ISSUE THREAD

**Issue by vukomir** [RMerl/asuswrt-merlin#1038]
Hi,

after configuring pptp client and connecting to the pptp server my internet connection stops working.
from what i can see from the logs/system one more default route is added via pptp connection.
is there a posibili to not route all traffic via PPTP connection and only use it as a tunnel between 2 networks? 

forgot to say, i'm using RT-N66U

**Comment by RMerl** [comment]
I don't plan on spending any development time on PPTP since I consider the protocol to be obsolete - it's trivial to crack it.
