### ISSUE TITLE
Update Tor to 0.2.8.8 (compiles and runs fine in 380.62)

### ISSUE THREAD

**Issue by blackfuel** [RMerl/asuswrt-merlin#1040]
Without any modification to the latest TOR 0.2.8.8 source code distribution, I found that it compiles and runs fine inside the Asuswrt-Merlin 380.62 firmware for RT-AC68U.  Just delete/rename the old TOR folder first, then copy in the new one.  I wish everything was this easy.

**Comment by RMerl** [comment]
I had a quick glance at the early 0.2.8.x changelogs, and there doesn't seem to be any compatibility-breaking change over 0.2.6.x.  I'll look into updating it for 382.63.
