### ISSUE TITLE
Zero-Handoff roaming

### ISSUE THREAD

**Issue by hvaliatti** [RMerl/asuswrt-merlin#1041]
Apparentely Asus does not handle roaming between two AP very well when you have 2 AP from Asus handling connections. I know roaming assistant is limited to -70, however, even when the signal is lower than that, roaming takes 5-10 minutes to work, so moving from one AP to another will have a huge lag.

More can be seen here: http://www.snbforums.com/threads/rt-ac66u-rt-ac87u-roaming-assistant-rssi-span.22254/ or here: http://www.snbforums.com/threads/asus-rp-ac56-1200mbit-extender-completely-not-working-in-ap-mode.28356/

Can you implement something similar to Zero-Handoff or any time out for roaming? Asus says this is ok and does not plan to fix it anytime.

**Comment by RMerl** [comment]
This is beyond the scope of this project.
