### ISSUE TITLE
DHCP option 60

### ISSUE THREAD

**Issue by gfardel** [RMerl/asuswrt-merlin#1044]
Hello,

Can you add the DHCP option 60 (it is the udhcpc -v "TEXT STRING" argument) ?
I can only set the DHCP option 61 on the advanced WAN configuration page / ISP requirement.
Can you add a new text field to store a text string, for example 👍 
100008,0001,ASUS
It's possible to store this information on the NVRAM or other ?

**Comment by RMerl** [comment]
Please update your firmware, option 60 was already added in 380.62.
