### ISSUE TITLE
Feature request : Disable port forwards option

### ISSUE THREAD

**Issue by neoatomic** [RMerl/asuswrt-merlin#1050]
@RMerl First thanks for all the time that you put into this project. 

Every few weeks i need to open/forward a port for an incoming FTP server. Currently i need to re-add/remove the port with every use. (as i want the port to be closed after usage)
I'm hoping it would be possible to have an option to just "disable" a individual forwarded port, so that the settings are saved, and you can reactivate it with a simple mouse click.

**Comment by p3yot3** [comment]
I would also love to see this feature implemented for similar reasons.

Thanks & great work!

**Comment by fanaticDavid** [comment]
I would also love this feature. My previous router, a CISCO Linksys E4200, had this in the standard firmware. Really convenient!

**Comment by HGWJ** [comment]
I would also love to see this feature implemented for similar reasons.

**Comment by RMerl** [comment]
Unlikely, as this would break compatibility with the stock firmware.  This is something that would have to be implemented by Asus ideally.
