### ISSUE TITLE
Adblock option baked in within Merlin firmware

### ISSUE THREAD

**Issue by crazyontech** [RMerl/asuswrt-merlin#1052]
Can Adblocking be baked in within the Merlin firmware (Like what Tomato Shibby has), instead of having to use AB-Solution or manually configuring Adblock subscription.

This will be very useful for a general user. 

It will be really nice if we have an option just to switch ON/OFF the adblocking and select the host file for blocking.

**Comment by RMerl** [comment]
There are no plans for integrating an ad blocker.
