### ISSUE TITLE
Pulling realtime stats via api endpoint or similar?

### ISSUE THREAD

**Issue by damccull** [RMerl/asuswrt-merlin#1059]
Is there a way to pull realtime traffic (and other neat info) stats via an api endpoint on the lan or some other way? The newest firmware links to an android app that seems to have a realtime monitor, though it appears glitchy and laggy. I'd rather set up a dashboard app pulling the data myself. Is it possible?

**Comment by RMerl** [comment]
Use SNMP.

And please use the forums for support request - this is a bug tracker.
