### ISSUE TITLE
/jffs/configs/group.add does not work

### ISSUE THREAD

**Issue by cbz** [RMerl/asuswrt-merlin#1061]
Hi - I have the following contents in /jffs/configs/group.add:

`nogroup:x:5:`

After a reboot, this isn't added to the contents of /tmp/etc/group|/etc/group.  I do have "Enable JFFS custom scripts and configs" set to 'Yes', and I am already using custom configs for dnsmasq.conf (which works).

The reason I need this btw is because the avahi daemon in opkg tries to chgrp to 'nogroup' after it is started up - and this fails.  I notice there is an avahi daemon in the github source tree - not sure if this is now built into the official build, I can't find it at any rate.

I tried posting this to the snbforums instead, but when I do cloudflare blocks me (apparently my post may contain sql commands).

**Comment by cbz** [comment]
Incidentally, this is with version 380.62_1 of the firmware - though it doesn't work with older firmware either.

**Comment by RMerl** [comment]
Issue occurs because the passwd/group/shadow files are configured before jffs2 is mounted.

**Comment by cbz** [comment]
but if you are recreating this - then I should see the change applied afterwards, shouldn't I? In this case even after a successful boot the .add file isn't added to /etc/group

**Comment by RMerl** [comment]
I fixed it last night, so unless you just recompiled the firmware from the Git repo, you won't see this change until the next release.
