### ISSUE TITLE
Sets generated by ipset 6.x cannot be accesed by iptables

### ISSUE THREAD

**Issue by RMerl** [RMerl/asuswrt-merlin#1062]
As mentioned in issue #1023, the following will fail:

```
admin@Stargate88:/tmp# ipset create testset hash:ip
admin@Stargate88:/tmp# iptables -A INPUT -i eth0 -m set --match-set testset src -j ACCEPT
iptables: No chain/target/match by that name.
```

**Comment by blackfuel** [comment]
This is working for me now.  Be sure you're loading the "xt_set" module, in addition to the other ones.

**Comment by RMerl** [comment]
Just loading xt_set should be sufficient.  ip_set automatically get loaded then as a dependency.
