### ISSUE TITLE
380.62_1 AC87U Cannot keep stable SSH connection with Bitvise client

### ISSUE THREAD

**Issue by Zulgrib** [RMerl/asuswrt-merlin#1071]
Using Bitvise SSH client, it is not possible to keep a stable SSH connection on RT87U ver 380.62_1, the client is disconnecting all the time, and router's logs says the client disconnected itself.

Client's error is : 
The SSH2 session has terminated with error. Reason: Error class: LocalSshDisconn, code: ByApplication, message: FlowSshPacketDecoder: unresponsiveness timeout.

Router says : 
dropbear[928]: Exit (Admin): Disconnect received

**Comment by RMerl** [comment]
Look for any keepalive option in your client, or try a different client.  So far there's no problem with OpenSSH, putty or XShell, so this seems specific to either your configuration or the Bitvise client.  In which case, the issue is more up to the Bitvise or the Dropbear developers.
