### ISSUE TITLE
Logfile archiving

### ISSUE THREAD

**Issue by Has3n** [RMerl/asuswrt-merlin#1075]
Hello,

as far i could find out asuswrt does not support archiving of traffic and system logs. Instead you are required to manually download or feed to a syslog server which i dont have and i dont plan on having a constantly running server. Does merlin add a bit more functionality to reporting, e.g. send logfiles via email or store them on usbdrive of router on a regular basis without need to do that manually? thanks:)

**Comment by RMerl** [comment]
Please use the support forums at SNBForums for support requests.
