### ISSUE TITLE
why does my router connect to: milla.nas-admin.org ?

### ISSUE THREAD

**Issue by gauteh** [RMerl/asuswrt-merlin#1076]
I noticed through `netstat` that the router connects to milla.nas-admin.org at start-up. Are you familiar with this? It also manages to block the web interface on the main router in my network somehow (the rt-n66u is configured to as a repeater) (this seems to be done by /usr/sbin/networkmap connecting to the :www port on the main router - diagnosed using `lsof`)?

**Comment by RMerl** [comment]
Please use the support forums at SNBForums for support requests.
