### ISSUE TITLE
Force poke ISP on boot to maintain IPv6 prefix (via dhcp-pd)

### ISSUE THREAD

**Issue by nimish** [RMerl/asuswrt-merlin#1077]
Sky UK requires that you make an active prefix request, so even if you disable sending RELEASE on exit, it won't work on the next boot. 

There's a hacky fix that relies on killing odhcpv6 and restarting it, but that's not particularly reliable (for me at least)
See: http://www.snbforums.com/threads/ipv6-duid.34523/page-2

**Comment by RMerl** [comment]
Disabling the RELEASE sending was just the matter of adding an option to control an odhcp6c existing setting.  This other issue however requires working around a quirk from the ISP, which I have no way of testing (and don't really have the patience to deal with either).  Someone else will have to address this.

**Comment by nimish** [comment]
I took a look internally and it is indeed quite complex. Not really a quick fix at all without modifying odhcp6c or using something else. 

WORKAROUND: kill odhcp6c at start and restart it using a script
