### ISSUE TITLE
Unmount and shutdown router

### ISSUE THREAD

**Issue by Nic2012** [RMerl/asuswrt-merlin#1078]
Hi,
after a while I would like to turn off my ac56u router, but before I have to unmount all connected harddisk. Is there an opportunity to program e.g. the WPS button to call both actions immediately?

Best reagards,
Nic

**Comment by RMerl** [comment]
There are plans to make the WPS button configurable, but no ETA at this point as to when this will be implemented.

**Comment by Nic2012** [comment]
Because I power off the router each day, its inconvenient to unmount the harddisks (NTFS) each time via the webinterface. But when the disks are already spin down would it be safe to power off without unmounting?
