### ISSUE TITLE
Not compiling when PARENTAL2=n

### ISSUE THREAD

**Issue by blackfuel** [RMerl/asuswrt-merlin#1080]
Here's a patch to fix the issue with 380.63-beta1 not compiling when PARENTAL2=n.
[asuswrt-merlin-380.63-beta1-parental-fix.patch.txt](https://github.com/RMerl/asuswrt-merlin/files/560624/asuswrt-merlin-380.63-beta1-parental-fix.patch.txt)

**Comment by azdps** [comment]
I can confirm that there is build failure when attempting to compile when PARENTAL2  is set to PARENTAL=n. I'm using the latest source code from Oct 30, 2016. Your recent change to [firewall.c](https://github.com/RMerl/asuswrt-merlin/commit/f5ea81fffd4c284db417c6f43b20bdf6c69cf47d) must have introduced the issue. Implementing blackfuel's patch or another fix would be great.

**Comment by RMerl** [comment]
The proposed patch should fix this, however I want to wait after the 380.63 beta cycle has completed before applying it to the master repo.
