### ISSUE TITLE
AC68U: Dual WAN with failover is broken after upgrade from 380.58 to 380.62_1

### ISSUE THREAD

**Issue by imammedo** [RMerl/asuswrt-merlin#1081]
Screenshot with Dual WAN settings is attached <img width="755" alt="screen shot 2016-10-31 at 01 22 01" src="https://cloud.githubusercontent.com/assets/28249/19841234/97dd698c-9f08-11e6-8495-b102ebf05bdf.png">.

From both uplinks the router should get IP by DHCP, however when I ssh into it 
'ip addr' shows that vlan3 interface for backup link is down:

  9: vlan3@eth0: <BROADCAST,MULTICAST> mtu 1500 qdisc pfifo state DOWN 
     link/ether 30:5a:3a:c3:f9:38 brd ff:ff:ff:ff:ff:ff

The vlan3 interface by itself seems fine as I can manually put it in up state and then feed it to "udhcpc -i vlan3 -b"  after which it gets IP address from backup uplink.

**Comment by imammedo** [comment]
the same issue with 380.61_0 firmware

**Comment by RMerl** [comment]
I don't touch the Dual WAN code, as it's too complex, and undocumented.

**Comment by pepeEL** [comment]
Send issue to ASUS
