### ISSUE TITLE
AsusWRT-Merlin - secondary WAN disable

### ISSUE THREAD

**Issue by chimcen** [RMerl/asuswrt-merlin#1082]
Hi,

is or will it possible to manually disable (tun off) the secondary WAN? I use the option Dual-WAN because i'm behind a cable modem on LAN1. The router wants to setup a secondary WAN (for fallback e.g.), but i didn't have a secondary WAN connected - so the router will alltime mark the secondary WAN as "nor connection - DHCP problem"...
It not a technicaly problem - its a cosmetic one...
![secondarywan](https://cloud.githubusercontent.com/assets/22658487/19847672/e1e28e50-9f48-11e6-80a5-b7d57528ce3a.JPG)

**Comment by RMerl** [comment]
I don't touch the dual wan code, as it's too complex, and undocumented.

**Comment by pepeEL** [comment]
Send issue to ASUS
