### ISSUE TITLE
post-mount script not run

### ISSUE THREAD

**Issue by hackvanru** [RMerl/asuswrt-merlin#1088]
ASUS RT-N66U Firmware: 380.62_1

post-mount script does not run, although pre-mount script is run normally.

Nov  5 01:36:28 kernel: sd 0:0:0:0: [sda] 62683136 512-byte hardware sectors (32094 MB)
Nov  5 01:36:28 kernel: sd 0:0:0:0: [sda] Write Protect is off
Nov  5 01:36:28 kernel: sd 0:0:0:0: [sda] Assuming drive cache: write through
Nov  5 01:36:28 kernel: sd 0:0:0:0: [sda] Assuming drive cache: write through
Nov  5 01:36:28 kernel:  sda: sda1
Nov  5 01:36:28 kernel: sd 0:0:0:0: [sda] Attached SCSI removable disk
Nov  5 01:36:28 kernel: sd 0:0:0:0: Attached scsi generic sg0 type 0
Nov  5 01:36:29 custom script: Running /jffs/scripts/pre-mount (args: /dev/sda1)
Nov  5 01:36:29 admin: /dev/sda1
Nov  5 01:36:29 kernel: kjournald starting.  Commit interval 5 seconds
Nov  5 01:36:29 kernel: EXT3 FS on sda1, internal journal
Nov  5 01:36:29 kernel: EXT3-fs: mounted filesystem with ordered data mode.
Nov  5 01:36:29 syslog: USB ext3 fs at /dev/sda1 mounted on /tmp/mnt/sda1
Nov  5 01:36:29 usb: USB ext3 fs at /dev/sda1 mounted on /tmp/mnt/sda1.
Nov  5 01:37:07 crond[251]: time disparity of 665196 minutes detected

admin@RT-N66U:/jffs/scripts# ls -la
drwxr-xr-x    2 admin    root             0 Nov  5 01:35 .
drwxr-xr-x    7 admin    root             0 Jan  1  1970 ..
-rwxrwxrwx    1 admin    root            21 Nov  5 01:35 post-mount
-rwxrwxrwx    1 admin    root            21 Nov  5 01:28 pre-mount

admin@RT-N66U:/jffs/scripts# cat post-mount 
#!/bin/sh

if [ $1 = "/tmp/mnt/sda1" ]
then
  ln -sf $1/entware /tmp/opt
fi

Сan I do something wrong?

**Comment by RMerl** [comment]
Works for me:

```
admin@Stargate88:/tmp/home/root# cat /tmp/syslog.log | grep post-mount
Jul 31 20:00:24 custom script: Running /jffs/scripts/post-mount (args: /tmp/mnt/KT410)
```
