### ISSUE TITLE
Daylight savings for California, USA

### ISSUE THREAD

**Issue by calvintam236** [RMerl/asuswrt-merlin#1089]
Hi there, I have installed v380.62_1 on ASUS RT-AC68U last week.

I just notice that I cannot set the correct daylight savings time for my area. The firmware limited to the first five days of the month, but California DST starts at Sunday, March 13, 2:00 AM and end at Sunday, November 6, 2:00 AM this year. The time on the router is definitely goes wrong. Same situation for next year.

Any chance the FW can make the list longer or change it to a text field?

**Comment by RMerl** [comment]
The second field is for the week, not for the day.  Since a day can only happen up to 5 times within a month, that's why that field is limited to five.  The third field is where you chose the day of the week.  So typically, this would be the 2nd Sunday.
