### ISSUE TITLE
dnsmasq: loop detection not available: set HAVE_LOOP in src/config.h

### ISSUE THREAD

**Issue by hcgonzalezpr** [RMerl/asuswrt-merlin#1090]
I'm trying to enable --dns-loop-detect to prevent a loop in two dnsmasq I have configured are trying to resolve local names without domain causing the loop, dnsmasq suggest using this option but this option is currently disabled.

If it does not make the binary too large would It be possible to include it?

For reference heres what im trying to do that create the loop:
http://www.snbforums.com/threads/can-dnsmasq-be-configured-to-search-secondary-domain.35524/

**Comment by RMerl** [comment]
Somehow, the binary size doesn't change when enabling this build time option.  The only side effect is a bit of additional memory usage, as it adds a UID element to a server structure.
