### ISSUE TITLE
Original timestamps are not retained on files within the firmware

### ISSUE THREAD

**Issue by blackfuel** [RMerl/asuswrt-merlin#1092]
For example, the timestamp on /rom/ca-bundle.crt is always updated even when the file stays the same.  If we have the original timestamps, then we will be able to see just by looking at the timestamp, which binaries come directly from Asus and the ones compiled by the firmware build process.  For example, the C runtime library binaries appear to come directly from Asus.

How to fix it:   If you bind mount the Linux 'cp' and 'install' programs to your own scripts, then you can add the extra command arguments to retain the original file timestamp during the firmware build process.  This requires zero changes to the Asuswrt makefiles, which makes things easy.  You're just adding a "-pv" argument each time the programs 'cp' and 'install' get invoked by the makefiles.

Here's how I do it.  These are scripts, just remove the ".txt" extension.
[cp.txt](https://github.com/RMerl/asuswrt-merlin/files/623436/cp.txt)
[install.txt](https://github.com/RMerl/asuswrt-merlin/files/623437/install.txt)

**Comment by RMerl** [comment]
I'm not fond of those kind of tricks because you never know when they might break something at some point - fiddling with file datestamp can wreck havok with build systems that rely on datestamps to determine what needs to be rebuild.  I prefer not to try my luck with these, sorry.
