### ISSUE TITLE
Support for RT-ACRH13?

### ISSUE THREAD

**Issue by gvillo** [RMerl/asuswrt-merlin#1093]
Is it possible to install Asus merlin on the brand new router from Asus?: https://www.asus.com/us/Networking/RT-ACRH13/

Thanks!

**Comment by RMerl** [comment]
No.

**Comment by tmendes** [comment]
Forecast for support?

**Comment by unsynaps** [comment]
It seems to be Atheros chipset not Broadcom. So support is a no go.

**Comment by RMerl** [comment]
Will never happen.
