### ISSUE TITLE
GuestNetwork at different channel

### ISSUE THREAD

**Issue by hover20** [RMerl/asuswrt-merlin#1100]
Hey Guys,

yesterday I installed Asuswrt-Merlin on my AC68U and it works great! Thanks a lot for this firmware to every developer!

I have a question: There are round about 25 Wlan networks in my area, so I have strong performance issues in the evening. I activated DFS  for 5 Ghz network. My problem is, that some devices not supporting DFS. So I think about creating the following:

**Wlan 1**: 5 Ghz, DFS
**Guest Wlan network 1**: 5 Ghz without DFS with intranet access
**Guest Wlan network 2**: 2,4 Ghz without intranet access (Real guest network)

But if I activate DFS, my "Guest Wlan network 1" also uses a DFS channel. 

--> Is it possible to deactivate the DFS feature for a single Guest network?
--> I don't want to use a 2,4 Ghz network for my guest wlan networks.

Thanks a lot!

Flo

**Comment by RMerl** [comment]
Guest networks don't use a separate radio, they are just virtual interface on the primary radio.  Therefore they all share the same channel and other wireless configuration.
