### ISSUE TITLE
Disk mount and /jffs/scripts issue

### ISSUE THREAD

**Issue by giveup** [RMerl/asuswrt-merlin#1101]
In 380.63, Disk may not properly mount.
df -h 
/dev/sdb                  3.6T      2.8T    839.1G  77% /tmp/mnt/sda1 # USB3 GPT
/dev/sda1                 1.8T      1.1T    704.6G  62% /tmp/mnt/sda(1) # USB2 MBR  # wrong mount point
It need reboot twice to fix mount problem
/dev/sdb                  3.6T      2.8T    839.1G  77% /tmp/mnt/sdb1 # USB3 GPT
/dev/sda1                 1.8T      1.1T    704.6G  62% /tmp/mnt/sda1 # USB2 MBR # Correct

And the /jffs/scripts/example.shell  wont't excute after boot
 ls -l
-rwxrwxrwx    1 admin    root           387 Nov  6 01:16 shell # This wont't excute
-rwxrwxrwx    1 admin    root          1268 Nov 10 20:14 firewall-start  # This wont't excute
-rwxrwxrwx    1 admin    root            81 Aug  1  2015 post-mount
-rwxrwxrwx    1 admin    root           190 Aug  1  2015 services-start
-rwxrwxrwx    1 admin    root            43 Aug  1  2015 services-stop
In the previous version(380.62),They worked fine. 
And I also try to reset to factory.The problem still exists
Sorry for my bad English.

**Comment by RMerl** [comment]
Please use the support forums at SNBForums for support requests.
