### ISSUE TITLE
src-rt / Makefile recommendations

### ISSUE THREAD

**Issue by azdps** [RMerl/asuswrt-merlin#1103]
In the src-rt/Makefile samba3 is set with the following code:

```
	if [ "$(CONFIG_LINUX26)" = "y" ] || [ "$(SAMBA3)" = "y" ]; then \
		sed -i "/RTCONFIG_SAMBA3/d" $(1); \
		echo "RTCONFIG_SAMBA3=y" >>$(1); \
	fi; \
```

I would suggest you change it to the following instead:

```
	if [ "$(SAMBA3)" = "y" ]; then \
		sed -i "/RTCONFIG_SAMBA3/d" $(1); \
		echo "RTCONFIG_SAMBA3=y" >>$(1); \
	fi; \
```

**The problem is that when you set samba3=n in src-rt / target.mak it doesn't work**. There's nothing in the Makefile that will prevent samba3 from being built into the firmware. 

So there's 4 separate samba's:

SAMBACLIENT (disabled by default)
SAMBA3 (disabled by default)
SAMBA36 (disabled by default)
SAMBASRV (enabled by default)

To enable:
SAMBACLIENT=y
SAMBA3=y
SAMBA36=y

To disable:
NO_SAMBA=y (SAMBASRV)

My suggestion would be to disable SAMBASRV by default like the rest of them in router / config_base. Completely remove NO_SAMBA from the code base and add code to enable SAMBASRV in src-rt / Makefile like the other samba's. I understand that other files may need to be modified as well to accomplish this.

NO_SAMBA is kinda deceiving unless you really look at the code. It only disables SAMBASRV and non of the other samba's.

**Comment by RMerl** [comment]
I don't want to make changes to Asus's own settings unless it's absolutely necessary.  Otherwise, it only makes my job harder whenever merging new GPL versions.
