### ISSUE TITLE
Dnsmasq --address performance improving 

### ISSUE THREAD

**Issue by giveup** [RMerl/asuswrt-merlin#1106]
Dnsmasq matches domain names for --ipsets, --server, and --address options by iterates over linked list. It is good enough for general use, but slows down as the domain names to be matched grows. e.g Ad Block host file.

https://github.com/infinet/dnsmasq

**Comment by RMerl** [comment]
Our dnsmasq build is customized, and Asus frequently update it, so I don't want to go through the trouble of going with a fork that might not be 100% compatible with Asus's custom version.
