### ISSUE TITLE
Support for RT-AC66U hardware revision B1?

### ISSUE THREAD

**Issue by peterdenk** [RMerl/asuswrt-merlin#1107]
On the site (http://asuswrt.lostrealm.ca/about)
RT-AC66U (hardware revision B1 is NOT supported)

In README.md
RT-AC66U

Which one is correct?

**Comment by RMerl** [comment]
Hardware revision B1 is a newer revision that only appeared on the 
market a few weeks ago.  That new revision is not supported.

**Comment by oldskooler** [comment]
Is there any plan in the near future that you might do support this device?
Thank you very much

**Comment by RMerl** [comment]
I don't know, Asus didn't answer me when I asked if the hardware was 100% compatible with the RT-AC68U firmware or not.  If it is, then people can simply flash the RT-AC68U firmware.  If not, then I don't know if it will ever be supported or not, as it will depend on the amount of work required versus how widespread this model will be.

**Comment by peterdenk** [comment]
Ok, then README.md needs to be updated with this information.
