### ISSUE TITLE
Make-WiFi-Fast project patchsets for LEDE project in Asuswrt-merlin?

### ISSUE THREAD

**Issue by Hedda** [RMerl/asuswrt-merlin#1108]
Please consider looking at the Make-WiFi-Fast project patchsets for LEDE project in Asuswrt-merlin. Read:

http://www.cnx-software.com/2016/11/16/make-wifi-fast-project-massively-improves-wifi-performance-of-busy-wifi-routers/

Make-WiFi-Fast project uses among other things the Bufferbloat project to prevent excessive buffering by improving queue handling.

https://www.bufferbloat.net/projects/

https://www.bufferbloat.net/projects/make-wifi-fast/wiki/

Make-wifi-fast project patchsets are queued for  Linux 4.9 and 4.10 already, and yet-to-be submitted patchsets for LEDE (OpenWrt fork) can be found here:

https://kau.toke.dk/git/lede/

Dave Täht gave a presentation of his work on Make-WiFi-Fast project entitled “Fixing WiFi Latency… Finally"

http://www.linuxplumbersconf.com/2016/ocw//system/presentations/3963/original/linuxplumbers_wifi_latency-3Nov.pdf

https://www.youtube.com/watch?v=RCrRU4KdaHk`

There’s also an article on LWN.net (reserved to subscribers) discussing about this very topic. 

Could this maybe be added to Asuswrt Merlin firmware?

**Comment by RMerl** [comment]
No, as Broadcom is using a much older kernel.
