### ISSUE TITLE
Custom DDNS-Start and WAN-Start for GoDaddy

### ISSUE THREAD

**Issue by blckwolf** [RMerl/asuswrt-merlin#1111]
Hi All:

If you have your own domain through GoDaddy, I have created a WAN-Start script and a DDNS-Start Script so that you can actually have the IP address of a sub-domain (or even your domain) automatically updated when your router restarts or if the IP changes on your router.  

WAN-Start:  Once the router (re)boots, it grabs the router's either or both the  IPv4 and IPv6 address.  It then compares those addresses to what your domain zone files have listed in the A and AAAA (if you're using v6), and if either of those addresses has changed, it updates the appropriate record to reflect the change.  It also optionally will send you an email and/or text message to any address/cell phone you want through Gmail, to let you know of the event.  There is no limit to how many accounts/cell #'s you have the mail/text message sent out to.

DDNS-Start:  Acts just like any other version of DDNS start, but again, checks the IPv4, IPv6 (optionally), and will optionally email and/or text message you of any changes, again, through Gmail.

Both scripts will log in to GoDaddy securely, and update the domain or sub-domain - depending on how you are set up.

RMerl:  If you want to post them in the wiki, I'll be glad to send them to you.

V/R

BlackWolf

**Comment by RMerl** [comment]
Anyone with a Github account can edit the wiki.

The wan-start script is probably redundant, since ddns-start will only run whenever the WAN IP is changed.
