### ISSUE TITLE
Native IPV6 via PPPoe does not set default gateway

### ISSUE THREAD

**Issue by Netriak** [RMerl/asuswrt-merlin#1115]
When I configure native IPV6 on my pppoe interface (ppp0), the default gateway is not set.
That is, the "WAN IPv6 Gateway" field on the ipv6 tab of the system log page is empty, and there is no IPV6 default route at all.
Naturally, this means that reaching any host outside of the local network via IPV6 is impossible.

Manually setting the default gateway (to the remote link local address provided to pppd, which is visible in the system log) via SSH/wan-start script restores full IPV6 funtionality:

route add -A inet6 default gw {remote link local address goes here} dev ppp0

That is, the "WAN IPv6 Gateway" is properly filled in and non-local hosts are accessible via IPV6.

using firmware 380.63_2

**Comment by RMerl** [comment]
I don't touch IPv6 anymore.  Any issue will have to be resolved upstream - I have no way of testing this properly.

**Comment by Cilph** [comment]
Thank you @Netriak. Thanks to you I was able to figure out why my connection wasn't working.
