### ISSUE TITLE
Apple TV frequent performance issue solved after restarting router

### ISSUE THREAD

**Issue by hanoii** [RMerl/asuswrt-merlin#1119]
Hi,

I have an Asus RT-AC68U and most of time it works great, but I have been having very frequent annoying issues with Apple TV streaming super slow on either Netflix or other Apps.

I know this is very off-topic, but the the strangest issue is that it's sorted once I reboot the router, so some incompatibility must be affecting. They are in the same visual line so it's not a matter of wifi not reaching.

I wonder if you can suggest what I could do to track this down or if you have any other ideas, any config I could try?

Router is at the latest - 380.63_2. And besides a few port forwards and a DDns, there's nothing too specific configured on it.

Thanks,
Ariel=

**Comment by RMerl** [comment]
Please use the support forums at SNBForums for support requests.
