### ISSUE TITLE
[Request] Source ip field in NAT view

### ISSUE THREAD

**Issue by Mikiya83** [RMerl/asuswrt-merlin#1120]
Hello
First, thank you for your amazing work ! I am a happy user of your firmware for mare than a year.
But today, i would just suggest you a little adding : a source ip field in NAT view. I know we can set a rule in 
nat-start but JFFS must be enabled, and it's  not very convenient for a such basic config, many other routers have this so maybe you could add this field in GUI.

Thank you again

**Comment by RMerl** [comment]
Would require changing an internal structure that would break backward compatibility with the stock firmware.  Too many bad experiences in the past whenever I tried to do such changes, so I'm not doing it anymore.
