### ISSUE TITLE
DNS filtering feature request

### ISSUE THREAD

**Issue by Steve-7** [RMerl/asuswrt-merlin#1124]
I would like an option in the dns filtering menu to filter all connected IPs

Thank you for considering

**Comment by RMerl** [comment]
That's what the Global Filter does - it applies to all connected clients.

**Comment by Steve-7** [comment]
Thanks

**Comment by Steve-7** [comment]
so if i enter multiple dns ips, the traffic will be filtered by all those dns'

**Comment by RMerl** [comment]
No, only one single DNS can be used, the one you set as "Global".  The custom fields below are only for use for clients for which you set it to ONE of the three "Custom" types.

Please use the support forums at SNBForums for further support requests.
