### ISSUE TITLE
Port forwarding from multiple WAN IPs

### ISSUE THREAD

**Issue by zanthius** [RMerl/asuswrt-merlin#1125]
Hi, just wondering if it's possible to implement port forwarding from multiple WAN IP addresses?

My ISP has assigned a /29 block of IPs to my service, but am not able to make use of them without port forwarding.

Thanks for your time.
(Love the software BTW)

**Comment by RMerl** [comment]
There are currently no plan to implement support for entire WAN subnets, as this would require too many extensive changes to the code, and fall beyond the scope of this project, sorry.
