### ISSUE TITLE
Adaptive QoS -> Web History stoppen working in 380.63_2 on iPhone

### ISSUE THREAD

**Issue by callebokedal** [RMerl/asuswrt-merlin#1128]
Just updated my AC68U from 380.58_0 to 380.63_2 - and see that Adaptive QoS -> Web History stopped working on my iPhone. It did work on version  380.58_0.

Using desktop and Chrome (v 54) with 380.63_2 works as excpeted (even more history in version 380.63_2?). But not Safari on iOS 10.1.1 + 380.63_2.

The problem I experiance is that the "All client" drop down only contains that text - and no other clients (but using desktop browser displays all clients). So I can't chose any clients to view when using my iPhone.

**Comment by RMerl** [comment]
Anything related to the Trend Micro engine is outside of my control.
