### ISSUE TITLE
OpenVPN server cause high cpu

### ISSUE THREAD

**Issue by lceron** [RMerl/asuswrt-merlin#1130]
been running RT-AC68U_380.63_2 and decided to play around with the OpenVPN server option.  I was successful in connecting but it makes my Windows 10 cpu run at 50 percent or more.  I have checked task manager for what is causing the cpu to run high and the only thing running high at 50 percent is the OpenVPN daemon.  I have since reloaded the stock Asus firmware and it does not cause the cpu to run high.  Can you please look into this?

**Comment by RMerl** [comment]
I fail to see how the remote server could have an impact on the desktop client.  I use OpenVPN on a daily basis without any problem.  Look at your OpenVPN system log for any error message.
