### ISSUE TITLE
Support for Asus RT-AC1200G+ 

### ISSUE THREAD

**Issue by volkanp** [RMerl/asuswrt-merlin#1133]
I cannot find any documentation or support for Asus RT-AC1200G+ aside from deducing that this device is not supported at all.

There is practically no information (aside from an DD-WRT forum administrator confirming that work is being carried out for this particular implementation) that indicates any custom firmware options to choose from over the built-in Asus firmware.

Can anyone clarify what the hold up is for the support of this device/model or whether they can point me in the right direction to keep track of an WRT implementation, if any?

**Comment by RMerl** [comment]
The list of supported models is in the Wiki: https://github.com/RMerl/asuswrt-merlin/wiki/Supported-Devices

There are no plans to support any of the RT-AC1200 models.
