### ISSUE TITLE
ipv6 passthrough and NAT Acceleration causes cyclic reboot

### ISSUE THREAD

**Issue by YuriyKischenko** [RMerl/asuswrt-merlin#1134]
Enabling ipv6 passthrough and NAT Acceleration causes cyclic reboot in the latest Asuswrt 380.63_2 on rt-ac66u.
No issues with the latest firmware from Asus

**Comment by RMerl** [comment]
Anything related to NAT acceleration is outside of my control.  If there was a bug that was fixed later on by Asus we will have to wait for new source code to become available for all models.

**Comment by onetwobr** [comment]
I´m having the same issue on Asuswrt 380.65_2 in my AC66U too and this is not the first time I have faced exactly the same problem.

If with Asus firmware the IPv6 Passthrough works fine but overall performance on local network is poor, I'm starting to think about in possibility of a router bug. 

@YuriyKischenko Did you find any old version of Merlin where the problem didn´t occur?
