### ISSUE TITLE
OpenVPN client connect error on Merlin, But it works on WinOS client.

### ISSUE THREAD

**Issue by edoko** [RMerl/asuswrt-merlin#1137]
I used RT-N66U and the latst merlin firmware.(380.63_2)
I tried factory reset and connect the OpenVPN client, but failed.
It cause "openvpn[7915]: SIGTERM[hard,] received, process exiting".

But, I used the same .ovpn file, It worked Windows OS(OpenVPN Client).

I upload merlin syslog and windows os client log.
[syslogs.zip](https://github.com/RMerl/asuswrt-merlin/files/634326/syslogs.zip)

Thank you.

**Comment by RMerl** [comment]
Please use the support forums at SNBForums for support requests.
