### ISSUE TITLE
Curl not complied with ipv6 support

### ISSUE THREAD

**Issue by jakehilluk** [RMerl/asuswrt-merlin#1138]
`curl 7.21.7 (arm-unknown-linux-gnu) libcurl/7.21.7 OpenSSL/1.0.2h zlib/1.2.5
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smtp smtps telnet tftp
Features: Largefile NTLM SSL libz TLS-SRP`

version: 380.61
build: Fri Aug 5 01:18:59 UTC 2016 merlin@30c7946

Unsure if this has been fixed in later builds, just noticed it on my router.

**Comment by RMerl** [comment]
Interesting, Curl does show the -6 command-line switch, yet I don't think that IPv6 support is really there.  I'll have to investigate in forcing IPv6 support at build time to see if it makes any difference.
