### ISSUE TITLE
Hostfile order

### ISSUE THREAD

**Issue by bosim** [RMerl/asuswrt-merlin#1147]
When I do a traceroute from my LAN I see the following
```
traceroute to google.dk (172.217.20.3), 30 hops max, 60 byte packets
 1  router.asus.com (192.168.1.1)  2.289 ms  2.321 ms  2.432 ms
...
```

My router already has a custom hostname, the hostfile on the router reflects so. It would be nice to get the custom hostname as the first, so dnsmaq would use that for DNS resolution.

**Comment by RMerl** [comment]
I will have to make sure it doesn't break anything, as Asus is internally relying on router.asus.com in a couple of places.

**Comment by unsynaps** [comment]
Is there anything major dependent on these names? For a while now I have had a script to remove them for the same reason as bosim and have no had any issues (that I can see).

` cat hosts.postconf
#!/bin/sh
CONFIG=$1
source /usr/sbin/helper.sh

pc_replace "192.168.1.1 router.asus.com" "" $CONFIG
pc_replace "192.168.1.1 www.asusnetwork.net" "" $CONFIG
pc_replace "192.168.1.1 www.asusrouter.com" "" $CONFIG`

**Comment by RMerl** [comment]
The last two are no longer active (Asus even lost control of these domain names), but first one is used, for instance, by the QIS redirection, probably by the AiProtection block pages as well.  I would not recommend removing it.
