### ISSUE TITLE
Combined IPv6 stateless and stateful

### ISSUE THREAD

**Issue by bosim** [RMerl/asuswrt-merlin#1148]
When I used the router of my provider I was obtaining two ipv6 addresses, one regular with the prefix + mac address and one "pretty" stateful one. It would be so cool if merlin could support this, because some devices does not support stateful config, i.e. android phones/tablets and iOS devices, if I go all in on stateful these devices will not have ipv6 access, however on stateless it will work, but I don't get "pretty" (rememberable) addresses.

**Comment by RMerl** [comment]
Architectural changes of that kind are beyond the scope of this project, sorry.
