### ISSUE TITLE
Renew IP or wait mor time

### ISSUE THREAD

**Issue by scrambler86** [RMerl/asuswrt-merlin#1150]
My router restarts with the following message: QTN connection lost

The message is in the file:
Https://github.com/RMerl/asuswrt-merlin/blob/master/release/src/router/rc/watchdog.c#L2468

Is it mandatory to restart the router?

**Comment by RMerl** [comment]
This has nothing to do with your Internet connection, it's a warning that the Broadcom firmware is no longer able to talk to the Quantenna firmware, which controls the 5 GHz radio on the RT-AC87U.  A reboot is required to restart the crashed Quantenna CPU.

**Comment by scrambler86** [comment]
And what is that due to?
Is there no other way to solve the problem?
