### ISSUE TITLE
GPL upstream sync: 3.0.0.4.380.4164

### ISSUE THREAD

**Issue by fengsi** [RMerl/asuswrt-merlin#1151]
https://www.asus.com/Networking/RTAC68U/HelpDesk_Download/

http://dlcdnet.asus.com/pub/ASUS/wireless/RT-AC68U/GPL_RT_AC68U_30043804164.zip

**Comment by RMerl** [comment]
I need GPL updates for all supported models, so this is of limited use to me.

Also if you see the commit log, I already merged what was the most important part of it - the security fixes for httpd.
