### ISSUE TITLE
Rounding issue in "Traffic Manager - Traffic Monitor"

### ISSUE THREAD

**Issue by Cpuroast** [RMerl/asuswrt-merlin#1153]
RT-AC3100
Upgraded to 380.64 final from 380.63_2

![rounding issue](https://cloud.githubusercontent.com/assets/3321892/21284444/24a8d766-c3e9-11e6-8e2b-fee45a76654f.png)

This may be related to https://github.com/RMerl/asuswrt-merlin/commit/168c54266f5987ab3c0289897d8725aace362f2a

**Comment by RMerl** [comment]
This looks more like a scaling issue in chart.js, as you have very small values but are using a very large scale.

**Comment by Cpuroast** [comment]
Right, after I reverted back to 380.63_2 to test, the same issue occurred.

Once a few days had past with enough traffic, that goes away, so it only happens at the very beginning when the router is first booted.
