### ISSUE TITLE
Difficulty upgrading RT-AC68U

### ISSUE THREAD

**Issue by trajano** [RMerl/asuswrt-merlin#1156]
I am trying to upgrade using the firmware upgrade on the web app and it had reported that the image is not valid.

I have verified the image as well using shasum

<pre>
Janets-Air:Desktop archie$ shasum -a 256 RT-AC68U_380.64_0.trx 
162a5d020f106dab3f535d09022d38da529575f5aa6bcde70eb26edf4315bf27  RT-AC68U_380.64_0.trx
Janets-Air:Desktop archie$ cat sha256sum.txt 
162a5d020f106dab3f535d09022d38da529575f5aa6bcde70eb26edf4315bf27  RT-AC68U_380.64_0.trx
</pre>

I have also tried uploading from a Windows Machine and restarted the router as well

No luck at the moment.

Are there any logs that I can look at to see what could've gone wrong?

**Comment by RMerl** [comment]
Please use the support forums at SNBForums for support requests.
