### ISSUE TITLE
OpenVPN UDP Server Regression

### ISSUE THREAD

**Issue by zquestz** [RMerl/asuswrt-merlin#1158]
Just updated to the latest firmware on my RT-AC88U and noticed that my UDP based OpenVPN server no longer functions. I have both the ipv6 and normal firewall enabled, but disabling them does not appear to resolve the issue. My TCP based server continues to work as expected.

They both appear to launch, and I can even connect to the UDP server, but it doesn't actually forward any traffic, to the lan or to the internet.

I am happy to provide any logs you need to address this.

In iptables-save the tun lines are:

```
-A PREROUTING -i tun21 -j MARK --set-xmark 0x1/0x7
-A PREROUTING -i tun22 -j MARK --set-xmark 0x1/0x7
-A INPUT -i tun21 -j ACCEPT
-A INPUT -i tun22 -j ACCEPT
-A FORWARD -i tun21 -j ACCEPT
-A FORWARD -i tun22 -j ACCEPT
```

ifconfig shows:

```
tun21      Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  
           inet addr:10.8.0.1  P-t-P:10.8.0.1  Mask:255.255.255.0
           UP POINTOPOINT RUNNING NOARP PROMISC MULTICAST  MTU:1500  Metric:1
           RX packets:0 errors:0 dropped:0 overruns:0 frame:0
           TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
           collisions:0 txqueuelen:100 
           RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

tun22      Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  
           inet addr:10.16.0.1  P-t-P:10.16.0.1  Mask:255.255.255.0
           UP POINTOPOINT RUNNING NOARP PROMISC MULTICAST  MTU:1500  Metric:1
           RX packets:16065 errors:0 dropped:0 overruns:0 frame:0
           TX packets:25562 errors:0 dropped:0 overruns:0 carrier:0
           collisions:0 txqueuelen:100 
           RX bytes:1799572 (1.7 MiB)  TX bytes:27908752 (26.6 MiB)
```

**Comment by RMerl** [comment]
I doubt the issue is related to UDP, because I'm connected at the moment over VPN with my router, using UDP.  No problem accessing my desktop at the remote end of the tunnel using RDesktop.

Recheck the rest of your configuration, especially the custom settings section.  I don't remember seeing any config change in OpenVPN 2.3.14, but they might have changed something else without mentionning it in the changelog.

**Comment by zquestz** [comment]
Hmm very odd, I have no custom connection options, and was able to connect fine with both my computer and Android device with the same config on my N66U... Now with my new router, same config, just with the newer firmware it no longer functions...

One other quick question, and perhaps I got a lemon model... I can't even seem to ping ::1 on the router when ssh'd in. Is this expected? I would expect `ping6 ::1` to work, and it doesn't return any packets.

**Comment by zquestz** [comment]
Just compared my configs, my UDP and TCP configs are identical except protocol. Arg =(

**Comment by zquestz** [comment]
NM, got it working. Needed to change the cipher type. Thanks.

**Comment by zquestz** [comment]
Note: exported configs DID change. This was added to my UDP server:

```
cipher AES-128-CBC
```

**Comment by RMerl** [comment]
After a factory default reset, the default cipher is no longer "default" (which for OpenVPN 2.3 means the vulnerable BF cipher) but explicitely AES-128-CBC.  That must be why your exported file changed if you never selected a specific cipher in the past.
