### ISSUE TITLE
SSH keys longer than 2048 don't seem to work.

### ISSUE THREAD

**Issue by ncrmro** [RMerl/asuswrt-merlin#1159]
Was wondering if any one has issues with this. I have an ssh config and have manually pointed it a 2048 key that works..

**Comment by unsynaps** [comment]
This is not all that help full but... Why do you really need SSL keys larger than 2018 on a home router?

**Comment by ncrmro** [comment]
Ideally it would support ed25519, but I have trouble using those keys as well on some services Just seems it would be more secure. To super more recent standards. I guess it might be out of the scope of this project.

**Comment by RMerl** [comment]
You will have to contact the dropbear author if you want support for new ciphers.  This firmware merely uses his SSH daemon.

A 2048-bit key works fine, I'm using one myself.

**Comment by ncrmro** [comment]
@RMerl thanks for pointing me the right direction

**Comment by RMerl** [comment]
Note that I never tried anything stronger than 2048-bit, but the config buffer should be large enough to support one.
