### ISSUE TITLE
Hosts using TOR are inaccessible via OpenVPN

### ISSUE THREAD

**Issue by vabello** [RMerl/asuswrt-merlin#1165]
I noticed that when TOR is enabled and a host is added to use it, that host can no longer be reached by any OpenVPN client connected to the router. It's very easy to reproduce.

**Comment by RMerl** [comment]
That's normal.  The idea of Tor is that the host traffic is ONLY going through Tor.  Any traffic coming from outside the Tor tunnel shouldn't generate outbound traffic, or it will defeat the purpose of Tor.

**Comment by vabello** [comment]
Ah, ok. I thought I read somewhere it was only http/https traffic that got tunneled. My mistake!
