### ISSUE TITLE
Is there a way to track WAN data usage per device?

### ISSUE THREAD

**Issue by dannieboiz** [RMerl/asuswrt-merlin#1166]
Trying to figure out what's pulling all the WAN bandwidth on my network as I'm using 20-30gb of data a day with the new Comcast 1tb cap I'm getting charged with overage every month.

**Comment by unsynaps** [comment]
What are you using to track this? The bandwidth monitor does not work properly unless you shit off spanning tree protocol.

**Comment by RMerl** [comment]
Please use the forums at SNBForums for support requests.
