### ISSUE TITLE
openssl-1.0.0q

### ISSUE THREAD

**Issue by umerov1999** [RMerl/asuswrt-merlin#1169]
This rom has a openssl-1.0.0q and openssl-1.0.2-j. Why the need for openssl-1.0.0q?
(В прошивке присутствуют два openssl - 1.0.0q и 1.0.2-j. Зачем нужна старая версия?)

**Comment by themiron** [comment]
because builtin beceem winax support can't work with newer versions. asus legacy

**Comment by Thynix** [comment]
Is that something in a firmware blob that we can't fix, or do we have source for that?

**Comment by RMerl** [comment]
Closed source, nothing we can do about it.  Probably outside of Asus's control as well, hence they decided to include a legacy version of openssl for those specific components relying on them.

If you don't use a Beceem-compatible 4G modem then this has zero security impact.
