### ISSUE TITLE
Add parted tool (currently only fdisk present)

### ISSUE THREAD

**Issue by mieszkomularczyk** [RMerl/asuswrt-merlin#1171]
When I connect 4TB drive to my 68U using the latest merlin firmware (as of Dec 30, 2016) AND the drive is fully cleaned (filled with zeroes), without any partition table, I cannot make use of the drive properly using just the  linux on the router.
The first thing is to create a partition table, however I do need GPT for such a drive. Built-in FDISK also reports the following problem:
_fdisk: device has more than 2^32 sectors, can't use all of them_
I would like to create a single 4TB parition with ext4, however I need full-GPT compatible partition tool. FDISK is old and PC-based Linux systems use PARTED. Please add parted tool to the distribution.

**Comment by RMerl** [comment]
Use a Linux live CD.  There's no reason to devote megs of the limited flash to a disk management tool that isn't necessary to run a router, sorry.

**Comment by mieszkomularczyk** [comment]
Hello,
parted takes little space. If so, then I suggest removing fdisk as well. First it is a disk management tool, as you write, second it is useless in the modern days. I would recommend replacing fdisk with parted or if you want to conserve the space so much, remove the fdisk as well, especially if this is useless (cannot create GPT and does not support >2TB drives)

**Comment by RMerl** [comment]
fdisk is not a separate tool, it's an applet that's part of Busybox, and therefore only takes a few kilobytes.  I'm leaving it there because it has always been there.

**Comment by unsynaps** [comment]
Not to mention fdisk is required to create the partitions the router needs to run **every single time** it starts up (IIRC).

Just write gparted ( http://gparted.org/ ) out to a flash drive and boot off of that to prep the drive before plugging it into the router.

**Comment by mieszkomularczyk** [comment]
Hi, thanks for the advice with gparted. Windows' diskpart is not so good, as it always creates 128MB partition for its own purposed if GPT is used
