### ISSUE TITLE
Test VPN tunnels to determine which one is faster and reroute

### ISSUE THREAD

**Issue by a3rosol** [RMerl/asuswrt-merlin#1175]
A possible enhancement.
My VPN tunnel is chosen semi-randomly by the tunnel provider when the router starts. Once the tunnel is created, connections seem to get slower after a while. I circumvent this by restarting the router at a certain time. Would it be possible to do something like "load balancing" between several VPN clients? Like regular speed tests to determine which client is faster and rerouting the computers?
If not, is there something readily available (like a shell script) that can be deployed?

**Comment by RMerl** [comment]
Not going to implement that, sorry.

If you are having issues caused by a round-robin, then determine the exact IP address that gives you the best performance, and connect to it instead of the DNS hostname.
