### ISSUE TITLE
Merge 4180 for RT-AC66U

### ISSUE THREAD

**Issue by captainepoch** [RMerl/asuswrt-merlin#1180]
Hello there!

I saw at the forum [the 680.65 alpha](http://www.snbforums.com/threads/test-build-asuswrt-merlin-380-65-alpha-builds.36508/) that you don't have the 4180 GPL for RT-AC66U. I saw at the Asus' website the link to donwload the source code. At the [Asus support for RT-AC66U](https://www.asus.com/uk/Networking/RTAC66U/HelpDesk_Download/), just select "Others" and then "Source code".

Or is this router one of those: "or in the case of some models, the provided GPL was missing all closed source components"?

Thank you!

**Comment by RMerl** [comment]
The second.  The AC66U GPL is missing every closed source binary blobs.
