### ISSUE TITLE
OpenVPN is using WAN IP instead of custom DDNS hostname for client.ovpn export

### ISSUE THREAD

**Issue by kylemart** [RMerl/asuswrt-merlin#1185]
I just successfully setup a custom DDNS host (i.e. *.duckdns.org) and ddns-start script for my router running 380.64_2. Now I'm trying to setup the VPN server component of the router. When I export the client.ovpn file through the GUI, and view the contents of the file, the line in the file specifying the remote and port contains my router's public IP address, not the custom DDNS host I set. I can manually telnet into the router and edit the client.ovpn file manually to 'resolve' this, but I was wondering if the system should be doing this automatically.

Reference: http://www.snbforums.com/threads/how-asus-merlin-rt-n66u-openvpn-server-w-dyndns.20076/#post-145492

**Comment by RMerl** [comment]
Is the DDNS type set to "Custom", and did you enter your FQDN in the "Host name" field?  Otherwise, the router has no way of knowing what the FQDN would be, so the export process will use the WAN IP instad of a DDNS hostname.

**Comment by kylemart** [comment]
Thanks for the quick response! Yes, the DDNS type is set to "Custom" and the host name field is set to, essentially, www.mysubdomain.duckdns.org.

**Comment by kylemart** [comment]
http://www.snbforums.com/index.php?threads/35634/
