### ISSUE TITLE
QOS Download and Upload speed boxes mixed up 380.64 R7000

### ISSUE THREAD

**Issue by saveli4** [RMerl/asuswrt-merlin#1187]
Device R7000. FW version 380.64.

When setting upload and download speed in QOS settings the fields are mixed up. Upload speed box sets limit on download speed (tested on speedtest.net) and download box  has absolutely no noticeable effect on anything.

**Comment by mstombs** [comment]
What Asus router is that?

**Comment by stevek123** [comment]
It's a Netgear that is not supported by this firmware.

**Comment by saveli4** [comment]
Ooops. Sorry I followed a wrong link from XWRT-VORTEX website.
