### ISSUE TITLE
DLNA connection breaks regularly on Samsung Smart TV

### ISSUE THREAD

**Issue by mieszkomularczyk** [RMerl/asuswrt-merlin#1190]
I have 380.64_2 on my AC68U with Samsung TV connected over WIFI (UE49KS7000). The TV has god very stable wifi connection (good signal) and e.g. I can watch 3h movie on the HBO GO app on the TV. However when I watch a movie on DLNA streaming (using router's DLNA server and connected USB disk) , it regularly kicks me out after ~20mins. The player simply drops the connection and I have to start the movie again. Same for browsing pictures.
It seems that the DLNA connection/session is unstable. It could be a samsung bug and also if this is a router FW bug, it is for sure in the ASUS base code (problem occurs both with merlin and stock FW).
Before considering this as an router bug, could you advise me how to check e.g. minidlna specifc log files - where do I find them after logging over SSH? Maybe I could increase log level on the router to better diagnose the problem?
I browsed the internet, it looks the problem is known for a few years (?)

**Comment by hgw90** [comment]
I have a similar problem with my setup. I fund a "workaround" for it se link:
http://www.snbforums.com/threads/asus-rt-ac87u-win-10-homegroup-problem.36817/
hopes it works for you!

**Comment by mieszkomularczyk** [comment]
Thanks! Are you sure? The article discusses sth else. I have DLNA on my ASUS router and SamsungTV connected over WIFI, it has nothing to do with Microsoft Windows homegroups.
Could you confirm?

**Comment by hgw90** [comment]
OK it is not your exact setup. 
But my problem is Exactly the same! I could only watch movies and pictures stored on PC from my Samsung TV for about 20-30 min before I had  to reboot my PC My setup:
PC running win 10  homegroup (was an easy way to select what content from the PC I want to have availably on my TV) connected to the router wired (ASUS RT-AC87 firmware 3.0.0.4.380_4180) and then from the router by WIFI to the TV (Samsung Sorry I can't remember the exact  modell nr but UE40 something)

, and it is easy enough to test :)

**Comment by hgw90** [comment]
just toggle the IPv6 setting on the router on or off (doesn't matter witch )
and hopefully it will work until the next time you turn off your router 
and if it don't work just turn it back 
btw my TV modell nr is UE40F8005STXXE

**Comment by hgw90** [comment]
Windows 10 Homegroup seems to use DLNA to stream content to media devices, read: TV (but as usual windows don't call It that :) )  http://windowsreport.com/configure-dlna-server-windows-10/

**Comment by mieszkomularczyk** [comment]
Hello hg90, with all due respect, I think I was unclear in my original issue (now edited). I mean DLNA built in the ASUS router itself with USB disk connected to the router. Assume that thereis JUSt ASUS 68U plus Samsung TV on my network ONLY. No windows machines and any other PCs.

**Comment by hgw90** [comment]
It's all good )

**Comment by RMerl** [comment]
All DLNA services are provided by minidlna.  If there's a bug with either Samsung or miniDLNA, it's outside of my control.

**Comment by mieszkomularczyk** [comment]
@RMerl : could you at least only tell me how do I enable low level logging for miniDLNA server in my router so I get some diag info?

**Comment by eralaj** [comment]
I have been experiencing similar problems with DLNA servers becoming invisible to devices connected through my ASUS RT-AC87. The following actions solved these issues permanently for me (and it is unrelated to whether IPv6 is enabled or not):

1. Log in as admin on your router
2. Go to Advanced Settings -> LAN -> IPTV
3. Under Special Applications, set "Enable multicast routing (IGMP Proxy)" to [Enable] and set "Enable efficient multicast forwarding (IGMP Snooping)" to [Enable]
4. Hit [Save] and your router will restart

You should now be able to see your DLNA Servers from all DLNA clients and be able to stream content without any interruptions.

Note that my RT-AC87 is running firmware version 380.65 by Asuswrt-Merlin.

**Comment by themiron** [comment]
ctf/fa of 5Ghz band could cause it with igmp snooping enabled.
try to connect tv to 2.4Ghz ssid instead

**Comment by eralaj** [comment]
All my devices can now find all DLNA servers on my network irrespective of whether connected on 2.4 GHz or 5 GHz. It has become rock stable. I am very satisfied even though it was not intuitive to solve the problem by enabling multicast routing and efficient multicast forwarding under the heading IPTV. Before testing it I thought that these settings were addressing IPTV services provided by external IPTV providers only. Anyway, problem solved and I am happy.
