### ISSUE TITLE
Update entware install script to include swapfile creation

### ISSUE THREAD

**Issue by latenitetech** [RMerl/asuswrt-merlin#1193]
The currently installed 'entware-setup.sh' (in /usr/sbin) doesn't include a swapfile creation step, which I think is very beneficial to many users, especially noobies.  The script recommended by this Wiki article:
https://www.hqt.ro/how-to-install-new-generation-entware/
is nearly identical to the current one, except it includes a block of code at the bottom to create a swap file, and also adds code to post-mount to enable it on each boot.

Note that the current built-in script contains code to ensure /jffs is enabled (not included in the external script), so a "best of both" would be the recommended update.

**Comment by RMerl** [comment]
@ryzhovau any thought on this?

**Comment by ryzhovau** [comment]
I don't think so, sorry. There's a bunch of external services where no swap is required. Most of them.

**Comment by RMerl** [comment]
Thanks.  Best to let advanced users do it themselves then, so if they run into stability issues, they can't blame us for it :)
