### ISSUE TITLE
Dualwan route rules conflicts with Openvpn server lan communication

### ISSUE THREAD

**Issue by florid2** [RMerl/asuswrt-merlin#1194]
I use 380.64_2 on RT-AC68U setup dualwan in LB mode with routing rules. It tells LAN host 192.168.1.2 only use primary WAN. 
Have DDNS enabled with namecheap. Not sure how it works on Dualwan environment. But I can confirm the A record is primary WAN public IP at that time. 
Also create Openvpn server profile and push the LAN side route. No difficulty to connect openvpn, but the client cannot talk to 192.168.1.2 which has dualwan route rule pointing to primary WAN only. However, the client can talk to 192.168.1. x hosts in the same VLAN which does not have dualwan route rules. I have to delete the dualwan routing rule for 192.168.1.2 to make it accessible via OpenVPN tunnel.  

Not sure if this is by design or known issue. Please help, thanks.

**Comment by RMerl** [comment]
Not touching the Dual WAN code as it's too complixcated.  Also, Dual WAN route configuration is closed source, and cannot be modified.
