### ISSUE TITLE
UPnP issue between 2.4GHz and 5GHz networks

### ISSUE THREAD

**Issue by bnlcr** [RMerl/asuswrt-merlin#1199]
Hi, I did the upgrade from 380.59 to 380.64_2 on my AC87U few days ago, and since then my laptop when using the 5Ghz antenna is not able to see my UPnP renderer which is using the 2.4Ghz antenna (when I use the 2.4Ghz on my laptop, it is working great).
I did not change any settings since the upgrade.
Is it intended? Do I need to change a new setting?
Ps: The Upnp server and controller are on my laptop, I'm not using the router as upnp server. 
Ps2: I'm able to ping the renderer from the laptop, it just seems that the UPnP traffic is dropped by the router..

**Comment by RMerl** [comment]
Please use the support forums at SNBForums for support requests.
