### ISSUE TITLE
"Plus' button on Advanced_ACL_Content is not working on Chrome

### ISSUE THREAD

**Issue by NEVEROYATNII** [RMerl/asuswrt-merlin#1203]
Was trying to add a MAC addres to a Wireless MAC Filter and after clicking the 'add' button console shows this:
![11](https://cloud.githubusercontent.com/assets/2984018/22106051/ff9cf324-de57-11e6-852a-b572c7380499.png)
Select box is not working too:
![11](https://cloud.githubusercontent.com/assets/2984018/22106172/7788bf76-de58-11e6-8650-9b59fb73960f.png)
Chrome release: 55.0.2883.87 m

**Comment by RMerl** [comment]
Did you have any connected wireless client at that time?  The dropdown only contains wifi clients.

**Comment by NEVEROYATNII** [comment]
Yea, 1 wireless client. And after i added my device there via Opera it still show nothing in Chrome.
Also, the "client list" on front page isnt working too in chrome.

**Comment by RMerl** [comment]
It's possible it might be fixed with 79d5a2709d0aab000ac2c004315684cb30167422 as I'm currently unable to reproduce the issue even by having a test client that contains a single quote in its name.  Check on the Network Map if that's the case among your clients.

**Comment by NEVEROYATNII** [comment]
yea, seems like it. Thank you
