### ISSUE TITLE
is there a mac learning bcm4709 switch? how to disable it?

### ISSUE THREAD

**Issue by oxygeny** [RMerl/asuswrt-merlin#1205]
I am trying to mirror all traffic from wifi device to a switch port, I used libpcap to capture packets, and then inject to vlan7(vlan 7 ports '4 5t'), but no packets I can capture on the switch port, ifconfig I changed the packet's dst mac address, I can capture the packets。So, I think there is a mac learning on the switch, but I can't find the way to disable it! 

I am using merlin fireware with a mcu bcm4709A.

**Comment by RMerl** [comment]
Please use the support forums at SNBForums for support requests.
