### ISSUE TITLE
[380.64_2] Router doesn't try hard enough to connect to remote OpenVPN

### ISSUE THREAD

**Issue by Zulgrib** [RMerl/asuswrt-merlin#1206]
When OpenVPN client fails to connect due to "AUTH_FAILED" error, the client doesn't retry to connect to the remote OpenVPN server, an "AUTH_FAILLED" error may only means the remote server didn't finish initialize and wasn't able to authenticate at that time.

The router should retry to connect some time later instead of abandoning. (--auth-retry nointeract)

(This is confirmed not a password issue, turning off and on OpenVPN client on the router is enough to get it connected again)

**Comment by RMerl** [comment]
Constantly retrying on a failure is generally a bad idea, and can lead to unintended denial of services, as the most likely case where this would be triggered is when there's really an authentication issue.

If for your specific usage scenario you still need it, you can add it to the custom section.
