### ISSUE TITLE
802.1q VLAN (Virtual LAN) trunking, tagging, and routing support

### ISSUE THREAD

**Issue by Hedda** [RMerl/asuswrt-merlin#1211]
Please consider adding 802.1q VLAN (Virtual LAN) trunking, tagging, and routing support to Asuswrt-Merlin firmware Web GUI.

http://www.smallnetbuilder.com/lanwan/lanwan-howto/30071-vlan-how-to-segmenting-a-small-lan

Personally I would like to use VLANs on the wired LAN (and not wireless) for some local lab servers I have at home.
http://www.mattiasholm.com/security/configuring-vlan-on-asus-rt-ac66u-with-asuswrt-merlin-firmware-380-59/
https://www.snbforums.com/threads/vlans-on-merlin-mini-howto.20529/
https://www.snbforums.com/threads/asus-merlin-firmware-and-vlans.27361/
https://www.snbforums.com/threads/asuswrt-vlan-trunking.24410/

Apparently VLAN trunks is possible via shell on Asuswrt (and Asuswrt-Merlin) but it is not available in the Web GUI as of yet.

http://www.dd-wrt.com/wiki/index.php/VLAN_Support

OpenWrt, DD-WRT, and Tomato all offer 802.1q VLAN trunk support on Broadcom based hardware, only Asuswrt missing the GUI.

**Comment by RMerl** [comment]
This would be problematic to implement without conflicting with Asus's own VLAN related code.  This will have to be implemented upstream by them.
