### ISSUE TITLE
AIProtection DNS Filtering issue with NetFlix on Roku

### ISSUE THREAD

**Issue by cheapbyte** [RMerl/asuswrt-merlin#1213]
There is a strange problem when using AiProtection DNS Filtering with Netflix, it doesn't seem to matter what DNS provider I use, NetFlix on Roku times out constantly, everything else like Hulu works fine.  Has anyone else experienced this or can test it to see if it happens to you.

I have a Roku3 and the new Roku 4, both have the same issue with NetFlix and DNS filtering enabled.  I will try to get a wireshark capture to see what's going on. And no, I didn't have a DNS that was blocking Netflix, the same OpenDNS I used as my main router DNS.

**Comment by RMerl** [comment]
Those devices often include measures to prevent the use of third party nameservers, to prevent bypassing region locks.  This isn't an issue with DNSFilter but a limitation imposed by these devices.
