### ISSUE TITLE
Update tor to 0.2.9.9

### ISSUE THREAD

**Issue by feranick** [RMerl/asuswrt-merlin#1217]
Important bugfixes for DDoS attacks, in particular:

Major bugfixes (security):
Downgrade the "-ftrapv" option from "always on" to "only on when --enable-expensive-hardening is provided." This hardening option, like others, can turn survivable bugs into crashes -- and having it on by default made a (relatively harmless) integer overflow bug into a denial-of-service bug. Fixes bug 21278 (TROVE-2017-001); bugfix on 0.2.9.1-alpha.

Major bugfixes (client, onion service):
Fix a client-side onion service reachability bug, where multiple socks requests to an onion service (or a single slow request) could cause us to mistakenly mark some of the service's introduction points as failed, and we cache that failure so eventually we run out and can't reach the service. Also resolves a mysterious "Remote server sent bogus reason code 65021" log warning. The bug was introduced in ticket 17218, where we tried to remember the circuit end reason as a uint16_t, which mangled negative values. Partially fixes bug 21056 and fixes bug 20307; bugfix on 0.2.8.1-alpha.

Minor features (geoip):
Update geoip and geoip6 to the January 4 2017 Maxmind GeoLite2 Country database.

Minor bugfixes (portability):
Avoid crashing when Tor is built using headers that contain CLOCK_MONOTONIC_COARSE, but then tries to run on an older kernel without CLOCK_MONOTONIC_COARSE. Fixes bug 21035; bugfix on 0.2.9.1-alpha.
Fix Libevent detection on platforms without Libevent 1 headers installed. Fixes bug 21051; bugfix on 0.2.9.1-alpha.

**Comment by RMerl** [comment]
Closed with 43ea97d3c7cda604eb31856b5101a992085084db .
