### ISSUE TITLE
Broken manage page on Chrome "Alpha(mean stable version)" 56+

### ISSUE THREAD

**Issue by iMocW** [RMerl/asuswrt-merlin#1226]
See the snapshot below:
![snapshot1](https://cloud.githubusercontent.com/assets/20218140/22452438/d26a933a-e7b1-11e6-9c0e-1e3f20f26570.png)

**Comment by RMerl** [comment]
Already fixed a couple of days ago through c59da2be54f3f9ef0d0ff7ae53b0e002db33e07f .
