### ISSUE TITLE
Automatic QoS Kills iCloud Drive 

### ISSUE THREAD

**Issue by computersteve** [RMerl/asuswrt-merlin#1227]
Hi so idk the technical details but on my Ac5300 if I enable automatic QoS my Macs crawl while trying to sync with iCloud. Im talking about even a small txt document that could be a few kilobytes take minutes to sync..  I verified that something is wrong cause this happens on the latest beta, and the latest stable release I reset the router to defaults before trying. I hope you can fix this cause I love that feature of the firmware I just can't use it that way =(

**Comment by RMerl** [comment]
Adaptive QoS is closed source, and outside of my control.
