### ISSUE TITLE
Policy based routing (manual method) for specific ports

### ISSUE THREAD

**Issue by agp89** [RMerl/asuswrt-merlin#1229]
On the Wiki-Page [Policy based routing](https://github.com/RMerl/asuswrt-merlin/wiki/Policy-based-routing) it says that you could create policys for ports. On the Wiki-Page [Policy based routing (manual method)](https://github.com/RMerl/asuswrt-merlin/wiki/Policy-based-routing-(manual-method)) i cant find any example for this though.

How would i configure a policy like: All traffic from specific source ip over specific ports go through VPN?

**Comment by RMerl** [comment]
Please use the forums at SNBForums for support requests.
