### ISSUE TITLE
AICloud client list

### ISSUE THREAD

**Issue by Xitro01** [RMerl/asuswrt-merlin#1230]
Not really an issue, more a question/feature request. Did not know where I could post this elsewhere.

I see alot of very old computers in my AICloud list, also after reinstalling the app they are still there.
Is there a way to purge this list?

I saw in the source code that it uses aicloud.db, but I can't find this file anywhere in my router. Also I saw that it probably uses sqlite3, but I can't seem to run this on the router.

If you guys have any ideas about this, please let me know.

**Comment by RMerl** [comment]
I don't touch the AiCloud code, sorry.  Part closed-source, part-obfuscated.
