### ISSUE TITLE
MiniDLNA: Scan pre-processed drives faster

### ISSUE THREAD

**Issue by the0ne** [RMerl/asuswrt-merlin#1231]
I just stumbled upon this MiniDLNA fork:
https://code.google.com/archive/p/minidlna-fastscan/
In case a user often disconnects/reconnects usb drives this might be useful.
Just wanted to make sure you heard of it - feel free to close this issue.

**Comment by RMerl** [comment]
Google Code was shut down some time ago, so there's no code accessible anymore.

**Comment by stevek123** [comment]
I think this is the code: https://code.google.com/archive/p/minidlna-fastscan/source/default/source

**Comment by RMerl** [comment]
This old code is based on minidlna 1.0.1 - this is nearly four years old, we're on 1.1.6 now.
