### ISSUE TITLE
Is it possible to implement some socks 5 proxy?

### ISSUE THREAD

**Issue by mittar** [RMerl/asuswrt-merlin#1234]
Hi,
I am looking how to set proxy (sockd) to use it for tun12 (openvpn) but it does not work for me. It uses all DNS and main IP address (openvpn DNS set as Exclusive). In the sockd.conf I have:
internal: 192.168.1.1 port = 1080
external: tun12
I suppose that it is due lack of knowledge so I want to ask if you plan implement some Socks 5 proxy directly to the Settings (with the option to select Output - WAN,VPN)?
Thanks

**Comment by RMerl** [comment]
There are no plans to implement socks proxy support.
