### ISSUE TITLE
WOL script in Wiki needs an update

### ISSUE THREAD

**Issue by joaonl** [RMerl/asuswrt-merlin#1236]
Hi there,

Since the last release of asuswrt-merlin (380.65) the ether-wake is located in "/usr/sbin/ether-wake" instead of "/usr/bin/ether-wake" which caused the script to stop working on my end and fixed with path change.

**At least, this is the case on my RT-N66U and not sure on other models.**

Cheers,

**Comment by RMerl** [comment]
Wiki is open for editing by anyone with a Github account, feel free to update it.

**Comment by fun4stuff** [comment]
Script doesn't seem to be working anymore.
