### ISSUE TITLE
ASUS RT-AC87U in Wireless router mode, connected WAN <--> LAN to 4G-AC55U to use as internet gateway.

### ISSUE THREAD

**Issue by sg-zax** [RMerl/asuswrt-merlin#1237]
Good day,

The issue is setting up a monitored and controlled environment that asuswrt-merlin supports, but I cannot get it to function correctly. 
The RT-AC87U must acts as the default gateway for all devices to connect to wireless and wired on network 10.0.0.0.
Therefor the 4G-AC55U must act as the internet gateway, and also use its WIFI as an extender to the 10.0.0.0 network.

How do I get this setup correctly?

It was easy setting up the 4G-AC55U as the default gateway and the RT-AC87U as an access point, but this defeats the point of trying to monitor the network and/or setup QoS traffic because the 4G-AC55U does not have asuswrt-merlin firmware as of yet.

Please help. I know there must be a solution.

Thanks in advance.

Regards,
ZaX

**Comment by RMerl** [comment]
Please use the support forums at SNBForums for support requests.
