### ISSUE TITLE
Put Tor NAT rules at top of nat PREROUTING chain

### ISSUE THREAD

**Issue by blackfuel** [RMerl/asuswrt-merlin#1240]
This patch puts the Tor NAT rules at the top of the nat PREROUTING chain, above the VSERVER rule.  Modifies two functions nat_settings() and nat_settings2().  I think this is good to prevent the router from leaking your true IP address, just in case something unexpected happens.

[380.65-tor-nat-top.patch.txt](https://github.com/RMerl/asuswrt-merlin/files/759562/380.65-tor-nat-top.patch.txt)

**Comment by RMerl** [comment]
Closing this, as the pull request has been merged (looks like issues don't auto-close like they do with commits).
