### ISSUE TITLE
Disabled OpenVPN Client re-enables on restart

### ISSUE THREAD

**Issue by goldcd** [RMerl/asuswrt-merlin#1242]
I setup an OpenVPN Client on my with RT-AC66U 380.65
I disable it ("Service state" set to off)
I restart my router and the service re-enables itself.

**Comment by RMerl** [comment]
Disable "Start with WAN".

Also, please use the support forums at SNBForums for support requests.

**Comment by goldcd** [comment]
Thanks.
Will do in future
