### ISSUE TITLE
AC68U - 380.65 ssh hangs

### ISSUE THREAD

**Issue by agurenko** [RMerl/asuswrt-merlin#1245]
After upgrade to 380.65 ssh server hangs and connection to port 22 times out. Turning ssh off/on helps for some time, but it happens now all the time. Interestingly enough reboot does not help.

 I'm using ssh-key authentication, password auth disabled, LAN only.

**Comment by agurenko** [comment]
Hm...now I cannot restore functionality at all...I've switched it off completely yesterday, let see if it will work today, but that's not a good sign. Never happened before.

**Comment by RMerl** [comment]
Please use the support forums at SNBForums for support requests.
