### ISSUE TITLE
Policy based routing (manual method) doesn't work

### ISSUE THREAD

**Issue by yecundha** [RMerl/asuswrt-merlin#1248]
Hi

Did someone successfully applied the method documented here: https://github.com/RMerl/asuswrt-merlin/wiki/Policy-based-routing-(manual-method)?

I tried the manual one and not the asuswrt Merling GUI policy based routing because I want to keep access to a website hosted on the VPN user device from the ISP gateway, using some port forwarding.
But for the moment I'm stuck on routing all traffic through the ISP gateway except this device.

Here is the exact copy of my "openvpn-event" script:

`#!/bin/sh

sleep 10

for i in /proc/sys/net/ipv4/conf/*/rp_filter ; do
	echo 0 > $i
done

ip route flush table 100
ip route del default table 100
ip rule del fwmark 1 table 100
ip route flush cache
iptables -t mangle -F PREROUTING

ip route show table main | grep -Ev ^default | grep -Ev tun11 | while read ROUTE ; do
	ip route add table 100 $ROUTE
done
ip route add default table 100 via $(nvram get wan_gateway)
ip rule add fwmark 1 table 100
ip route flush cache

iptables -t mangle -A PREROUTING -i br0 -j MARK --set-mark 1
iptables -t mangle -A PREROUTING -i br0 -m iprange --src-range 192.168.77.2 -j MARK --set-mark 0
`

So 192.168.77.2 is the static private IP of the device which should use the VPN.

The problem is every devices are using the VPN.
I'm using an RT-AC3200 with the 380.65 firmware. It was the same behaviour with 380.64-2 firmware then I decided to upgrade it.
I tried setting the sleep time to 2 sec then 10 sec. Nothing changed.
My Open VPN client GUI panel is configured as above:
  Select client instance: Client1
  Service state: ON
  Start with WAN: Yes
  Create NAT on tunnel: Yes
  Redirect Internet traffic: No

The VPN provider is IP Vanish.

Any clue?
Thanks for your help, I'm getting mad....

**Comment by RMerl** [comment]
Please use the support forums at SNBForums for support requests.
