### ISSUE TITLE
bug - wireless scheduler not working after using the wireless button

### ISSUE THREAD

**Issue by dilighiani** [RMerl/asuswrt-merlin#1252]
I have set a wireless scheduler to stop the WiFi signal every night after 1:00 AM. Sometimes I need to have the WiFi signal open after 1:00 AM and I force to enable the WiFi signal from the front button of the AC87U. But after that, for the following days, the scheduler is disabled until the momment when I logon to the web Interface to re-enable the WiFi schedule.
I consider this an Asus WRT bug but I don't know how to open bug requests for Asus WRT.

**Comment by hggomes** [comment]
You just simply need to send an email to: networking_support@asus.com

**Comment by dilighiani** [comment]
Thank you for the tip hggomes. I have sent an email to them.

**Comment by hggomes** [comment]
You are welcome, thank you also for reporting it.
