### ISSUE TITLE
PPTP error

### ISSUE THREAD

**Issue by zuozhehao** [RMerl/asuswrt-merlin#1254]
Feb 22 09:02:39 pptpd[29219]: CTRL: Ignored a SET LINK INFO packet with real ACCMs!
Feb 22 09:02:51 pptpd[29230]: CTRL: Ignored a SET LINK INFO packet with real ACCMs!
Feb 22 09:03:03 pptpd[29243]: CTRL: Ignored a SET LINK INFO packet with real ACCMs!
Feb 22 09:03:03 pptp[29244]: Cannot determine ethernet address for proxy ARP
Feb 22 11:05:34 pptpd[18386]: CTRL: Ignored a SET LINK INFO packet with real ACCMs!
Feb 22 11:05:50 pptpd[18397]: CTRL: Ignored a SET LINK INFO packet with real ACCMs!
Feb 22 11:05:50 pptp[18398]: Cannot determine ethernet address for proxy ARP
Feb 22 16:07:05 pptp[18398]: MPPE disabled
Feb 22 16:07:06 pptpd[18397]: CTRL: EOF or bad error reading ctrl packet length.
Feb 22 16:07:06 pptpd[18397]: CTRL: couldn't read packet header (exit)
Feb 22 16:07:06 pptpd[18397]: CTRL: CTRL read failed
Feb 22 17:01:49 pptpd[15943]: CTRL: EOF or bad error reading ctrl packet length.
Feb 22 17:01:49 pptpd[15943]: CTRL: couldn't read packet header (exit)
Feb 22 17:01:49 pptpd[15943]: CTRL: CTRL read failed

**Comment by RMerl** [comment]
Please use the support forums at SNBForums for support requests.
