### ISSUE TITLE
Issue/Feature - Allow DDNS use real internet IP instead of WAN IP

### ISSUE THREAD

**Issue by rkkoszewski** [RMerl/asuswrt-merlin#1260]
Is there any way to allow the DDNS service to use the real internet IP instead of the WAN IP? 

In my case I have my Asus router connected to another router that is shared with many people. Ive set my Asus to use a static IP as if it woild be juat an other user from the shared router. My aim with this is to have my own private network where I can have all my Samba and Dlna services running, without having stranger looking teough my stuff. 

The only problem is that I cannot use the DDNS feature, which seems required for the OpenVPN service and others to run properly. My router has full access to the internet as it is on a DMZ. The only issue is that the DDNS service seems to register the internal WAN IP instead of the real Internet IP. Is there any way to make this work? Or if not could this be considered as a feature request?

Greetings and thanks.

**Comment by RMerl** [comment]
This would require architecture changes to how Asus implemented it, so it's unlikely to happen on my end, and would need to be done upstream by Asus.

My advice as an alternative is to use the custom DDNS script, which will give you more flexibility.
