### ISSUE TITLE
QOS Port Utilization

### ISSUE THREAD

**Issue by xhaloz** [RMerl/asuswrt-merlin#1262]
Hello I am using an ASUS RT-AC66U.  I noticed in Tomato I could view complete tables for QOS.  The IP, the Port, The classification.  Why can't I do that with Merlin?  I don't know if the ports I am QOS-ing are actually working because there are no charts .

Thanks in advance

**Comment by RMerl** [comment]
Different QoS implementation.  And since Traditional QoS is currently broken on numerous models, this is something I consider to be legacy code.  It's unlikely I'll devote much time working with that old code, at least until Asus fixes it.
