### ISSUE TITLE
pptp use only one core

### ISSUE THREAD

**Issue by CHazz** [RMerl/asuswrt-merlin#1263]
Hello, connection via PPTP (client) only uses a single core .. when heavy traffic is a core 1 used at 100% and core 2 is 1% .. throughput is thus reduced to the theoretical half .. (model RT-AC68U) thank you for your help 

http://imgur.com/a/m5Oh0

**Comment by RMerl** [comment]
Nothing I can do about it, it's how the pptp client is implemented, has nothing to do with the firmware itself.

**Comment by CHazz** [comment]
ok .. I got try to ASUS support then?

**Comment by RMerl** [comment]
It's a technical limitation of the pptp code, Asus cannot change that.
