### ISSUE TITLE
NAT Loopback is not work

### ISSUE THREAD

**Issue by cutedogspark** [RMerl/asuswrt-merlin#1264]
Dear RMerl

 I updated the firmware 380.65 version on my ASUS RT-68U, when I  Factory default Route then the NAT Loopback is not work, pls help me

## Port Forwarding List
PC1     22  port  <------->  WAN  80 port
PC1     80  port  <------->  WAN  22 port

PS:
    RT-68U web interface port change to 8888 
    RT-68U disable ssh daemon
    RT-68U  Set DDNS success

## Test
LAN  ->   DDNS:8888    success
LAN  ->   DDNS:80         fail
LAN  ->   DDNS:22         fail

4G(Extranet)    ->   DDNS:8888   success
4G(Extranet)    ->   DDNS:80       success
4G(Extranet)    ->   DDNS:22        success

## how can i check NAT Loopback table is  work ?

**Comment by bossarts** [comment]
Hello

Same issue here, see config:
ASUS RT-68U
380.65_2 -> Install with factory reset
380.66 beta -> Update
NAT Loopback: Merlin/Ausus -> both are not working
OpenVpn Server installed
192.168.223.1 Router IP
DHCP 192.168.223.200-230
SUBNET 255.255.255.0
STATIC DHCP for Webcams
WEBCAM1: 192.168.223.30
WEBCAM2: 192.168.223.32

Port Forwarding List
WEBCAM1	80 port <--> WAN 33860 port
WEBCAM2	80 port <--> WAN 33862 port

Testing:
LAN	-> myddns.ch:33860 fail
LAN -> myddns.ch:33862 fail
4G(WAN)	-> myddns.ch:33860 success
4G(WAN) -> myddns.ch:33862 success
LAN -> WANIP:33860 sucess
LAN -> WANIP:33862 sucess
Conclusion: NAT loopback works when WAN IP is used but not with DDNS myddns.ch

DNS Reserch on Win10 CMD:
C:\> nslookup myddns.ch
Server: Routername.myddns.ch
Address: 192.168.223.1 -> This is the Router IP which seems OK
***superboss.me wurde von Routername.myddns.ch nicht gefunden: Non-existent domain.

I'm lost. Any ideas?

Regards

**Comment by RMerl** [comment]
Your problem is your DDNS, not the NAT loopback.  Look at the error message on your nslookup result.

NAT loopback is working fine in the firmware, lots of people are using it without any issue.

**Comment by bossarts** [comment]
Changed "RT-AC68U's Domain Name"  to someting else than myddns.ch and now it works! Thanx for the hint!
