### ISSUE TITLE
ASUS RT-AC68U 380.65-X7.4 cannot update ddns on noip.com

### ISSUE THREAD

**Issue by WalkerWalker** [RMerl/asuswrt-merlin#1269]
I'm in China. I already set up ss client and ss server on ec2 and the vpn works perfectly.  (not sure the router itself will go through it or not. )

At the management page, WAN - DDNS set the noip free domain，account email and password. Double checked its all correct.  But just cannot update successfully.

In the log in see the following message.  I checked with web broswer,  members.dyndns.org page simply shows 404

```
ddns update: connected to members.dyndns.org (204.13.248.111) on port 80.
ddns update: error recv()ing reply: Connection reset by peer
ddns update: strange server response, are you connecting to the right server?
```

I checked log another time today, the address changed but still cannot connect.

```
ddns update: connected to dynupdate.no-ip.com (8.23.224.120) on port 80.
ddns update: error recv()ing reply: Connection reset by peer
ddns update: strange server response, are you connecting to the right server?
```

I googled quite a lot and seems like some [posts](http://www.dyncommunity.com/questions/30899/error-updating-ddns.html) says it's because the website is blocked by my ISP, but no solution provided. Another . Meanwhile some [other posts](http://www.dyncommunity.com/questions/9720/membersdyndnsorg-down.html) says 404 is normal. Have been searching it a lot these days but just no luck.  Any way to make it work? or should I deploy some manual update script on the router to let it update?  

Hope to get help!!! Thanks

**Comment by RMerl** [comment]
Since you are running a third party fork, you might need to contact the author of that fork.  No-IP is working properly for me using my firmware.
