### ISSUE TITLE
Dual WAN failback bouncing with Arris SB6183

### ISSUE THREAD

**Issue by rgiesman2** [RMerl/asuswrt-merlin#1271]
With the Arris SB6183 cable modem, the WAN DHCP client (RT-AC68U) is issued a public IP when a broadband connection is available.  However, when the modem is in failed state (Broadband cable pulled), the router WAN interface is issued an RFC-1918 address.  I have called Arris tech support and there is no way to disable the DHCP server nor is there a way to change the management IP address.  This is unfortunate because wanduck detects this private address as a valid WAN and goes into a state of bouncing back and forth between WAN connections when this happens.  My only solution is to disable failback and possibly somehow detect this condition and deal with in the wan-start user script in /jffs/scripts.

**Comment by RMerl** [comment]
I don't touch the Dual WAN code.  I recommend reproducing the issue with Asus's stock firmware, and then contact Asus about it.
