### ISSUE TITLE
Latest ASUS RT-N66U Firmware version 3.0.0.4.380.7266

### ISSUE THREAD

**Issue by batch22** [RMerl/asuswrt-merlin#1274]
I've read the Merlin story and am happy to hear these initiatives are existing.
Also I've read that each Merlin firmware update will be based on the latest released Asus firmware.
Logically.

Since this is the case(?), are you aware of the bug in the latest firmware ASUS RT-N66U Firmware version 3.0.0.4.380.7266 that is causing the WAN to drop after a couple of hours. (I think maybe a buffer overrun?)

I'm really curious If you have any thoughts or knowledge about that happening. Also because If I make the switch to Merlin that I'm not ending up with the same problem.

Thanks alot!

**Comment by RMerl** [comment]
Please use the support forums at SNBForums for support requests.
