### ISSUE TITLE
dnsmasq.conf.add: Manual Entries Not Honored When Using DNSCrypt Proxy

### ISSUE THREAD

**Issue by jlambright** [RMerl/asuswrt-merlin#1276]
Simply put, I'm trying to combine the outcomes of both the [Enforce Safesearch](https://github.com/RMerl/asuswrt-merlin/wiki/Enforce-Safesearch) and the [Secure DNS queries using DNSCrypt](https://github.com/RMerl/asuswrt-merlin/wiki/Secure-DNS-queries-using-DNSCrypt) how-to articles. Unfortunately, they don't seem to be compatible.

**Comment by RMerl** [comment]
This is a support issue, not a bug in the firmware.  Please use the support forums.
