### ISSUE TITLE
In Dual-WAN mode, can not access internet when firewall enanbled.

### ISSUE THREAD

**Issue by leonanu** [RMerl/asuswrt-merlin#1277]
Device: Netgear R7000
Firmware: Asuswrt-Merlin & Xwrt-Vortex
Version: 380.65

In Dual-WAN mode, if firewall was enabled. Clients can not access to internet normally, even if disable the second WAN connection. There were no rules in firewall settings.

Disable Dual-WAN function or disable firewall, the clients could access internet normally.

**Comment by RMerl** [comment]
I do not support the R7000.
