### ISSUE TITLE
Spurious Ports Forwarding entries appear when adding a new port to forward

### ISSUE THREAD

**Issue by arbshimmin** [RMerl/asuswrt-merlin#1281]
RT-N66U with Firmware:380.65_2

When I add a new port to forward I get two spurious rows in the port forwarding table which contain text of some HTML styling commands. Screenshot attached.

These survive reloading the page and I have to use the - button to remove them.

There also looks to be an extra blank column in some parts of the table.

![portforwardbug](https://cloud.githubusercontent.com/assets/26351385/23826851/438aa8e2-069e-11e7-96fe-a9d6c63cde0d.png)

**Comment by RMerl** [comment]
Corrupted rulelist, reset it:

```
nvram unset vts_rulelist
nvram commit
```

I have seen two reports so far, yet I can't reproduce it here.  I suspect they might come from moving back and forth between different firmware version (Asus recently added a new source IP field to that list).
