### ISSUE TITLE
How to increase max static route limit on RT-AC5300

### ISSUE THREAD

**Issue by junwchina** [RMerl/asuswrt-merlin#1282]
Hello,

I want to add almost 7k static routes on my router based on chnroute list. The issue is the router did not response any more if there were more than 500 static routes. On the webui, It seems the max static routes is 64. Is it possible to increase this limit?

**Comment by RMerl** [comment]
That probably wouldn't even fit in nvram.  Your usage scenario needs a business-class device rather than a home gateway.
