### ISSUE TITLE
suggest add "Run after mounting" and "Run before unmounting" options webUI interface?

### ISSUE THREAD

**Issue by tsingui** [RMerl/asuswrt-merlin#1283]
1.Suggest add webUI "**Run after mounting**" and "**Run before unmounting**" options control as same as Tomato webUI interface.
Want to run script directory (/mnt/sda1/example.sh),To enable third-party extensions.
a) Don't enable jffs partition,Because a large number of syslog(log) write in the partition.
b) OR a large number of syslog(log) moved write to temp(/tmp) directory.

2.Asus router as second router (restart) WAN interface sometime Can't get **IP address** and **hostname**  can't display on the first the routing.

Look forward to your reply,Thanks developers team!

**Comment by RMerl** [comment]
I don't want to add a web interface to manage the custom scripts/config files, because with over 40 different files that can be customized, this would be a nightmare of usability.
