### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Octolus** [RMerl/asuswrt-merlin#1285]
Hello.

Is there any way to automatically change the mac wan address, at certain time for example 03:00 AM? Then restart WAN?

I'm looking to do this, to obtain a Dynamic IP. The only way to change my IP, would be changing WAN MAC Address.

If not, then this is a suggestion. I noticed that I can change my IP many times as i want, as long as I can change the mac address. What I did was copying a random mac from the network map (device list) then using it as WAN MAC. Then boom -- brand new IP.

Maybe there are a way to do some custom user scripts for this? I'd even pay for such..

**Comment by RMerl** [comment]
Please use the support forums at SNBForums for support requests.
