### ISSUE TITLE
Hostname weird resolution since switch to merlin firmware

### ISSUE THREAD

**Issue by david-soyez** [RMerl/asuswrt-merlin#1287]
Hi,

I have updated my RT-AC1900P router to the merlin firmaware and before updating the hostname resolution was working fine on the official firmware, now for most of the android devices, instead of the correct hostname, it says "Google(Android)" which makes it too difficult to identify the owner of each device. Before it said the firstname of the person(ex: Robert x3-phone)
But the worse is that then it says Apple Iphone (see screenshot)
Note that I have reset the router and it did not change anything.

<img width="534" alt="screen shot 2017-03-15 at 12 24 23 pm" src="https://cloud.githubusercontent.com/assets/1408966/23959038/5e249f80-097a-11e7-9d09-a3f21306e9db.png">

Thanks for your help.

**Comment by unsynaps** [comment]
You do know you can change the names right?

**Comment by david-soyez** [comment]
I dont want to change them manually, it supposed to take them from the hostnames automatically.

**Comment by RMerl** [comment]
That field is a description, unrelated to hostname lookups, and is filled up by the closed source Trend Micro engine.
