### ISSUE TITLE
RT68U - VPN for GuestWireless dhcp users only

### ISSUE THREAD

**Issue by TRingo1** [RMerl/asuswrt-merlin#1288]
Is there a way to always route Guest Wifi users through the VPN?  I tried to have with both internal DHCP servers and external, but not successful.  Ideally i would like a different subnet for my wifi guests users and have them all route through the active vpn. by default the guestwifi users are assigned address within the same dhcp pool, and when i select the checkbox for no intranet access, I'm not sure they only have access to internet, and not local address range.

**Comment by RMerl** [comment]
Please use the support forums at SNBForums for support requests.
