### ISSUE TITLE
Is there a way to enable ssh tcp forwarding via command line? 

### ISSUE THREAD

**Issue by WalkerWalker** [RMerl/asuswrt-merlin#1293]
I cannot visit the admin page now because ISP blocked my 8080 port.  I was trying ssh port forwarding but I get the message
```
channel 3: open failed: administratively prohibited:
```

Is it because ssh tcp forwarding is disable?  Is there a way to turned it on via command line ? I can ssh in

**Comment by RMerl** [comment]
Please use the support forums at SNBForums for support requests.
