### ISSUE TITLE
Is there a way to change WAN admin page port via command line?

### ISSUE THREAD

**Issue by WalkerWalker** [RMerl/asuswrt-merlin#1294]
I cannot visit the admin page now because ISP blocked my 8080 port.  Is there a way to change WAN admin page port via command line?

**Comment by gNomeXOS** [comment]
nvram show | grep 8080
size: 61357 bytes (69715 left)
misc_httpport_x=8080

**Comment by RMerl** [comment]
Please use the support forums at SNBForums for support requests.
