### ISSUE TITLE
RT-AC88U 380.65_2 OpenVPN Client Problem

### ISSUE THREAD

**Issue by uncensoredtr** [RMerl/asuswrt-merlin#1297]
OpenVPN Client connects, routes looking OK but cannot ping to vpn given ip(10.8.0.x) or vpn gateway ip (10.8.0.1). No connection to outside ip s and websites.
TUN/TAP write bytes is 0 no matter what.
Same ovpn config connects on 380.65 but has poor performance.
Same ovpn config has been working great on 380.64_2

client
dev tun
proto udp
remote xxx.xxx.xxx.xxx 443
resolv-retry infinite
nobind
user nobody
group nobody
persist-key
persist-tun
remote-cert-tls server
cipher AES-128-CBC
auth SHA256
key-direction 1
comp-lzo no
verb 3

I am using same ovpn config with different certificates on 2 RT-AC88U with Merlin and 3 DSL-AC68U with original firmware. Not counting android, iphone and pc clients.

**Comment by RMerl** [comment]
Please use the support forums at SNBForums for support requests.
