### ISSUE TITLE
Enhancement: support for hostless modems

### ISSUE THREAD

**Issue by crazyquark** [RMerl/asuswrt-merlin#1298]
Hello,

(Love your work)

How hard would it be to add support for hostless modems in the firmware, something like what this OpenWRT fork is doing:
[ROOter](http://ofmodemsandmen.com/hostless.html)

**Comment by RMerl** [comment]
I have no plan to implement any additional USB modem, as I have no way of testing it, and that would require devoting development time that I lack, and would be better spent elsewhere in the project, sorry.
