### ISSUE TITLE
PS4 via AC3200's LAN not working with 380.65_2

### ISSUE THREAD

**Issue by guidomedina** [RMerl/asuswrt-merlin#1301]
I had to fallback to 380.65 because the PS4 wouldn't connect to the Internet via LAN.

I have AiProtection on for:
- Malicious websites.
- Parental control for few devices including the PS4.

Just reporting it, I didn't actually went to the logs to check but once I fallback to 380.65 the problem disappeared.

Maybe it is a new firewall rule for the LAN? the WiFi was working OK though.
The PS4 was getting everything fine via DHCP but wouldn't get any answer from the DNS.

**Comment by RMerl** [comment]
There are various issues with the RT-AC3200 and 380.65_2.  As a temporary workaround, run the following commands over SSH:

```
nvram set stop_gmac3=1
nvram commit
reboot
```

**Comment by guidomedina** [comment]
Thanks, closing as the idea was to report but I see it is a well known issue, nice job with the Asus firmware btw.
