### ISSUE TITLE
380.65_4 mispacked or misversioned for RT-AC66U?

### ISSUE THREAD

**Issue by t-nelson** [RMerl/asuswrt-merlin#1306]
I've installed 380.65_4 on my RT-AC66U three times (redownloaded once, sha256 always checks out), but the version still displays 380.65_2.  There are no errors reported during the installation.  The update checker is still nagging about an available update.

I tried running "strings" against the TRX, but the version must be encoded and formatted at run time because I could not find any instance of "380.65".  I didn't notice any mention of the FW version in the system log either.

Updating from 380.65_2 to 380.65_4 worked, as usual, with my RT-N66U.

How should I proceed?

**Comment by RMerl** [comment]
No one else among the thousand of people who downloaded it mentioned having any issue, so double check that you downloaded the correct model.
