### ISSUE TITLE
no response from asuswrt.lostrealm.ca, problem was exit point with VPN, suggest Closing this issue

### ISSUE THREAD

**Issue by jontis** [RMerl/asuswrt-merlin#1307]

**Comment by t-nelson** [comment]
Works here.  Are you using a VPN by chance?  I finally got around to setting one up this week and noticed asuswrt.lostrealm.ca was not accessible when it is enabled.

**Comment by jontis** [comment]
I do use a vpn. I'll turn it off and check again, didn't think that could affect it.

**Comment by t-nelson** [comment]
I'm guessing it's not the VPN so much as the VPN's IP being on some abuse
list.

**Comment by jontis** [comment]
you we're absolutely right. When I connect from another IP, I get responses. 
Thanks for helping.
