### ISSUE TITLE
Console errors since 380.65_4

### ISSUE THREAD

**Issue by w84no1** [RMerl/asuswrt-merlin#1312]
Uncaught TypeError: Cannot read property 'getElementsByTagName' of null
    at refreshStatus (state.js:2879)
    at XMLHttpRequest.xmlHttp.onreadystatechange (makeRequest.js:19)
refreshStatus @ state.js:2879
xmlHttp.onreadystatechange @ makeRequest.js:19
state.js:2879 Uncaught TypeError: Cannot read property 'getElementsByTagName' of null
    at refreshStatus (state.js:2879)
    at XMLHttpRequest.xmlHttp.onreadystatechange (makeRequest.js:19)
refreshStatus @ state.js:2879
xmlHttp.onreadystatechange @ makeRequest.js:19

**Comment by imavroukakis** [comment]
I assuming you mean browser console. Any specific page? I can't seem to replicate it with mine.

On Chrome 57.0.2987.133

**Comment by w84no1** [comment]
Yes, I am using the Chrome inspector. I reverted back to a previous version that did work without errors and it still has those errors on every page.  I think it might be my setup (usb modem tethered), so I am going to factory reset it and see if that fixes it.
