### ISSUE TITLE
How to support 32mb flash (eg.MX25L25645GM2I-10G) by cfe?

### ISSUE THREAD

**Issue by ilasx** [RMerl/asuswrt-merlin#1314]
How to support 32mb flash (eg.MX25L25645GM2I-10G) by cfe?
I bought a MX25L25645GM2I-10G flash ,but when i boot from CFE i only got a message said that "Found a ST compatible (Marconix) serial flash with 512 64KB blocks; total size 16MB".

**Comment by RMerl** [comment]
Please use the support forums at SNBForums for support requests.
