### ISSUE TITLE
Clicking on Clients Name in View List with an apostrophe removes all characters to the right

### ISSUE THREAD

**Issue by rsforbes** [RMerl/asuswrt-merlin#1317]
Steps to replicate

1. Go to Network Map
2. Click on View List under Clients
3. Click on a Clients Name so that it is editable
4. Enter the text...  `Mike's iPad`
5. Click on the X in the upper right corner to close
6. Click on View List under Clients
7.  Click on a Clients Name where it is equal to...   `Mike's iPad` ...so that it is editable

Bug: Everything to the right of the apostrophe is remove leaving just...  `Mike`
Expected: The Clients Name is unchanged leaving...  `Mike's iPad`

**Comment by RMerl** [comment]
Already fixed with 79d5a2709d0aab000ac2c004315684cb30167422 .
