### ISSUE TITLE
permission error with gendict.pl file

### ISSUE THREAD

**Issue by azdps** [RMerl/asuswrt-merlin#1318]
I'm getting a permission error with the gendict.pl file during the build process. Changing the file permission to executable solved this problem. I cloned the asuswrt-merlin repository 3 times which resulted in the same permission error during each build process.

**Comment by RMerl** [comment]
Works for everyone else, make sure you use a compatible filesystem.  Asuswrt cannot be build using a Windows filesystem for instance.

**Comment by azdps** [comment]
If you set AUTODICT=n in the asuswrt-merlin/release/src-rt/target.mak  file and gendict.pl will fail to execute because of the permission issue. If you look at the file under linux, you can see it not set as executable which it should be. I doubt most users don't notice this.

I use linux mint to build asuswrt-merlin. I don't use windows at all.
