### ISSUE TITLE
Applying settings does not return focus to page

### ISSUE THREAD

**Issue by mscreations** [RMerl/asuswrt-merlin#1320]
So I upgraded my firmware on my RT-AC3200 to 380.65_4. The router didn't start up properly and I had to reset the settings to default. Now, everytime I make a change that requires applying them, I get the notification that the changes are being applied and once it gets to Complete, the notification never goes away. I have to reload the page completely to go back to the page.

**Comment by unsynaps** [comment]
Have you tried flashing it again?
