### ISSUE TITLE
Dual WAN has status Disconnected after reboot

### ISSUE THREAD

**Issue by alexander-hagen** [RMerl/asuswrt-merlin#1321]
I have connected primary WAN on my AC88U. Secondary WAN is configured as WAN Type "Ethernet LAN" on "LAN Port 3". After reboot, Primary WAN has status "Connected" and secondary WAN has status "Disconnected". Router does not switch to Secondary WAN if Primary WAN fails.

When I go to WAN > Internet Connection and select: "Ethernet LAN" and then click Apply, Secondary WAN changes to status "Standby". Router now does switch to Secondary WAN if Primary WAN fails. After reboot of the router, Secondary WAN has status "Disconnected" again until the settings are re-applied. Same issue in AC68U.

This issue exists in firmware 380.65_4.

**Comment by RMerl** [comment]
I don't touch the Dual WAN code since it's too complex and largely undocumented.  See if you can reproduce it with the stock firmware, and if you do I recommend raising a bug report with Asus so they can look into it.
