### ISSUE TITLE
Cant install this firmware on TM-AC1900

### ISSUE THREAD

**Issue by mystycs** [RMerl/asuswrt-merlin#1324]
Hey there!

I tried installing the RT-AC68U firmware on the TM-AC1900, but it says its not supported.

Is there a possible way to get merlin on the tmobile branded rt-ac68u?

Cant find any info on this. I know the tm-ac1900 is just a rebranded ac68u

**Comment by RMerl** [comment]
Please use the support forums at SNBForums for support requests.
