### ISSUE TITLE
OpenVPN Client Configuration Request & added issue with OpenVPN Server simultaneous use.

### ISSUE THREAD

**Issue by techtoolkit** [RMerl/asuswrt-merlin#1327]
Redirect Internet traffic with "Policy Rules" for routing client traffic through the tunnel "Buy List".

Issue One:  To be able to reverse "Policy Rules "and state all but exempt list, instead of "only in approved a list".  and all others could be controlled by "Block routed clients if tunnel goes down" setting toggle.

Issue Two: Using IP is difficult to administer due to DHCP, using MAC like with DHCP server configuration would not change with DHCP assignments.

Issue Three:  With the above configuration allow for inbound OpenVPN Server Hosting through non-VPN Client service (i have not been able to get both working at the same time)

Thank for the consideration.

**Comment by RMerl** [comment]
1) Use subnets or a WAN rule to split your clients as desired

2) Routing is an IP-based protocol, it cannot deal with MACs, which is an Ethernet-level protocol.  Use static reservations.

3) This will depend on your configuration, please visit the support forums at SNBForums, there's a few discussions on how to achieve this.
