### ISSUE TITLE
Router routinely runs out of NVRAM and disables 2.4GHz on RT-AC3200

### ISSUE THREAD

**Issue by Kampe** [RMerl/asuswrt-merlin#1330]
Quite frequently the router will max out NVRAM and disable the 2.4GHz band.  I have openVPN disabled and not much else going on aside from port forwarding two ports.   This has been happening for many firmware updates now.  Issue probably started in August 2016.

**Comment by azdps** [comment]
Maybe you should provide a backup of your nvram and post it here. Of course masking anything that you don't want anyone to see.

**Comment by RMerl** [comment]
Please use the support forums at SNBForums for support requests.
