### ISSUE TITLE
Client list shows all wireless clients as connected to the wired interface

### ISSUE THREAD

**Issue by dandv** [RMerl/asuswrt-merlin#1333]
I've just flashed 380.65_4 stable onto my AC-68U set up in repeater mode. It connects to my phone's hotspot, then the devices in my home connect to the 5GHz AP, plus a Philips Hue bridge connected via Ethernet.

When I look at the client list however, I see all clients as wired, and the Philips Hue bridge is missing.

"Htc" is the phone (Google Pixel). "Lappy" is connected to the phone's hotspot. So maybe the firmware thinks that anything connected to the parent AP is wired?

![image](https://cloud.githubusercontent.com/assets/33569/25307855/b581ef02-275d-11e7-9d3f-d80cc13a5138.png)

**Comment by RMerl** [comment]
This will happen following a reboot, usually needs a while for the networkmap to properly update itself.
