### ISSUE TITLE
Use the “Traffic Analyzer - Statistic” for a long time will fill up the /jffs space.

### ISSUE THREAD

**Issue by tldzyx** [RMerl/asuswrt-merlin#1335]
“Traffic Analyzer” will create the file "/jffs/traffic.db" and "/jffs/traffic.db-journal", it will grow up until the jffs has no space to store it.

So, there need a UI to delete a part of history in file "traffic.db" by auto or manual, it's a sqlite database file.

**Comment by RMerl** [comment]
Traffic Analyzer is closed source, so I cannot manipulate it.  Beside, Asus already did implement some form of database management.  I forgot what threshold they implemented, but they did implement one.
