### ISSUE TITLE
RT-AC87U 5GHz guest network - intranet access not working

### ISSUE THREAD

**Issue by jackyaz** [RMerl/asuswrt-merlin#1340]
When setting disble, it has no effect, clients can still access Intranet. Interface seems to come out as vlan4000 rather than wl1.1 (as forum searches show it should be). ebtables shows the matching rules as per 2.4GHz, but they don't seem to work.

**Comment by hggomes** [comment]
That's a well known issue on that model, together with other 3, they addressing the issue since January 17, expect it on next 382.xxxx code.

**Comment by RMerl** [comment]
This will have to be fixed upstream by Asus.
