### ISSUE TITLE
is Merlin gonna release firmware for the new ROG GT-AC5300 ??

### ISSUE THREAD

**Issue by mbugshan** [RMerl/asuswrt-merlin#1341]
is there a Merlin firmware release for ROG Rapture GT-AC5300 ? or it will be ?

**Comment by unsynaps** [comment]
According to this yes: https://wikidevi.com/wiki/ASUS_RT-AC5300

But I think that site has been proven wrong in the past.

**Comment by mbugshan** [comment]
thats the RT-AC5300. I'm talking about the new GT-AC5300

**Comment by mbugshan** [comment]
thank you,

**Comment by RMerl** [comment]
No final decision has been made yet for the long term, but the short term answer is "no".
