### ISSUE TITLE
DNS Filtering doesnt filter DNS?

### ISSUE THREAD

**Issue by matt-gb** [RMerl/asuswrt-merlin#1342]
Hello,
Love Merlin Firmware - going to contribute later on..!

I've configured DNS Filtering as following :
1. WAN Settings
- Connect to DNS Settings Automatically : No (208.67.222.222, 208.67.220.220)
2. Global Filtering Mode : Router (I've tried the OpenDNS options as well as Custom-1)
Custom: (208.67.222.222, 208.67.220.220)

However testing shows this isnt working..
a) dig www.cnn.com
....SERVER: 192.168.1.1#53(192.168.1.1) - Not 208.67.222.222
b) dig www.cnn.com@8.8.8.8 (google)
;; SERVER: 192.168.1.1#53(192.168.1.1) - Ok, thats strange..but its still not 208.67.222.222

Any suggestions - or is this a known bug...?

PS Any plans to pickup the OpenDNS Umbrella integration..?

many thanks!
M

**Comment by RMerl** [comment]
Please use the support forums at SNBForums for support requests.
