### ISSUE TITLE
Merlin Firmware leaves 3 WAN TCP open ports in default state (21,25,80)

### ISSUE THREAD

**Issue by matt-gb** [RMerl/asuswrt-merlin#1343]
I've configured my Merlin with OpenVPN (very nice integration btw!)

So I thought next...I should at least do a quick port-scan on the puppy to see whats open..
OpenVPN : UDP port 1194 and another on TCP 443)

Plug in my iphone to my PC, disable wifi, run up a VPN (I dont want to be flagged as a bad guy!)

nmap at my IP and what do I see...

PORT    STATE SERVICE
21/tcp  open  ftp
25/tcp  open  smtp
80/tcp  open  http
443/tcp open  https

So I figure OpenDNS is 443 - but leaving open 21 (FTP), 25 (SMTP) and 80 (http) - by default..??

I tried telnetting to those ports, and it didnt show me much - however surely we should have 21, 25 and 80 disabled by default on the WAN side..?

many thanks!
M

**Comment by Syst3mSh0ck** [comment]
You are testing the VPN provider endpoint, not your local WAN IP connectivity. Most VPN providers will leave these ports open by default so nothing to worry about.

**Comment by RMerl** [comment]
As pointed out, these ports aren't open by the firmware, but by your configuration.

By default, out of the box, there are zero ports open to the WAN.
