### ISSUE TITLE
How to Remove Xwrt-Vortex!

### ISSUE THREAD

**Issue by 50mbs** [RMerl/asuswrt-merlin#1352]
Recently my son downloaded a file it seems from your github repository and installed the firmware for Asus into our local router for whatever reason. I have searched and searched but found no light on how to revert back to the default Netgear R8000 firmware. Do you have a file or instruction kit for us to do this?

Any info given will be greatly appreciated.

**Comment by RMerl** [comment]
The Vortex firmware isn't from me, it's someone else's fork of my work.  You will have to contact him about it, I have no idea if/how it can be reverted back to the stock firmware.  I'm not involved in any way in his project.
