### ISSUE TITLE
User interface in 4k monitor 21:9

### ISSUE THREAD

**Issue by antopoli** [RMerl/asuswrt-merlin#1353]
The top of the ui page (where you can read the firmware version) is shifted on the right.

**Comment by kokspflanze** [comment]
same problem if you zoom

@antopoli your zoom is at 100%? `CTRL + 0`

**Comment by RMerl** [comment]
This is an old bug that happens if the window is enlarged wider than a certain width.  Unfortunately, even on my dual screen setup at the office I can't make it large enough to reproduce it, so this is something that someone else will have to fix.

**Comment by RMerl** [comment]
Should be fixed with 67577a7e1c4dcaf338701b043e94d0af9b991962.
