### ISSUE TITLE
Time Machine support on Asus N66U 

### ISSUE THREAD

**Issue by unCleanCode** [RMerl/asuswrt-merlin#1354]
Officially that's a limitation of this and few other devices, but as far as I understand it's fully software limitation, so why not to remove this limitation from Merlin firmware?

**Comment by RMerl** [comment]
Because Asus didn't license the HFS+ filesystem driver for the MIPS platform - HFS+ is only supported by the newer ARM models.

**Comment by unCleanCode** [comment]
Thx for fast reply, but I found many manuals on how to install it on OpenWRT, only issue was to prepare disk on Mac computer, isn't it possible to add this support to Merlin firmware but give instructions on how to prepare the disk?
