### ISSUE TITLE
Any plans to support RT-AC58U?

### ISSUE THREAD

**Issue by pmalek** [RMerl/asuswrt-merlin#1373]
I just bought RT-AC58U and I am quite surprised how slow the http interface gets after connecting one device via Ethernet cable and one Ethernet cable for WAN.

How much this firmware differs from stock one that Asus provides and when (if at all) do you plan to support RT-AC58U?

**Comment by RMerl** [comment]
There are no plans to support the RT-AC58U, biggest reason being this is not based on Broadcom but on Qualcomm hardware.
