### ISSUE TITLE
Port forwarding to OpenVPN client in 10.0.8.0 subnet

### ISSUE THREAD

**Issue by tprochazka** [RMerl/asuswrt-merlin#1375]
I don't know if it is a bug or feature it works the same in the original firmware and also here.
I'm able to setup port forwarding for any LAN client, but it doesn't work for OpenVPN client connected to my router.

I need to provide public IP address of my router to some device without public IP connected by OpenVPN.

It works, but just from the local network, not from the Internet.
I did not find the reason.

I have RT-N66U and firmware 380.66_4

**Comment by tprochazka** [comment]
I checked iptables and there is correctly
-A VSERVER -p tcp -m tcp --dport 80 -j DNAT --to-destination 10.8.0.5:80
Without -i so it should works for all interfaces
Maybe is the problem in the opposite direction.

**Comment by tprochazka** [comment]
I tried to setup open VPN server to use TAP.
Now the client has my LAN subnet correctly, but it works worst, also from the local network I'm not able to connect the client.

**Comment by tprochazka** [comment]
I asked on Asus Support and they told me that this is officially not supported thing.

**Comment by RMerl** [comment]
The issue tracker is only for development purposes.  If you need technical support or have a question, please use the support forums at https://www.snbforums.com/forums/asuswrt-official.51/ instead.
