### ISSUE TITLE
Configure multiple IPs and associated NAT forwarding rules on WAN interface

### ISSUE THREAD

**Issue by boldandbusted** [RMerl/asuswrt-merlin#1377]
It would be great to have the ability to make use of the extra IPs on my Internet connection. Thanks.

**Comment by RMerl** [comment]
There are no plans to implement this, as this would require some extensive low-level changes, and this is beyond the scope of this project.

It's currently possible to manually configure it through scripting, have a look at the support forums as I believe this was discussed a while ago.
