### ISSUE TITLE
ipset help spelling error

### ISSUE THREAD

**Issue by uihdff** [RMerl/asuswrt-merlin#1383]
Platform: Asuswrt-Merlin 380.67 _alpha2
Hardware: Asus RT-AC88U

ipset v. 6.29 help has a spelling error

`swap FROM-SETNAME TO-SETNAME`

`        Swap the contect of two existing sets`

It looks like "contect" is supposed to be "contents"

**Comment by RMerl** [comment]
The typo is in the ipset code itself - I recommend submitting the issue to the ipset developers so it can be fixed upstream (I see it's still there in 6.32).

**Comment by RMerl** [comment]
Closing this, as I generally don't spend time fixing typos in third party modules - this should be submitted upstream rather.
