### ISSUE TITLE
Would it make sense to upgrade the kernel?

### ISSUE THREAD

**Issue by IComplainInComments** [RMerl/asuswrt-merlin#1387]
It seems the router is using a no longer supported version of the Linux kernel (according to kernel.org). Would it make sense to upgrade it?

Considering the performance and security gains it can bring?

I know the 4.x kernels offer a lot of performance improvements and support for a lot of ARM based devices.

**Comment by RMerl** [comment]
That's not possible, only Broadcom can do that - and they never upgrade kernels for existing SDKs.
