### ISSUE TITLE
Incorrerct "Connection status" representation on the "OpenVPN Servers" page.

### ISSUE THREAD

**Issue by asredn** [RMerl/asuswrt-merlin#1388]
Router: RT-AC68U
Firmware: 380.66_4

On the bottom of "VPN/OpenVPN Servers" page, in the "Username and Password" table, the сonnection status for each OpenVPN User have to be represented.
In case if only one OpenVPN User is connected, the status in the column "Connection status" is represented correctly ("Connected")
But in case if more than one OpenVPN Users are connected at the same time, all statuses in the column "Connection status" are represented as "Disconnected".

**Comment by RMerl** [comment]
Fixed with 9798a0bb46cbd21291baaf960ca07be6c5bb9e2e.
