### ISSUE TITLE
5G guest wifi allows access to intranet

### ISSUE THREAD

**Issue by petersohn** [RMerl/asuswrt-merlin#1391]
I have an Asus RT-AC87U router with Merlin version 380.66_4. I set up a guest wifi network for both 2.4G and 5G bands, intranet access disabled for both. The 2.4G works as expected, but with the 5G the intranet can still be accessed.

**Comment by jackyaz** [comment]
Known issue, needs to be fixed upstream by Asus

**Comment by RMerl** [comment]
This is outside of my control, and will have to be fixed by Asus.
