### ISSUE TITLE
VPN Issue

### ISSUE THREAD

**Issue by Octolus** [RMerl/asuswrt-merlin#1392]
I'm using the OpenVPN Client.

It's leaking the real IP Address even when block when offline is on. It seems that when I have two VPN Clients at once, it only works on one of them and the other one not.

I'm using routing on both + block if client is down.

I am using AC88U the latest version that came out. Updated yesterday, it happened on the old one too (randomly).

**Comment by RMerl** [comment]
This is most likely a configuration issue.  Please use the support forums for further troubleshooting.
