### ISSUE TITLE
router rebooting

### ISSUE THREAD

**Issue by cz-michi** [RMerl/asuswrt-merlin#1395]
Hello, since 380_66 build i'm experiencing random reboots of my AC66U rev A, don't know how to debug it more, the last message in syslog is about key regenration of VPN clients
any help is apperciated, thanks

**Comment by pongells** [comment]
same happens to me. trying the beta now.

**Comment by cz-michi** [comment]
i also tried to hold WPS button during start to flush everything, but no success. today i got 2 reboots

**Comment by RMerl** [comment]
Random reboots are typically caused by a hardware issue, as there are no widespread reports of similar issues that would tie it to the firmware.
