### ISSUE TITLE
Cannot apply DNS Filtering as well as dnsmasq for SafeSearch

### ISSUE THREAD

**Issue by richardlock** [RMerl/asuswrt-merlin#1396]
Hi.  Thank you for the work on asuswrt-merlin.  Is it possible to use the DNS Filtering and the dnsmasq features at the same time to enforce safe search as well as use OpenDNS filtering?  It doesn't seem to apply the dnsmasq addresses when I enable DNS Filtering.  It would be great to be able to filter DNS and force safe search.

Thanks, Richard

**Comment by RMerl** [comment]
This is a limitation of the technology, as DNSFilter forces redirection of DNS traffic toward the configured server, ignoring the router's dnsmasq resolver.  This is how it prevents users from bypassing the filter.
