### ISSUE TITLE
VPN client encoding problems with passwords and special characters

### ISSUE THREAD

**Issue by Kapot** [RMerl/asuswrt-merlin#1398]
Hi there,

Not really sure if it is an error but wanted to let you know.

On my AC66U/VPN/Open VPN Clients page there seems to be some errors with 'special' characters like % $ & etc. Whenever I want to start the VPN connection after I turned it off it tells me the authentication was wrong. When I click the box 'show password' the password isn't right; it suddenly is a lot longer with stuff like '&#-32&#-68&#'.  I need to retype my password every time before I can connect again.

Also, the 'Please wait, 44% Applying settings' popup goes above 100%, only on this page. It usually goes to 170+ % for me. Minor thing tho ;)

Thanks in advance!

**Comment by RMerl** [comment]
First issue seem related to form encoding.  I'll see if I can something about it.

Second one is random, and I have no idea what triggers it.  I have only seen it happen twice myself over the months.

**Comment by RMerl** [comment]
Can you provide me with an example password causing the issue?  I just tested with "t1$t2%t3" here, and the password is correctly stored and retrieved from nvram.

**Comment by Kapot** [comment]
Sure. Something similar to: &76VreFNW!

**Comment by RMerl** [comment]
The issue is probably specific to the "&76" part, which gets interpreted as a meta entity by the web browser.  I'll see if it's possible to escape such sequences from it.
