### ISSUE TITLE
 The wireless device can not ping unresponsive.

### ISSUE THREAD

**Issue by zuozhehao** [RMerl/asuswrt-merlin#1400]
![20170630094904](https://user-images.githubusercontent.com/4464252/27717756-c89587c8-5d79-11e7-899d-749eef27ba43.png)

380.66_4

In the RT-AC5300, if I closed, prohibit the wireless device interoperability. I use two notebook PING, did not respond.

When I turn it on, I can ping the wireless device.

**Comment by wyemun** [comment]
Why is this closed? I have the same issue.
