### ISSUE TITLE
traffic monthly rollup on usb storage

### ISSUE THREAD

**Issue by duecedriver** [RMerl/asuswrt-merlin#1404]
running latest firmware

have a usb formatted for external and its 

/mnt/memorex/traffic
/tmp/mnt/memorx/traffic

in tools/othersettings
custom location has been set as /tmp/mnt/memorx/traffic/   with the trailing slash and both files are created

     4 -rw-rw-rw-    1 admin    root          2781 Jul  3 09:38 tomato_cstats_d850e693d000.gz
     4 -rw-rw-rw-    1 admin    root           167 Jul  3 09:35 tomato_rstats_d850e693d000.gz

reboots seem to retain daily stats and per client is also enabled and has daily and monthly

but going to traffic montly there is no history for jun, just july... even though there are daily rollups for jun showing up in daily... to clarify I am talking general traffic not per device.. that seems to be working

thoughts?

does it need a full month for a monthly rollup or should june have a monthly rollup calculated even though it is partial?

**Comment by RMerl** [comment]
Please use the support forums at SNBForums for support requests.

Yes, monthly traffic is only accumulated after a month cycle is complete.
