### ISSUE TITLE
security camera WAN leakage?

### ISSUE THREAD

**Issue by duecedriver** [RMerl/asuswrt-merlin#1406]
N66u running merlin latest

I have some inexpensive hosafe wired ip security cameras on the network and noticed when plugged in they make contact with dozens of servers.. mostly in china...

i put them into parental control with deny all time to firewall them from the WAN.. so I thought but per device monitoring is showing they have numerous TCP and UDP connections and there is still upload traffic being accumulated although looks like no download traffic count?

better way to firewall these to keep them secure?

parental controls working or are they leaking

all NAT passthrough settings are off and I believe I have nat acceleration off due to per device monitoring and ASUS NAT selected..

thanks

**Comment by RMerl** [comment]
Please use the support forums at SNBForums for support requests.
