### ISSUE TITLE
SQM QoS?

### ISSUE THREAD

**Issue by eversins** [RMerl/asuswrt-merlin#1408]
Any chance we can get a simple SQM (Smart Queue Management) QoS to prevent buffer bloat? Is hardware acceleration always disabled if using QoS?

Thanks.

**Comment by RMerl** [comment]
What can be done is limited by the old kernel Broadcom uses (2.6.36).  fq_codel was already backported, however it's only available on models using 2.6.36, and also currently only with Traditional QoS.  The RT-N66U and RT-AC66U kernel is much too old.

**Comment by RMerl** [comment]
Closing this, as limited SQM was already available for Traditional QoS and now Adaptive QoS - this is the best that can be done with the current kernel version.

**Comment by ChriscomIT** [comment]
Great to see the QoS improvements for Adapative QoS. Nice work Eric!!
