### ISSUE TITLE
Source Target tool tip does not display

### ISSUE THREAD

**Issue by julsssark** [RMerl/asuswrt-merlin#1409]
In the WAN -> Port Forwarding tab, a question mark appears over the "Source Target" field when the cursor hovers over the label (see screenshot), but nothing appears when clicked.  The cursor should either not turn into a question mark over that field or a tooltip should be displayed when the user clicks. 

![2017-07-04_12-56-00](https://user-images.githubusercontent.com/29901255/27841770-ea74d0c8-60b8-11e7-9d91-7373ee74c999.jpg)

**Comment by RMerl** [comment]
Known issue, but I kept forgetting to look into it - thanks for the reminder.
