### ISSUE TITLE
NTP / DNS not working on router (380.x)

### ISSUE THREAD

**Issue by MarkusI72** [RMerl/asuswrt-merlin#1415]
With 380.66_6 on my RT-AC68U I have issues with DNS and NTP.
With all clients, DNS works well but not on the router itself.
E.g. using network tools to ping Google or so fails resolving the hostname.
NTP does not sync at all (because it also has issues resolving the hostname of NTP server?)..

The symptom was that OpenVPN did not work anymore (certificate not valid yet) because the router server time was back somewhen in 2015...

**Comment by hoerbi1000** [comment]
yes asus ddns also not working for me

**Comment by MarkusI72** [comment]
Same with 380.67_0, DNS not working, NTP not working

**Comment by MarkusI72** [comment]
Any update on this?

**Comment by unsynaps** [comment]
Sounds like something specific to your router/ISP/configuration. Not sure about anyone else but I am having no problems.

**Comment by MarkusI72** [comment]
So, your NTP works and your network tools (e.g. ping google) from within the router UI?
Clients do not show any issue.

**Comment by MarkusI72** [comment]
Strange - for whatever reason - it somehow recovered from the issue...
