### ISSUE TITLE
2.4Ghz wireless stopped accepting connections

### ISSUE THREAD

**Issue by Tailslide** [RMerl/asuswrt-merlin#1418]
After switching from stock firmware to 380.66_6 on the AC3200 and having it work great for a couple days I noticed all the devices connected via the 2.4 radio were disconnected. When I tried reconnecting them I got a 'password incorrect' message.  I toggled the security on the radio from WPA2-Personal to WPA-Auto Personal, applied, then changed back to WPA2-Personal and applied again, and all the devices immediately reconnected.

**Comment by RMerl** [comment]
Wireless code is identical to stock firmware, as it's closed source anyway.  Unlikely to be an issue caused specifically by this firmware.
