### ISSUE TITLE
Dual Wan, Secondary always disconnected state

### ISSUE THREAD

**Issue by GitzJoey** [RMerl/asuswrt-merlin#1422]
I dont know whether thats the correct state
but imho it shouldn't show as disconnected, coz it's very misleading

Dual Wan (Wan and USB Modem, fail over mode, RT-N66U)

**Comment by RMerl** [comment]
I don't touch the Dual WAN code, so behaviour will be the same as with stock firmware.  Any issue there would have to be fixed by Asus.
