### ISSUE TITLE
Enhancement: Add a Way For Users To Edit Famous Games List

### ISSUE THREAD

**Issue by FormalHellhound** [RMerl/asuswrt-merlin#1423]
It would be great if there was a way for users to be able to create a json file that could be loaded by Advanced_VirtualServer_Content.asp that users could edit, which wouldn't get deleted upon flashing a newer version of the firmware.

**Comment by RMerl** [comment]
Those are just presets, I see no point in such a thing.  It's faster to lookup a port on the web and create the forward than crafting a json file (something that 99% of router owners have no idea how to do anyway).
