### ISSUE TITLE
Asus with RT-AC66U_380.66_6 -- login

### ISSUE THREAD

**Issue by thezoggy** [RMerl/asuswrt-merlin#1424]
ISP had fiber cut, so wan connection was down.

When logging into:
http://192.168.0.1/Main_Login.asp

after putting in login credentials it took me to:
http://192.168.0.1/ajax_ddnscode.asp

Which just displays:
`ddns_return_code = ''; pin_status = ''; ddns_enable = '1'; ddns_host_name = '<removed>'; ddns_old_name = ''; `

If I manually change the url to `http://192.168.0.1` then gui loaded just fine.

**Comment by RMerl** [comment]
This is a know rare random issue.  Unfortunately I have been unable to track it down so far (I've only ever seen it happen two or three times myself so far).  Asus has now started to close some of the httpd referrer validation code, which makes it nearly impossible to do any further troubleshooting on this unfortunately.
