### ISSUE TITLE
NTP queries use ntp_server1 - not settable via GUI

### ISSUE THREAD

**Issue by cbz** [RMerl/asuswrt-merlin#1428]
Due to the following code:

https://github.com/RMerl/asuswrt-merlin/blob/4620b188428fb2cc867f08699879390497247fd0/release/src/router/rc/ntp.c#L189

Both ntp_server1 and ntp_server0 are used as valid values for ntp servers by the NTP subsystem, and by default the router round robins between each of them ntp_server0 is provisionable via the GUI, ntp_server1 is not, and by default is set to time.nist.gov.

In my opinion the code stanza should be changed, or http://router.asus.com/Advanced_System_Content.asp should be changed to enable both values to be set.

**Comment by RMerl** [comment]
This was a recent change by Asus.  I don't know if they intend to eventually expose both settings or not, I'm waiting to see where they are heading with this change first.

**Comment by RMerl** [comment]
Addressed with commit c6c617b998aa448f396a2543704dbfb26e3f9924.
