### ISSUE TITLE
RT-AC3200 5G-1 not showing

### ISSUE THREAD

**Issue by ken555** [RMerl/asuswrt-merlin#1432]
When I get the RT-AC3200, I saw the 2.4G, 5G-1 and 5G-2. After upgrading to merlin, the 5G-1 disappears. I tried changing the SSID of it, tried changing control channel to 40 or any other 4 available channels. It still doesn't show up. Only 5G-2 shows.

I am in USA.

Is it a bug?

**Comment by singhandsingh** [comment]
I had a similar issue with my AC87U. 

Do you have a USB drive plugged in. Remove it.

USB3 interferes with 5Ghz spectrum..

My 5Ghz magically reappeared as soon as i plugged on my USB3 thumb drive :)

**Comment by ken555** [comment]
Thank you for the tip!

**Comment by metekamil** [comment]
https://github.com/RMerl/asuswrt-merlin/issues/1460
