### ISSUE TITLE
RT-AC88U lost 5G WiFi

### ISSUE THREAD

**Issue by ReqPro** [RMerl/asuswrt-merlin#1433]
I was wondering why, during a reboot, the 5ghz LED wasn't lighting up and I couldn't find neither the regular SSID or the guest SSID, so I checked the configuration to see what could cause the 5GHz to fail (picture 1).

![1](https://user-images.githubusercontent.com/3521440/28746029-af8f6cc2-7484-11e7-9815-0c65b822b8b7.jpg)

It tells me I need to activate 5GHz, so I decided to check the 5GHz settings before checking if radio is enabled, as I haven't touched that setting (picture 2). There I saw that it is using channel 0.

![2](https://user-images.githubusercontent.com/3521440/28746032-b9d61b36-7484-11e7-96fe-07fb0824ccd4.jpg)

From there I decided to check if the radio was enabled, just to be sure (picture 3) and confirmed that it was indeed enabled.

![3](https://user-images.githubusercontent.com/3521440/28746035-bf0b27b8-7484-11e7-8fca-3c7ca0494340.jpg)

Lastly I checked the system log, to make sure that the WiFi interfaces are brought up correctly, and they seem to be (picture 4).

![4](https://user-images.githubusercontent.com/3521440/28746036-c323c8be-7484-11e7-855d-24b111be4f20.jpg)

It does not help to reboot, restore factory settings, go to recovery or anything else I could think of.

**Comment by themiron** [comment]
most likely it's hw issue. try official fw and apply for rma if doesn't help.

**Comment by RMerl** [comment]
Please use the support forums for support requests.
