### ISSUE TITLE
RT-AC68U: QoS up/down traffic is treated in reverse when using OpenVPN Client

### ISSUE THREAD

**Issue by carmanj** [RMerl/asuswrt-merlin#1434]
Using firmware: 380.67

I first noticed this the other day when downloading a large file in my Transmission client. It appeared that in the QoS Bandwidth Monitor Gauges appeared to be reflecting that I was uploading a large amount of data, not downloading. Additionally, it appears as though it is actually applying the QoS rules in the same manner (the limited upload speed is actually affecting the download speed). All other clients/traffic that isn't having the VPN's redirect policy rule applied, appears to be correctly having QoS applied as well as displaying properly.
![image](https://user-images.githubusercontent.com/30543806/28747929-b4e6e2a6-7478-11e7-98fb-f925f721ab39.png)

**Comment by RMerl** [comment]
It's not swapped, it's something broken at the lower levels  Asus are aware of the issue, however it's not a priority for them to fix as they consider Adaptive QoS a better alternative.

**Comment by RMerl** [comment]
Actually, it's a different (also known) issue since you are using a VPN client.
