### ISSUE TITLE
RT-AC68U_380.67_0 - FIRMWARE - OPENVPN NOT WORKING

### ISSUE THREAD

**Issue by maxgajo** [RMerl/asuswrt-merlin#1436]
Hi, since last FW update, when I switch on a OpenVPN Client I got the following message:  **_Connecting... (uk-ln-001.privatetunnel.com tcp-client:1194)_** and the client is not working. As I didn't change any setting in my RT-AC68U and the OpenVPN file is the same, I was wondering if it is a (known) problem fo the FW.
BTW, this is happening with ALL the servers provided around EU, not the only UK.
Tks
Max

**Comment by RMerl** [comment]
This is most likely a configuration issue, please use the support forums at SNBForums for support requests.
