### ISSUE TITLE
DNS Filtering

### ISSUE THREAD

**Issue by Timeslides** [RMerl/asuswrt-merlin#1441]
Not sure if it's just me but I can't seem to get DNS filter rules in the client list to work. Global filtering works just fine but no matter what settings I try any rule I put for a specific client does not work, they only follow what the global setting is. Can someone else test this for me?

**Comment by RMerl** [comment]
Works for me.

Make sure you're not using an OpenVPN tunnel, which might override your DNS settings with its own enforced rules.
