### ISSUE TITLE
Proprietary drivers free version

### ISSUE THREAD

**Issue by Bitim** [RMerl/asuswrt-merlin#1448]
I saw on your website that you are using proprietary drivers for some features:
> enhanced NTFS performance (through the proprietary drivers used by Asus from either Paragon or Tuxera)

Is there any version free of this proprietary drivers?

Are there any other parts in the released binaries that are closed source? If yes, what are they?

Thanks.

**Comment by RMerl** [comment]
It's impossible to compile a version that's 100% free of proprietary code.  The wireless driver and everything associated to it are closed source for instance.

**Comment by Bitim** [comment]
> It's impossible to compile a version that's 100% free of proprietary code. The wireless driver and everything associated to it are closed source for instance.

So it won't be really usable. Other third-party firmwares like DD-WRT are also using  these proprietary drivers?

**Comment by RMerl** [comment]
OpenWRT (and variations like Lede) is the only one I know of that is 100% sourced.  Blame it on SoC manufacturers like Broadcom and Qualcomm who refuse to open source their drivers.

**Comment by Bitim** [comment]
Which not support a lot of Asus's products, reason mentioned in OpenWRT website is:
>     Unsupported due to ASUS' proprietary wireless AC implementation

Thanks!
