### ISSUE TITLE
ntpd does not autostart

### ISSUE THREAD

**Issue by Teddyz** [RMerl/asuswrt-merlin#1452]
Hi

I tried to follow the instruction here https://github.com/RMerl/asuswrt-merlin/wiki/Setting-up-an-NTP-Server-for-your-local-lan to run a local ntp-server. 
It does not run automatically. I can run it manually, but it will not run after next reboot. The error-message is not included in 'System Log - General Log'. 

Where did I go wrong? Is there another way to include 'ntpd -l' so it runs after reboot?

Thanks!

**Comment by RMerl** [comment]
Please use the support forums for support requests.
