### ISSUE TITLE
firewall start script causes dhcp to not assign ip-addresses.

### ISSUE THREAD

**Issue by 133794m3r** [RMerl/asuswrt-merlin#1453]
```
#!/bin/bash
iptables -N LOG_DROP
iptables -A LOG_DROP -j LOG --log-prefix "INPUT:DROP: " --log-level 6
iptables -A LOG_DROP -j DROP
iptables -A INPUT -s x.y.z.a -j DROP
```
causes the thing to get stuck at the "waiting for an ip address" status message from the Ethernet connected computer and the laptop's wireless. I don't get how this could happen but for some reason it does. It is _not_ any localhost ip addresses nor the other reserved ones for internal networking. It happens every time I add that rule to the script and restart the router. After that, it never lets anyone connect.

I don't get this. Every single time I put that into the firewall-start script it does that. Each and every single time. If the system isn't using bash but some other shell it shouldn't cause the router to crash that the preferred language isn't available.

**Comment by RMerl** [comment]
Please use the support forums at SNBForums for support requests.
