### ISSUE TITLE
Small GUI issue when you select PPTP on VPN Server

### ISSUE THREAD

**Issue by marceloaf** [RMerl/asuswrt-merlin#1457]
Small GUI issue when you select PPTP on VPN Server (Invalid Character!). Tested on AC5300 and AC87U. Noticed on 380.67 but it is also present in 380.68. See attached pic.
![image](https://user-images.githubusercontent.com/11551691/29588236-1b0bac5a-8767-11e7-935d-41bb09682b84.png)

**Comment by RMerl** [comment]
Enable it and look at the content of the client list.  This error message will show up if there's an invalid username.
