### ISSUE TITLE
Problems with detection of external disk, if external disk connected to USB 3.0 port on RT-AC68U.

### ISSUE THREAD

**Issue by SevenMaxs** [RMerl/asuswrt-merlin#1459]
Hi Merlin!
I found one issue:
Router RT-AC68U does not see HDD, if I connect a External HDD (in Thermaltake Muse 5G 3.5" case) to USB 3.0 port.
Router RT-AC68U detects a HDD, if I connect a External HDD (in Thermaltake Muse 5G 3.5" case) to USB 2.0 port.
At the same time Seagate Backup Plus Slim 1TB External HDD (STDR1000100 SDR00F1) works fine in any of the USB ports.
This problem is on all the firmware version that I had time to check (RT-AC68U_380.6Х).

Thx U!

**Comment by RMerl** [comment]
The issue tracker is only for development purposes.  If you need technical support or have a question, please use the support forums at https://www.snbforums.com/forums/asuswrt-official.51/ instead.
