### ISSUE TITLE
NAS not showing up on network map

### ISSUE THREAD

**Issue by sondr3** [RMerl/asuswrt-merlin#1461]
Hello, I'm having a weird issue where my NAS (Synology) isn't showing up on my network map and running `nmap` on the local network doesn't show it there either, but I can access it just fine from Finder in OS X. I just don't know the IP for it. I have a `RT-N66U` running `Firmware:380.67`.

**Comment by sondr3** [comment]
I just upgraded and it shows up on the side where it lists that there's one cable being used in the Ethernet slots, but I still have no idea what the IP is. 
<img width="314" alt="screen shot 2017-08-26 at 01 57 55" src="https://user-images.githubusercontent.com/2280539/29736494-020d653e-8a02-11e7-949b-df3d3b045b4d.png">

**Comment by RMerl** [comment]
Please use the support forums at SNBForums for support requests.
