### ISSUE TITLE
VPN Clients set to OFF will self-activate on reboot [RT-AC87U/ FW: 380.68]

### ISSUE THREAD

**Issue by aybase** [RMerl/asuswrt-merlin#1463]
Scenario: VPN clients 1 trough 5 all have been configured to connect to different servers with the same VPN provider. However only client 1 is turned ON, whereas 2 through 5 are toggled OFF. 

Once the RT-AC87U is rebooted, ALL VPN clients become activated and must be turned off individually.

**Comment by jackyaz** [comment]
Have you made sure you have set "Start with WAN" to Yes?

Also post things like this here: https://www.snbforums.com/forums/asuswrt-merlin.42/

**Comment by aybase** [comment]
@jackyaz Yes you were absolutely correct about "Start with WAN", thanks.
Also thanks for the forum link, I'll use that for questions moving forward.
