### ISSUE TITLE
No Way to import Intermediate certificate

### ISSUE THREAD

**Issue by tldzyx** [RMerl/asuswrt-merlin#1465]
### In the AiCloud ui like this and it's work
![image](https://user-images.githubusercontent.com/5987706/29995421-94c506f6-901b-11e7-89d7-e66a06e100dd.png)
![image](https://user-images.githubusercontent.com/5987706/29995446-07ce39ec-901c-11e7-9a38-a40f2a974392.png)

---

### But in the mamage web ui to Advanced_System_Content.asp, it's like this and it's not work
![image](https://user-images.githubusercontent.com/5987706/29995436-e121f720-901b-11e7-93ec-cd129dd99a47.png)
![image](https://user-images.githubusercontent.com/5987706/29995453-14e47e0c-901c-11e7-9964-1e7b1165eebe.png)

---

**The firrerent I can see is about the `Intermediate certificate`, could you fix it please**

**Comment by RMerl** [comment]
The AiCloud code is part closed source, part obfuscated.  Any change to it will have to be done by Asus.
