### ISSUE TITLE
After upgrading from version 380.66_6 to 67 the Blacklist blocks all traffic

### ISSUE THREAD

**Issue by DunkanMkLaud** [RMerl/asuswrt-merlin#1471]
I have a problem. In versions 380.67 and 380.68, the Blacklist does not work as expected. In version 66_6, everything is fine. When upgrading from version 380.66_6 to 67 or 68, the Blacklist blocks all traffic including icmp.

**Comment by RMerl** [comment]
The issue tracker is only for development purposes.  If you need technical support or have a question, please use the support forums at https://www.snbforums.com/forums/asuswrt-official.51/ instead.
