### ISSUE TITLE
l2tp vpn) ALL Internet traffic use remote PUBLIC internet.

### ISSUE THREAD

**Issue by noainred** [RMerl/asuswrt-merlin#1475]
"Currently version of L2TP vpn" use remote PUBLIC internet IP

How can I  use l2tp vpn to specific subnet.

**# Current)**

    *==============*================*========Remote Site / Public internet
(Local)                        (merlin)                 (L2TP VPN server)

**# I want to use)**

      *============ *-----------------------*------  ( Remote Site/192.168.11.0/24 )
                                     |
                                    *-------------------------------- PUBLIC Internet

 ( Local)                (merlin)

**Comment by RMerl** [comment]
The issue tracker is only for development purposes.  If you need technical support or have a question, please use the support forums at https://www.snbforums.com/forums/asuswrt-official.51/ instead.
