### ISSUE TITLE
Possible bug in log file display, affecting only some browsers

### ISSUE THREAD

**Issue by ShakeThat** [RMerl/asuswrt-merlin#1476]
When I first load the "System Log" page, the log data is displayed properly. But when the refresh occurs, everything after the first appearance of a "<" in the log data disappears. This behavior began in some recent firmware release, probably 380.68. It might result from the following code in Main_LogStatus_Content.asp:

    document.getElementById("textarea").innerHTML = logString;

There is a line in the log that looks like:

    ipt_account 0.1.21 : Piotr Gasidlo <quaker@barbara.eu.org>, http://code.google.com/p/ipt-account/

and I suspect that "&lt;quaker@barbara.eu.org&gt;" is looking like invalid HTML, causing it and everything that follows to disappear. Note that the browser I'm using is quite old, and the problem does not occur with some I've tried, so I don't consider this critical. When I click the "Save" button, the entire log is downloaded, without truncation.

Presumably there is not expected to be markup in the logString, so the assignment to .innerHTML looks questionable to me (but I'm no web developer). Should it be setting .value instead? Or maybe logString should be html-escaped, because a user script could add problematical HTML to the log?

**Comment by ShakeThat** [comment]
Of course I meant "&lt;quaker@barbara.eu.org&gt;", ha ha.

**Comment by Syst3mSh0ck** [comment]
Thanks for repoting. Can you please advise which browser this impacts?

**Comment by ShakeThat** [comment]
The problem occurs with Safari 4.1.3 and OmniWeb 5.11.2, both ancient, running on an ancient Mac (my daily driver, for reasons). Naturally, there had not been a problem until auto-refresh of the log was introduced., so it looked like a bug.

I've since tested it with current versions of Safari, FireFox, Chrome and OmniWeb, all of which do NOT exhibit the problem. Therefore, it's more likely a bug in the old browsers, or maybe a standards change, so I'm going to close this. Thanks for looking!
