### ISSUE TITLE
QOS 

### ISSUE THREAD

**Issue by nu1ee** [RMerl/asuswrt-merlin#1477]
FQ_CODEL
1 configuration failed to save
2 PPPOE VC / MUX </ option is not more </ option?
How should i know which type of my PPPOE belongs to?

**Comment by Syst3mSh0ck** [comment]
VCMUX and LLC ie Snap Bridging only apply to ATM and therefore PPPoA connections normally used for ADSL. PPPoE uses 802.11Q VLAN Tagging instead so these configuration options do not apply in this case. It is not clear what the actual problem is that you are experiencing so please clarify. Thanks.

**Comment by RMerl** [comment]
The issue tracker is only for development purposes.  If you need technical support or have a question, please use the support forums at https://www.snbforums.com/forums/asuswrt-official.51/ instead.
