### ISSUE TITLE
DDNS error: no-ip.com

### ISSUE THREAD

**Issue by VNGXR** [RMerl/asuswrt-merlin#1485]
> Sep 21 23:54:27 ddns_update: ez-ipupdate: starting...
> Sep 21 23:54:28 ddns_update: connected to dynupdate.no-ip.com (8.23.224.120) on port 80.
> Sep 21 23:54:28 ddns_update: request successful
> Sep 21 23:54:28 ddns_update: asusddns_update: 0

It shows "ddns_fail_hint" on index page with "Request error! Please try again", but the update succeeded.

**Comment by Syst3mSh0ck** [comment]
Can you include a screenshot of the issue reported please? Thanks.

**Comment by VNGXR** [comment]
On the index page: <img width="533" alt="2017-09-27 16 21 15" src="https://user-images.githubusercontent.com/32178677/30915648-1f7dbcf6-a3a0-11e7-8e23-0299f2a060df.png">
On WAN - DDNS page: 
<img width="505" alt="2017-09-27 16 13 46" src="https://user-images.githubusercontent.com/32178677/30915734-565dea16-a3a0-11e7-94ac-0b56d9245c3a.png">

**Comment by RMerl** [comment]
Can't reproduce here (also using No-IP).
