### ISSUE TITLE
Use a proper button for submitting the login form

### ISSUE THREAD

**Issue by chrboe** [RMerl/asuswrt-merlin#1488]
Currently the login form is submitted via a `div` element that's disguised as a button:

    <div class="button" onclick="login();">Sign in</div>

This breaks auto-submitting of the form. Extensions such as [browserpass](https://github.com/dannyvankooten/browserpass) depend on `<input type="submit">` elements being present to automatically fill and submit password forms. It would thus be better to use a proper `submit` button to ensure compatibility with such extensions.

(See also https://github.com/dannyvankooten/browserpass/issues/156)

**Comment by Syst3mSh0ck** [comment]
Agreed this would be a nice fix which appears to be quite trivial.

**Comment by RMerl** [comment]
Not sure what was Asus's reason behind that design decision - perhaps so it can more easily be disabled if an invalid firmware is detected?

I'd need to get a clearer idea as to the reason behind their decision before changing that.

**Comment by alindt** [comment]
After many years of debugging Chinese software, I'm pretty sure it is just a weird way of achieving a simple task, with no real design decision behind

**Comment by RMerl** [comment]
Fixed on AM382, will consider backporting it to this branch based on future release plans for a 380.xx release.
