### ISSUE TITLE
380.68_2

### ISSUE THREAD

**Issue by daddyg76266** [RMerl/asuswrt-merlin#1489]
Hello, 

I'm attempting to flash 380.68_2 onto the AC88U.  It gets through the process and says complete with no errors but after router reboot - manual and through UI - it doesn't appear as if the actual firmware loaded.  None of the changes on the UI are visible.

I've also flushed my browser cache.

What am I doing wrong?

**Comment by Syst3mSh0ck** [comment]
Does the firmware version change at the top of the UI? Are you able to flash any previous versions successfully?

**Comment by daddyg76266** [comment]
This has been resolved.  I had to unplug my usb powered fans, reboot and then load updated firmware.
