### ISSUE TITLE
API for IP routing

### ISSUE THREAD

**Issue by hardpumps** [RMerl/asuswrt-merlin#1491]
Hello,

A neat feature would be some very limited API that would allow the gateway for each client to be set such that one could easily toggle between VPNs, TOR, default gateways. OS specific 'client' could be created to interface with this and changing things could be as simple as right clicking a taskbar icon and selecting the desired tunnel. Could be useful for GeoIP protected sites and such.

**Comment by RMerl** [comment]
You can use SSH and scripting.  Adding a dedicated API for this is beyond the scope of this project.
