### ISSUE TITLE
5GHz band is gone on 380.68_2 - Asus RT-AC66U

### ISSUE THREAD

**Issue by szalap** [RMerl/asuswrt-merlin#1493]
Hi,

After upgrading to the latest and greatest I have lost my 5GHz network. I have checked it on multiple devices and the 5GHz was nowhere to be found. 
After downgrading to 380.68_0 everything is back to normal and I have both 2.4GHz and 5GHz available.

**Comment by alindt** [comment]
@szalap
I'm using 380.68_2 on a RT-AC66U_B1 and the 5GHz band works fine.
Do you have the A1 or B1 hw revision?

**Comment by szalap** [comment]
It's A1 revision, so I guess here might be the issue.

**Comment by gschukin** [comment]
Have the same problem with RT-N66U. 5GHz doesn't gone completely, but available from time to time

**Comment by RMerl** [comment]
Not a firmware issue, especially as there's been zero wifi-related changes between 380.68_0 and 380.68_2.
