### ISSUE TITLE
Which program is adding these two iptables rules???

### ISSUE THREAD

**Issue by iMocW** [RMerl/asuswrt-merlin#1494]
-A PREROUTING -p udp -m udp --dport 53 -j DNAT --to-destination 192.168.1.1:18018
-A PREROUTING ! -d 172.22.22.0/24 -p tcp -m tcp --dport 80 -j DNAT --to-destination 192.168.1.1:18017

**Comment by iMocW** [comment]
-A PREROUTING -p udp -m udp --dport 53 -j DNAT --to-destination 192.168.1.1:18018
-A PREROUTING ! -d 172.22.22.0/24 -p tcp -m tcp --dport 80 -j DNAT --to-destination 192.168.1.1:18017

**Comment by iMocW** [comment]
Broke all HTTP/DNS request

**Comment by VNGXR** [comment]
Administration / System / Enable WAN down browser redirect notice = No

**Comment by iMocW** [comment]
So this is a bug? Because my WAN connection is set correctly (via PPPoE and nothing wrong).

**Comment by RMerl** [comment]
The issue tracker is only for development purposes.  If you need technical support or have a question, please use the support forums at https://www.snbforums.com/forums/asuswrt-official.51/ instead.
