### ISSUE TITLE
custom script services-start only excute the first line

### ISSUE THREAD

**Issue by skyflying1989** [RMerl/asuswrt-merlin#1495]
when i use the services-start below:
#!/bin/sh
logger "start test!!!"
logger "test1"
logger "test2"
logger "test3"
after reboot, "start test!!!" only could be found in syslog.
Then services-start was changed below:
#!/bin/sh
/jffs/scripts/test
creat test script below:
#!/bin/sh
logger "test1"
logger "test2"
logger "test3"
then reboot again, the three test string could be found in syslog.
Is this a bug? my firmware version is 380.68, router is AC66U B1

**Comment by RMerl** [comment]
Your script is probably not properly encoded in UNIX format.  Not a firmware issue.
