### ISSUE TITLE
wpa2 enterprise - repeater mode | AC68U

### ISSUE THREAD

**Issue by gitty8** [RMerl/asuswrt-merlin#1496]
Hi, is it possible to connect via repeater mode to an wpa2 enterprise secured hotspot?
My device: AC68U Firmware 380.68_2

![image](https://user-images.githubusercontent.com/19901796/31077318-6d4058f4-a77e-11e7-8ed8-dd2f5531009f.png)

Edit:

http://www.ciscopress.com/articles/article.asp?p=1750205&seqNum=4

> If the router is supported and is using an Atheros chipset, you could flash the router with the firmware using their instructions. 

AC68U should have BCM - so still not supported?

Edit2:
https://youtu.be/PD5RSA5S4eg

**wpa_supplicant**  possible? I think it is called PEAP for authentication.

**Comment by RMerl** [comment]
The issue tracker is only for development purposes.  If you need technical support or have a question, please use the support forums at https://www.snbforums.com/forums/asuswrt-official.51/ instead.
