### ISSUE TITLE
DNSMASQ vulnerability

### ISSUE THREAD

**Issue by testn** [RMerl/asuswrt-merlin#1497]
Any plan to fix this soon?

https://security.googleblog.com/2017/10/behind-masq-yet-more-dns-and-dhcp.html

**Comment by RMerl** [comment]
I need to review the report first to determine if it's affecting the current version of dnsmasq Asuswrt uses.  This will occur sometime this week.

Note that dnsmasq is not exposed to the WAN, so the impact isn't as critical as if it were a public-fronting server.

**Comment by RMerl** [comment]
Fixed with 85a936206aac70561efab3c1f08cae60e9cf8f4b.
