### ISSUE TITLE
QoS Traditional Mode not working properly

### ISSUE THREAD

**Issue by void12345** [RMerl/asuswrt-merlin#1499]
i'm using asuswrt-merlin on Asus RT-AC5300 right now, i'm using nbn (australia network) which gives me access to have download speed of 100 mb/s, upload speed of 40mb/s (i paid for this speed). Everything worked perfectly on adaptive mode, i'm able to reach the most speed mode.

However, when switch to traditional mode (my favorite), it only allows me to go up to 20mb/s down, 20mb/s up (tested on both merlin and the official firmware).

**Comment by RMerl** [comment]
Known issue, duplicate.
