### ISSUE TITLE
prevent syslog saving to jffs

### ISSUE THREAD

**Issue by chchia** [RMerl/asuswrt-merlin#1500]
Hi,

is there a way to prevent syslog saving to jffs? or can i move it to usb instead?

i have some script on crontab which run every 15 minutes, and each time it run it generate a line like this

Oct  5 23:45:00 crond[502]: USER admin pid 8889 cmd /opt/test.sh

then it get saved at jffs, which means my jffs will be written every 15 minutes, this is what i would like to avoid.

thank you.

**Comment by ionutz4u** [comment]
Yes, there is a way. You can add in **/jffs/scripts/init-start**

**#!/bin/sh**
**mount -o remount,ro,noatime /jffs**

This way, the /jffs partition will be mounted on start as read-only partition so it won't be written at all.
If you want to edit/add scripts, you can always execute in console: mount -o remount,rw,noatime /jffs  , and after you finish you`ll execute back: mount -o remount,ro,noatime /jffs

**Comment by RMerl** [comment]
The issue tracker is only for development purposes.  If you need technical support or have a question, please use the support forums at https://www.snbforums.com/forums/asuswrt-official.51/ instead.
