### ISSUE TITLE
MiniDLNA 1.2.1 released

### ISSUE THREAD

**Issue by fmpallini** [RMerl/asuswrt-merlin#1502]
Some nice bugfixes, if easy to merge.

1.2.1 - Released 24-Aug-2017
--------------------------------
- Added Movian client detection and subtitle support.
- Fixed an issue with discovery on non-Linux systems.
- Fixed Bonjour discovery compatibility with TiVo Bolt.
- Fixed NFO file parsing, and added change monitoring support for them.
- Added a workaround for video thumbnails on some Samsung clients.
- Added DoS protection for event subscriptions.
- Fixed content browsing issues with some Samsung TVs.
- Improved non-destructive update scan support.

**Comment by RMerl** [comment]
Note that Asuswrt currently uses a snapshot that lies somewhere between 1.2.0 and 1.2.1, so some of these changes are already included.

**Comment by RMerl** [comment]
There are too many changes in 1.2.1, combined with Asus's being now too different from upstream.  This makes it too complicated to merge the two together, so I gave up on it.  Merging will have to come from upstream.
