### ISSUE TITLE
dnsmasq TFTP open to the world by default

### ISSUE THREAD

**Issue by chrisfu** [RMerl/asuswrt-merlin#1508]
Hi everyone,

I've just had notification from my ISP that the in-built TFTP server within dnsmasq is open to the world. I wasn't aware of the UDP port exposure in Merlin (and presumably upstream within the Asus firmware) previously, but I did know that TFTP has been used for roughly a year to amplify distributed denial-of-service (DDoS) attacks by various botnets. More information can be found on that [here](https://tftpscan.shadowserver.org/).

For now I'm going to use a JFFS 'firewall-start' script to add a persistent iptables rule to block external access to this service, as it doesn't appear to be possible to disable it via a dnsmasq.conf.add script.

My initial thoughts as to an out-of-the-box solution would be to enable such an iptables rule by default, allowing the user to toggle it off (and thus the service "enabled") should they wish.

Following up from that, it's probably worth some of us performing a external audit to find out exactly which TCP/UDP ports are exposed out of the box, and what the security issues resulting from those exposures could look like.

Any opinions on this report would be greatly appreciated.

Cheers,

Chris

**Comment by RMerl** [comment]
No, it's not.  The default firewall rules will block access to it, unless you disabled the firewall.
