### ISSUE TITLE
err_network_Changed

### ISSUE THREAD

**Issue by nicoxygen** [RMerl/asuswrt-merlin#1509]
Hello from version 380.68 when I reroute the router I have to synchronize the modem with the router to have an ip address again, and I systematically under google chrome error err_network_changed I have a numericable modem

fr: bonjour depuis la version 380.68 quand je relance le routeur je dois synchroniser le modem avec le routeur pour avoir a nouveau une adresse ip, et j'ai systématiquement sous google chrome l'erreur err_network_changed j'ai un modem numéricable

**Comment by RMerl** [comment]
The issue tracker is only for development purposes.  If you need technical support or have a question, please use the support forums at https://www.snbforums.com/forums/asuswrt-official.51/ instead.
