### ISSUE TITLE
When using dual WAN with WAN and Ehernet port 1 you cannot disable ping response

### ISSUE THREAD

**Issue by mikeq3** [RMerl/asuswrt-merlin#1513]
I'm using Dual WAN in Failover mode. I'm currently failed over to the secondary port with is Ethernet Lan Port 1. I have respond to pings disabled for WAN turned on.
Disabling ping response on WAN apparently does not disable ping response on the Ethernet port 1 when used as a WAN port. This is a serious problem.

**Comment by mikeq3** [comment]
I'm using the Asus RT-AC88U with Asuswrt-Merlin version 380.67

**Comment by mikeq3** [comment]
Can anyone take a look at this?

**Comment by RMerl** [comment]
I don't touch the dual wan code because it's too complex and constantly changing.  You will have to check with Asus.
