### ISSUE TITLE
Displaying in iFrame

### ISSUE THREAD

**Issue by privatesam** [RMerl/asuswrt-merlin#1514]
Hi,

I'm using a webserver app which grabs other webpages and displays them in what I believe to be iFrames for centralised management - https://github.com/causefx/Organizr

Unfortunately the Asus management web ui is not displayed - I've been searching through the html and JavaScript to see if there is something specific, deliberately blocking the site being displayed within an iFrame but can't find anything.  

Does anyone know what this might be and is there a workaround?

Many thanks in advance.

**Comment by RMerl** [comment]
The issue tracker is only for development purposes.  If you need technical support or have a question, please use the support forums at https://www.snbforums.com/forums/asuswrt-official.51/ instead.
