### ISSUE TITLE
Traffic Monitor - Where to view?

### ISSUE THREAD

**Issue by inverse** [RMerl/asuswrt-merlin#1516]
I used to be able to view the traffic monitoring from within the UI but now I cannot find it.

I found the page that enables me to configure it but I cannot see any data.

**Comment by RMerl** [comment]
The issue tracker is only for development purposes.  If you need technical support or have a question, please use the support forums at https://www.snbforums.com/forums/asuswrt-official.51/ instead.

**Comment by inverse** [comment]
Thanks for the clarity.
