### ISSUE TITLE
AC68U Firmware for AC1900P: CPU0 100% usage

### ISSUE THREAD

**Issue by windcarp** [RMerl/asuswrt-merlin#1522]
I got an AC1900P router and flash it with Firmware AC68U.

> Supported Devices: RT-AC1900P (use the RT-AC68U firmware)
https://github.com/RMerl/asuswrt-merlin/wiki/Supported-Devices

However, I found the compatibility is pretty bad and it sometimes stuck so that I have to reboot.

CPU Status:

https://ws4.sinaimg.cn/large/006tNc79gy1fld8zii5gdj30iq0h2dh5.jpg
https://ws2.sinaimg.cn/large/006tNc79gy1fld91ustiuj31gk0k6b2a.jpg

It may be harm for the RT-AC1900P and hope that someone can fix it.

Thanks.

**Comment by RMerl** [comment]
The issue tracker is only for development purposes.  If you need technical support or have a question, please use the support forums at https://www.snbforums.com/forums/asuswrt-official.51/ instead.
