### ISSUE TITLE
【AC86U 382.1 beta 4】The firewall caused NAT not to work.

### ISSUE THREAD

**Issue by iMocW** [RMerl/asuswrt-merlin#1523]
Here's iptables-save output:

[firewalldisabled.txt](https://github.com/RMerl/asuswrt-merlin/files/1461986/firewalldisabled.txt)
[firewallenabled.txt](https://github.com/RMerl/asuswrt-merlin/files/1461987/firewallenabled.txt)

When firewall is on, subnet devices except router itself can not access the internet.
Just turn it off to make link up.

**Comment by iMocW** [comment]
Lack of `iptables -t filter -I FORWARD ! -i ppp0 -j ACCEPT`, in other words: FORWARD chain in filter table causes this problem.

**Comment by iMocW** [comment]
This also causes port forwarding stops working !!!

**Comment by RMerl** [comment]
Remove any customization you've made.  There are a few hundred users out there running this firmware without any problem with their WAN connection, so something on your setup is causing it to break.

**Comment by zeit200** [comment]
Got the same problem after enabling openvpn server
[iptables.txt](https://github.com/RMerl/asuswrt-merlin/files/1485179/iptables.txt)
[server1-fw.sh.txt](https://github.com/RMerl/asuswrt-merlin/files/1485180/server1-fw.sh.txt)
[config.ovpn.txt](https://github.com/RMerl/asuswrt-merlin/files/1485181/config.ovpn.txt)

**Comment by RMerl** [comment]
Already fixed with https://github.com/RMerl/asuswrt-merlin.382/commit/57502aeede08940fdfb704e32b47aa1ba9813d44 .

**Comment by zeit200** [comment]
Thank you

**Comment by iMocW** [comment]
@RMerl No. Still needs `-A FORWARD -i br0 -o ppp0 -j ACCEPT` to make NAT work right. [382.1]

**Comment by iMocW** [comment]
@RMerl  And fake LAN TTL will cause some of LAN side devices speed near to 0Mbps but/when ping is right.
