### ISSUE TITLE
VPN Selective routing via Domain [enhancement]

### ISSUE THREAD

**Issue by seedboxer** [RMerl/asuswrt-merlin#1525]
Really missing this after moving from Tomato.

Please add it.

**Comment by RMerl** [comment]
Can't.  Asuswrt-Merlin's routing is done at the kernel RPDB level rather than through iptables, because otherwise it would conflict with Trend Micro's DPI engine which can arbitrarily wipe out the iptables rules used for Tomato's iptables-based implementation.
