### ISSUE TITLE
Entware runs unsigned code over HTTP

### ISSUE THREAD

**Issue by stiell** [RMerl/asuswrt-merlin#1530]
Both `entware-setup.sh` and the installer script from pkg.entware.net downloads and runs unauthenticated code over HTTP. There's no way to fix this until pkg.entware.net provides HTTPS or signatures for the downloaded files, but until then the documentation should warn that this is insecure.

I don't know how opkg works, but if it doesn't verify package signatures (I can't see that it does), users should be warned about this as well.

**Comment by RMerl** [comment]
Since most people don't even read the documentation, adding a warning wouldn't serve any purpose.  The issue should rather be fixed upstream.
