### ISSUE TITLE
Asus RT-N18u - possible support?

### ISSUE THREAD

**Issue by Eldenroot** [RMerl/asuswrt-merlin#1531]
Hi @RMerl ! Is there any way to get support in your firmware for Asus RT-N18u? Has changed anything? Asus released .382 fw for this unit. It is really popular here in Europe (direct replacement for RT-N16 for a good price. I am free for testing (if there would be any chance to get it working). If not, nevermind, just asking. Keep good work!

**Comment by RMerl** [comment]
I have no plans on supporting the RT-N18U.  It's not available in many regions, and I only focus on high-end models due to the amount of work involved in maintaining each individual models - they each require compatible GPL releases, and I can no longer mix up different GPL releases together.
