### ISSUE TITLE
library for communicating with usb modem

### ISSUE THREAD

**Issue by GitzJoey** [RMerl/asuswrt-merlin#1532]
is it possible to add lib/tool (included in firmware if possible) for communicating with the usb modem

I'm using usb modem as failover but using pre-paid card, sometimes it needed to check the sms received or sending sms to reload the sim-card.

**Comment by RMerl** [comment]
I have no plan on adding anything related to USB modems, as I don't focus on these.  Best chance for you would be to look at what's available on Entware.
