### ISSUE TITLE
How to use dnsmasq-full in the merlin 382.1

### ISSUE THREAD

**Issue by bigcat133** [RMerl/asuswrt-merlin#1533]
my router is RT-AC86U, firmware is 382.1
i want to use dnsmasq-full to redirect the resolve dns stream as the config:
`server=/xxxx.com/127.0.0.1#5353`
`ipset=/xxxx.com/gfwlist`

in here i can find it in opkg
`opkg list|grep dnsmasq-full`
`dnsmasq-full - 2.77-12 - It is intended to provide coupled DNS and DHCP service to a LAN.  This is a fully configurable variant with DHCPv6, DNSSEC, Authoritative DNS and IPset, Conntrack support & NO_ID enabled by default.`

how can i use the opkg dnsmasq-full with stop merlin's dnsmasq

as above cause, how can i to install and use iptables-mod-nat-extra

**Comment by bigcat133** [comment]
i can call:
`service stop_dnsmasq`
to stop dnsmasq
and run:
`/opt/sbin/dnsmasq` to start the opkg's dnsmasq
but that how can i to stop the merlin dnsmasq at restart router

**Comment by RMerl** [comment]
The issue tracker is only for development purposes.  If you need technical support or have a question, please use the support forums at https://www.snbforums.com/forums/asuswrt-official.51/ instead.
