### ISSUE TITLE
Cannot load Merlin Firmware onto RT-AC3200

### ISSUE THREAD

**Issue by cvee72** [RMerl/asuswrt-merlin#1535]
Hi,

My RT-AC3200 is on latest asus firmware 382.

When i try to flash it with Merlin software currently version 380, the upload via Recovery Tool is successful.   The router however never boots up.  It stays in a rebooting loop which goes to the recovery web UI only.

Is this because i'm trying to apply version 380 over asus 382 ?
Is this a firmware lock/verify issue between versions?

It seems i can only restore original asus firmware.
How can i work around this ?

**Comment by RMerl** [comment]
The issue tracker is only for development purposes.  If you need technical support or have a question, please use the support forums at https://www.snbforums.com/forums/asuswrt-official.51/ instead.
