### ISSUE TITLE
L2TP VPN client is missing IPSec pre-shared key config input filed?

### ISSUE THREAD

**Issue by jollychang** [RMerl/asuswrt-merlin#1547]
L2TP VPN client is missing IPSec pre-shared key config filed?
http://ROUTER/Advanced_VPNClient_Content.asp
![screen shot 2017-12-03 at 12 15 50 am](https://user-images.githubusercontent.com/64213/33517427-2a229b60-d7bf-11e7-863d-b02ea7ab89b7.png)
Firmware:380.68_4

**Comment by themiron** [comment]
yes, because it's l2tp only, not l2tp + ipsec client.
