### ISSUE TITLE
The router you are using is not an ASUS device or has not been authorised by ASUS. ASUSWRT might not work properly on this device.

### ISSUE THREAD

**Issue by panther7** [RMerl/asuswrt-merlin#1552]
Sometimes, router stop respond and after reboot say: "Note: the router you are using is not an ASUS device or has not been authorised by ASUS. ASUSWRT might not work properly on this device."
Wifi dont work.

![asus_broken](https://user-images.githubusercontent.com/3808250/33803376-ca1ba6b4-dd8e-11e7-8518-a500ecda7dc4.png)

After randomly reboots, fix that. I dont know how it is posible. I am frustated.

device: ASUS RT-AC66U (not B1)
firmware: "all firmwares" like 380.68_4, 380.69 Beta 1 or original 3.0.0.4.380.xx

**Comment by RMerl** [comment]
If you have the same issue with original firmware then this isn't a bug in my code.  You will have to contact Asus about it.
