### ISSUE TITLE
Power on 5GHz band

### ISSUE THREAD

**Issue by luengnat** [RMerl/asuswrt-merlin#1553]
The range I got on 5GHz is too short. I wonder whether AsusWRT supports higher output for 5GHz band as documented in 

http://community.arubanetworks.com/t5/Controller-Based-WLANs/What-is-the-maximum-allowed-EIRP-based-on-the-FCC-standard/ta-p/178490
https://www.federalregister.gov/documents/2014/05/01/2014-09279/unlicensed-national-information-infrastructure-u-nii-devices-in-the-5-ghz-band
https://transition.fcc.gov/bureaus/oet/ea/presentations/files/oct14/51-New-Rules-for-UNII-Bands,-Oct-2014-TN.pdf

**Comment by RMerl** [comment]
The issue tracker is only for development purposes.  If you need technical support or have a question, please use the support forums at https://www.snbforums.com/forums/asuswrt-official.51/ instead.
