### ISSUE TITLE
DSL-AC68U support

### ISSUE THREAD

**Issue by bdovaz** [RMerl/asuswrt-merlin#1558]
It says "RT-AC68U (and all of its variants)":

https://github.com/RMerl/asuswrt-merlin/wiki/Supported-Devices

Does it cover "DSL" model? I know that DSL parts won't work but I don't used them either.

Also I saw this thread:

http://whatsyourrouter.com/mybb/showthread.php?tid=86

Can I flash it? Thanks.

**Comment by RMerl** [comment]
No, none of the DSL models are supported.  They're not just variants, they're actual different devices, which require specific firmwares.

Anyone forcing the flash of a router firmware on a modem+router model is doing so at his own risk.  The first thing that will definitely not work is the modem part.  The rest may or may not work, depending on how different the hardware is.  For some models, the whole router portion uses completely different hardware, which would result in a bricked router.
