### ISSUE TITLE
router_status.asp issue

### ISSUE THREAD

**Issue by azdps** [RMerl/asuswrt-merlin#1559]
I believe there is an issue with your recent commit to router_status.asp.

https://github.com/RMerl/asuswrt-merlin/commit/eea7c61efa9624550958e4eda47d5179773e615d

Shouldn't this code end with a semicolon?

`var wanLanStatus = get_wan_lan_status["portSpeed"]`

**Comment by RMerl** [comment]
Yes, fortunately most browser interpreters are fairly forgiving (which also means such errors easily go unnoticed).

**Comment by azdps** [comment]
I'm wondering if this will fix the webui issues some users have been reporting with your recent release.
