### ISSUE TITLE
PrintServer on RMerlin

### ISSUE THREAD

**Issue by steelrat2000** [RMerl/asuswrt-merlin#1560]
Hello. I have an Xerox Phaser 3117 printer and an Asus RT-AC68U router that works as an AP. I connected the printer with the router via USB. When the router resets, the printer prints correctly but as soon as the PC and printer switch off and restart. The printer does not print until the router is restarted. Restarting the "lpd" itself does not help. Can you fix it somehow?
I temporarily solved the problem by killing the "lpd" process and running "p910nd" (/jffs/p910nd -f /dev/printers/lp0) from Tomato. She did it work properly.
Regards.

**Comment by RMerl** [comment]
I don't touch the printer server support code as I have no real way of testing it, since it depends on your specific router model.  Also most modern printer come with wifi support these days, so this is more of a legacy feature that Asus doesn't seem to devote any development resources anymore.
