### ISSUE TITLE
smart connect function problem.

### ISSUE THREAD

**Issue by yongw-pur** [RMerl/asuswrt-merlin#1566]
Hello,Master.I am a little bit confused about the smart connect function.
What is the specific function of  smart connect?
If the router has the same SSID between 2.4G and 5G, Can it switch between 2.4G and 5G according to the distance of router?
I will appreciate if you can answer me when you are free.
Thanks in advance！

**Comment by RMerl** [comment]
The issue tracker is only for development purposes.  If you need technical support or have a question, please use the support forums at https://www.snbforums.com/forums/asuswrt-official.51/ instead.
