### ISSUE TITLE
RT-AC68U Kernel Panic

### ISSUE THREAD

**Issue by eyezak** [RMerl/asuswrt-merlin#1572]
Jul 31 20:00:14 kernel: ctf: module license 'Proprietary' taints kernel.
Jul 31 20:00:14 kernel: Disabling lock debugging due to kernel taint
Jul 31 20:00:14 kernel: et_module_init: passivemode set to 0x0
Jul 31 20:00:14 kernel: et_module_init: txworkq set to 0x0
Jul 31 20:00:14 kernel: et_module_init: et_txq_thresh set to 0xce4
Jul 31 20:00:14 kernel: eth0: Broadcom BCM47XX 10/100/1000 Mbps Ethernet Controller 6.37.14.126 (r561982)
Jul 31 20:00:14 kernel: wl_module_init: passivemode set to 0x0
Jul 31 20:00:14 kernel: wl_module_init: igs set to 0x1
Jul 31 20:00:14 kernel: wl_module_init: txworkq set to 0x0
Jul 31 20:00:14 kernel: eth1: Broadcom BCM4360 802.11 Wireless Controller 6.37.14.126 (r561982)
Jul 31 20:00:14 kernel: eth2: Broadcom BCM4360 802.11 Wireless Controller 6.37.14.126 (r561982)
Jul 31 20:00:14 kernel: _ Reboot message ... _______________________________________________________
Jul 31 20:00:14 kernel: <4>Emergency Sync complete
Jul 31 20:00:14 kernel: <6>mod epilog takes 0�U�fies
Jul 31 20:00:14 kernel: <6>IDPfw: Exit IDPfw
Jul 31 20:00:14 kernel: <4>Stop the IPS/AppID engine...
Jul 31 20:00:14 kernel: <6>IDPfw: Exit chrdev /dev/idpfw with major 191
Jul 31 20:00:14 kernel: <7>[udb_exit:959] Free udb at cdeb7000
Jul 31 20:00:14 kernel: <7>[udb_exit:960] Free app at d2d96000
Jul 31 20:00:14 kernel: <7>[udb_exit:961] Free patrol table at d2db9000
Jul 31 20:00:14 kernel: <1>Unable to handle kernel NULL pointer dereference at virtual address 00000000
Jul 31 20:00:14 kernel: <1>pgd = cba50000
Jul 31 20:00:14 kernel: <1>[00000000] *pgd=9b89c031, *pte=00000000, *ppte=00000000
Jul 31 20:00:14 kernel: <0>Internal error: Oops: 17 [#1] PREEMPT SMP
Jul 31 20:00:14 kernel: <0>last sysfs file: /sys/module/bw_forward/parameters/dev_wan
Jul 31 20:00:14 kernel: <4>module:  tun	 bf01c000	 12274
Jul 31 20:00:14 kernel: <4>module:  wl	 bf7f5000	 3992315
Jul 31 20:00:14 kernel: <4>module:  ebtable_broute	 bf441000	 873
Jul 31 20:00:14 kernel: <4>module:  ebtable_filter	 bf02f000	 1061
Jul 31 20:00:14 kernel: <4>module:  ebtable_nat	 bf7f2000	 1056
Jul 31 20:00:14 kernel: <4>module:  ebtables	 bf7e9000	 15643
Jul 31 20:00:14 kernel: <4>module:  IDP	 bf72e000	 529190
Jul 31 20:00:14 kernel: <4>module:  nf_nat_sip	 bf727000	 5031
Jul 31 20:00:14 kernel: <4>module:  nf_conntrack_sip	 bf71e000	 15713
Jul 31 20:00:14 kernel: <4>module:  nf_nat_h323	 bf717000	 4761
Jul 31 20:00:14 kernel: <4>module:  nf_conntrack_h323	 bf709000	 33807
Jul 31 20:00:14 kernel: <4>module:  nf_nat_rtsp	 bf703000	 3202
Jul 31 20:00:14 kernel: <4>module:  nf_conntrack_rtsp	 bf6fd000	 4067
Jul 31 20:00:14 kernel: <4>module:  nf_nat_ftp	 bf6f7000	 1144
Jul 31 20:00:14 kernel: <4>module:  nf_conntrack_ftp	 bf6f0000	 4909
Jul 31 20:00:14 kernel: <4>module:  ip6table_mangle	 bf6ea000	 934
Jul 31 20:00:14 kernel: <4>module:  cdc_mbim	 bf6e4000	 3129
Jul 31 20:00:14 kernel: <4>module:  qmi_wwan	 bf6dd000	 5780
Jul 31 20:00:14 kernel: <4>module:  cdc_wdm	 bf6d6000	 7252
Jul 31 20:00:14 kernel: <4>module:  cdc_ncm	 bf6ce000	 8750
Jul 31 20:00:14 kernel: <4>module:  rndis_host	 bf6c7000	 4936
Jul 31 20:00:14 kernel: <4>module:  cdc_ether	 bf6c1000	 3187
Jul 31 20:00:14 kernel: <4>module:  asix	 bf6b9000	 10832
Jul 31 20:00:14 kernel: <4>module:  usbnet	 bf6b0000	 11161
Jul 31 20:00:14 kernel: <4>module:  mii	 bf6aa000	 3367
Jul 31 20:00:14 kernel: <4>module:  usblp	 bf6a2000	 10321
Jul 31 20:00:14 kernel: <4>module:  ohci_hcd	 bf698000	 17918
Jul 31 20:00:14 kernel: <4>module:  ehci_hcd	 bf68b000	 31565
Jul 31 20:00:14 kernel: <4>module:  xhci_hcd	 bf678000	 51124
Jul 31 20:00:14 kernel: <4>module:  thfsplus	 bf65c000	 81793
Jul 31 20:00:14 kernel: <4>module:  tntfs	 bf5e0000	 454497
Jul 31 20:00:14 kernel: <4>module:  tfat	 bf5a7000	 188546
Jul 31 20:00:14 kernel: <4>module:  ext2	 bf593000	 52776
Jul 31 20:00:14 kernel: <4>module:  ext4	 bf552000	 221674
Jul 31 20:00:14 kernel: <4>module:  crc16	 bf54c000	 1007
Jul 31 20:00:14 kernel: <4>module:  jbd2	 bf539000	 48993
Jul 31 20:00:14 kernel: <4>module:  ext3	 bf517000	 106409
Jul 31 20:00:14 kernel: <4>module:  jbd	 bf506000	 42367
Jul 31 20:00:14 kernel: <4>module:  mbcache	 bf4ff000	 4599
Jul 31 20:00:14 kernel: <4>module:  usb_storage	 bf4f0000	 34290
Jul 31 20:00:14 kernel: <4>module:  sg	 bf4e5000	 19855
Jul 31 20:00:14 kernel: <4>module:  sd_mod	 bf4d9000	 21983
Jul 31 20:00:14 kernel: <4>module:  scsi_wait_scan	 bf4d3000	 416
Jul 31 20:00:14 kernel: <4>module:  scsi_mod	 bf4ae000	 108738
Jul 31 20:00:14 kernel: <4>module:  usbcore	 bf48b000	 101810
Jul 31 20:00:14 kernel: <4>module:  ip6t_LOG	 bf484000	 4494
Jul 31 20:00:14 kernel: <4>module:  ip6table_filter	 bf47e000	 750
Jul 31 20:00:14 kernel: <4>module:  jffs2	 bf460000	 91274
Jul 31 20:00:14 kernel: <4>module:  zlib_deflate	 bf456000	 19489
Jul 31 20:00:14 kernel: <4>module:  nf_nat_pptp	 bf450000	 1602
Jul 31 20:00:14 kernel: <4>module:  nf_conntrack_pptp	 bf44a000	 3355
Jul 31 20:00:14 kernel: <4>module:  nf_nat_proto_gre	 bf444000	 887
Jul 31 20:00:14 kernel: <4>module:  nf_conntrack_proto_gre	 bf43e000	 3296
Jul 31 20:00:14 kernel: <4>module:  igs	 bf02a000	 11887
Jul 31 20:00:14 kernel: <4>module:  emf	 bf021000	 15225
Jul 31 20:00:14 kernel: <4>module:  et	 bf00a000	 61445
Jul 31 20:00:14 kernel: <4>module:  ctf	 bf000000	 20367
Jul 31 20:00:14 kernel: <4>Modules linked in: tun wl(P) ebtable_broute ebtable_filter ebtable_nat ebtables IDP(P-) nf_nat_sip nf_conntrack_sip nf_nat_h323 nf_conntrack_h323 nf_nat_rtsp nf_conntrack_rtsp nf_nat_ftp nf_conntrack_ftp ip6table_mangle cdc_mbim qmi_wwan cdc_wdm cdc_ncm rndis_host cdc_ether asix usbnet mii usblp ohci_hcd ehci_hcd xhci_hcd thfsplus tntfs(P) tfat(P) ext2 ext4 crc16 jbd2 ext3 jbd mbcache usb_storage sg sd_mod scsi_wait_scan scsi_mod usbcore ip6t_LOG ip6table_filter jffs2 zlib_def
Jul 31 20:00:14 kernel: <4>CPU: 0    Tainted: P             (2.6.36.4brcmarm #2)
Jul 31 20:00:14 kernel: <4>PC is at parse_ip6_header+0x1cb6c/0x1cf24 [IDP]
Jul 31 20:00:14 kernel: <4>LR is at devid_sig_destroy+0x1bc/0x21c [IDP]
Jul 31 20:00:14 kernel: <4>pc : [<bf775448>]    lr : [<bf7759bc>]    psr: a0000013
Jul 31 20:00:14 kernel: <4>sp : ccb35f00  ip : 00000000  fp : 00000000
Jul 31 20:00:14 kernel: <4>r10: 00000000  r9 : ccb34000  r8 : beb2bca8
Jul 31 20:00:14 kernel: <4>r7 : d0808000  r6 : cb69d360  r5 : cb69d340  r4 : cb69d328
Jul 31 20:00:14 kernel: <4>r3 : 00000000  r2 : 00000000  r1 : 9a000081  r0 : cb69d340
Jul 31 20:00:14 kernel: <4>Flags: NzCv  IRQs on  FIQs on  Mode SVC_32  ISA ARM  Segment user
Jul 31 20:00:14 kernel: <4>Control: 10c53c7d  Table: 9ba5004a  DAC: 00000015
Jul 31 20:00:14 kernel: <0>Process rmmod (pid: 4802, stack limit = 0xccb34270)
Jul 31 20:00:14 kernel: <0>Stack: (0xccb35f00 to 0xccb36000)
Jul 31 20:00:15 kernel: <0>5f00: cb69d328 d0808420 ccb34000 bf7759bc bf7847f0 bf784378 ccb34000 ccb35f44
Jul 31 20:00:15 kernel: <0>5f20: beb2bca8 bf7762f4 bf7847f0 bf738750 bf7847f0 bf730804 00000000 c008f27c
Jul 31 20:00:15 kernel: <0>5f40: cc82bd78 00504449 c82164a8 ccb34000 400f7000 ccb35f84 400f7000 00000001
Jul 31 20:00:15 kernel: <0>5f60: ccb34000 400f6000 cc90a640 beb2ba14 00005401 00000001 c003dc68 00b34000
Jul 31 20:00:15 kernel: <0>5f80: bf784378 00000880 ccb35f8c 00000000 401a23b0 00000880 beb2bca8 00000081
Jul 31 20:00:15 kernel: <0>5fa0: c003dc68 c003dac0 401a23b0 00000880 beb2bca8 00000880 00000b3c 00000000
Jul 31 20:00:15 kernel: <0>5fc0: 401a23b0 00000880 beb2bca8 00000081 000856f0 0000d05c beb2bde8 00000000
Jul 31 20:00:15 kernel: <0>5fe0: 4014974c beb2bc90 0001544c 40149758 20000010 beb2bca8 00000000 00000000
Jul 31 20:00:15 kernel: <4>[<bf775448>] (PC is at parse_ip6_header+0x1cb6c/0x1cf24 [IDP])
Jul 31 20:00:15 kernel: <4>[<bf775448>] (parse_ip6_header+0x1cb6c/0x1cf24 [IDP]) from [<bf7759bc>] (devid_sig_destroy+0x1bc/0x21c [IDP])
Jul 31 20:00:15 kernel: <4>[<bf7759bc>] (devid_sig_destroy+0x1bc/0x21c [IDP]) from [<bf7762f4>] (devid_exit+0x18/0x24 [IDP])
Jul 31 20:00:15 kernel: <4>[<bf7762f4>] (devid_exit+0x18/0x24 [IDP]) from [<bf738750>] (detector_remove+0x3c/0x4c [IDP])
Jul 31 20:00:15 kernel: <4>[<bf738750>] (detector_remove+0x3c/0x4c [IDP]) from [<bf730804>] �^Bsys_exit+0xac/0xc8 [IDP])
Jul 31 20:00:15 kernel: <4>[<bf730804>] (nk_sys_exit+0xac/0xc8 [IDP]) from [<c008f27c>] (sys_delete_module+0x16c/0x218)
Jul 31 20:00:15 kernel: <4>[<c008f27c>] (sys_delete_module+0x16c/0x218) from [<c003dac0>] (ret_fast_syscall+0x0/0x30)
Jul 31 20:00:15 kernel: <0>Code: e5902020 e1a05000 e1560002 0a000010 (e5924000) 
Jul 31 20:00:15 kernel: <4>---[ end trace fd3d84ab7ea301e6 ]---
Jul 31 20:00:15 kernel: <0>Kernel panic - not syncing: Fatal exception
Jul 31 20:00:15 kernel: <4>[<c0043ff8>] (unwind_backtrace+0x0/0xf8) from [<c02cb77c>] (panic+0x7c/0x1a8)
Jul 31 20:00:15 kernel: <4>[<c02cb77c>] (panic+0x7c/0x1a8) from [<c00416f0>] (die+0x1a4/0x1dc)
Jul 31 20:00:15 kernel: <4>[<c00416f0>] (die+0x1a4/0x1dc) from [<c004515c>] (__do_kernel_fault+0x6c/0x8c)
Jul 31 20:00:15 kernel: <4>[<c004515c>] (__do_kernel_fault+0x6c/0x8c) from [<c00452cc>] (do_page_fault+0x150/0x1ec)
Jul 31 20:00:15 kernel: <4>[<c00452cc>] (do_page_fault+0x150/0x1ec) from [<c003d3a4>] (do_DataAbort+0x30/0x9c)
Jul 31 20:00:15 kernel: <4>[<c003d3a4>] (do_DataAbort+0x30/0x9c) from [<c038682c>] (__dabt_svc+0x4c/0x60)
Jul 31 20:00:15 kernel: <4>Exception stack(0xccb35eb8 to 0xccb35f00)
Jul 31 20:00:15 kernel: <4>5ea0:                                                       cb69d340 9a000081
Jul 31 20:00:15 kernel: <4>5ec0: 00000000 00000000 cb69d328 cb69d340 cb69d360 d0808000 beb2bca8 ccb34000
Jul 31 20:00:15 kernel: <4>5ee0: 00000000 00000000 00000000 ccb35f00 bf7759bc bf775448 a0000013 ffffffff
Jul 31 20:00:15 kernel: <4>[<c038682c>] (__dabt_svc+0x4c/0x60) from [<bf775448>] (parse_ip6_header+0x1cb6c/0x1cf24 [IDP])
Jul 31 20:00:15 kernel: <4>[<bf775448>] (parse_ip6_header+0x1cb6c/0x1cf24 [IDP]) from [<bf7759bc>] (devid_sig_destroy+0x1bc/0x21c [IDP])
Jul 31 20:00:15 kernel: <4>[<bf7759bc>] (devid_sig_destroy+0x1bc/0x21c [IDP]) from [<bf7762f4>] (devid_exit+0x18/0x24 [IDP])
Jul 31 20:00:15 kernel: <4>[<bf7762f4>] (devid_exit+0x18/0x24 [IDP]) from [<bf738750>] (detector_remove+0x3c/0x4c [IDP])
Jul 31 20:00:15 kernel: <4>[<bf738750>] (detector_remove+0x3c/0x4c [IDP]) from [<bf730804>] (nk_sys_exit+0xac/0xc8 [IDP])
Jul 31 20:00:15 kernel: <4>[<bf730804>] (nk_sys_exit+0xac/0xc8 [IDP]) from [<c008f27c>] (sys_delete_module+0x16c/0x218)
Jul 31 20:00:15 kernel: <4>[<c008f27c>] (sys_delete_module+0x16c/0x218) from [<c003dac0>] (ret_fast_syscall+0x0/0x30)
Jul 31 20:00:15 kernel: <2>CPU0: stoppinace+0x0/0xf8) from [<c003d334>] 34>] (do_IPI+0x114/0x154) from [<c0386888>] (__irq_svc+0x48/0xe8to 0xc03c1fc0)
Jul 31 20:00:15 kernel: <4>1f60:                                                       c8215f80 cf919b00
Jul 31 20:00:15 kernel: <4>1f80: c03c1fc0 00000000 c03c01f 00000000 00000000 c03c1fc0 c003ebe4 c003ebe8 60000013 ffffffffrom [<00008084>] (0x8084)
Jul 31 20:00:15 kernel: <0>Rebooting in 3 seconds..

**Comment by RMerl** [comment]
Crash happened inside the Trend Micro module, which is outside of my control.
