### ISSUE TITLE
Merlin NAT loopback mode broken on 380.69 and 382.2_beta2

### ISSUE THREAD

**Issue by chrisballinger** [RMerl/asuswrt-merlin#1575]
Loopback works again when selecting ASUS mode.

**Comment by RMerl** [comment]
The loopback mode  isn't compatible with all configuration, that's why both options are available.  It's not a bug, just a technical compatibility limitation.

**Comment by chrisballinger** [comment]
Ah thank you! It seemed to stop working all of a sudden, possibly related to turning on Adaptive QoS.

**Comment by RMerl** [comment]
It's quite likely to be related indeed.  Adaptive QoS uses most of the packet mark bits for its own uses, which can conflict with the Merlin NAT loopback that also relies on packet marking.
