### ISSUE TITLE
Enable Monitor mode to capture management frames

### ISSUE THREAD

**Issue by sahilsharma1** [RMerl/asuswrt-merlin#1580]
I want to capture management frames in the router, so I have installed tcpdump by opkg. When I use `-I` option wtih tcpdump it says 

> That device does not support monitor mode

I have also tried `wl monitor 1` to put the device in monitor mode but no success. Please can you suggest a way to set mode to monitor?

**Comment by RMerl** [comment]
Wireless driver is closed source and outside of my control.
