### ISSUE TITLE
Disable Asusnat tunnel

### ISSUE THREAD

**Issue by garyfisher** [RMerl/asuswrt-merlin#1587]
![image](https://user-images.githubusercontent.com/285517/35436371-6d820bda-028e-11e8-8e1c-e191aeae32a4.png)

Hello, it's set to YES and saved. When restarting the router, returns the setting to NO. It does not save the setting to YES.

RT-N66U Firmware 380.69

https://github.com/RMerl/asuswrt-merlin/commit/5323501e548dfe417507fdd981d945f7d78822ba

**Comment by RMerl** [comment]
Upgrade to 380.69_2.
