### ISSUE TITLE
2fa support for web interace login

### ISSUE THREAD

**Issue by edgan** [RMerl/asuswrt-merlin#1588]
I would like to use Google Authenticator for 2fa to login to the web interface of my ASUS router. I have 2fa on pretty much everything, and why not my ASUS routers. Worst case I reset them from scratch to get around 2fa when you lose your Google Authentiactor device. For extra safety you could allow backup codes.

**Comment by unsynaps** [comment]
This might be difficult considering the router has no internal battery to keep time when its off.

**Comment by RMerl** [comment]
I have no plan of changing the login/authentication mechanism.
