### ISSUE TITLE
Download Master gone. Where is it?

### ISSUE THREAD

**Issue by oCCFANo** [RMerl/asuswrt-merlin#1591]
Just updated to 380.68, and the Download Master is not there.

Device: RT-AC56U

![firefox_screenshot_2018-02-02t09-49-57 769z](https://user-images.githubusercontent.com/32940376/35727175-3f532694-07d5-11e8-800b-16aa3cde4150.png)

**Comment by Utyff** [comment]
Did you insert USB flash?

**Comment by unsynaps** [comment]
380.69_2

Its there for me.

**Comment by RMerl** [comment]
You are not running my firmware, you are running a variant developped by the Koolshare deves.  Ask them.
