### ISSUE TITLE
Do not save the syslog to the jffs partition.

### ISSUE THREAD

**Issue by maranda** [RMerl/asuswrt-merlin#519]
Before getting to the point, as a note, the first difference I noticed between the Stock FW and Merlin on the AC56U, was the jffs partition size being 92 MBs on stock and 32 MBs on Merlin.

Forward, I know it's opinable but writing to the router's NAND flash drive still should be avoided in any case, for example my logs reached quite a bit more then a few "KBs a day" (due to issues with ipv6 6in4 tunnels). Reading some of related posts I'm not sure why the engineers at Asus considered that to be "a safe enough practice" (I almost had a heartache when I noticed), irregardless of how many write cycles it'll take before a wearoff happens, by doing frequent writes you're still tapping on the life expectancy of the device.

There should be at least a configuration option to disable the writing of syslog on the jffs partition which possibly should be enabled by default.

**Comment by blbradley** [comment]
@RMerl I appreciate your thorough research and response. Happy to know I can use my RT-AC66U for a lifetime of writes. I was concerned about the DHCP client list writes wearing out the flash. But, no longer!
