### ISSUE TITLE
Allow different SSH port on WAN side

### ISSUE THREAD

**Issue by zeroepoch** [RMerl/asuswrt-merlin#689]
If you can create a new nvram variable such as `sshd_wan_port` then it shouldn't be too difficult to support a different port for SSH on the WAN side such as how Tomato USB does.  You just need to start dropbear with an additional -p option and then create the firewall rule as you already have but using this new variable.  I think the logic for the dropbear command could be something like the following "pseudo" code:

```
dropbear_cmd = "dropbear ";
...
lan_port  = nvram_get_int("sshd_port")
wan_port = nvram_get_int("sshd_wan_port")

if nvram_match("sshd_wan", "1")) && wan_port != lan_port then
  dropbear_cmd += "-p ${wan_port}"
end
```

Then for the IP tables rule check if `sshd_wan_port` is defined and if not just use `sshd_port`.

**Comment by jauling** [comment]
possible to revisit this issue?
