### ISSUE TITLE
VPN client blocks FTP and VPN connections

### ISSUE THREAD

**Issue by jhallenb** [RMerl/asuswrt-merlin#924]
When enable the router to act as a VPN client (activate a VPN tunnel) so all computers on the LAN goes through the VPN connection (PPTP), then accessing the router's USB share over FTP is not working. Also if one enable the router to act as an OpenVPN server it is not possible to connect to the router over VPN if the "client" tunnel is active.

Seems like a bug, all incomming connections like FTP and OpenVPN seems to be routed out over the PPTP tunnel hence does no longer work. I would have expected at least to have the choice of allowing FTP and OpenVPN server (and other services) simultaniously with having the router using a VPN tunnel (just like HTTP and HTTPS connections to the router still works even when the VPN tunnel is activated).

**Comment by RMerl** [comment]
Asus recently tightened security so that various daemons will now only listens for connections to the LAN's subnet.  Is your VPN within the same subnet as your LAN, or a different one?

**Comment by jhallenb** [comment]
Router is at 192.168.1.1
Router is connected to ISP using direct cable.
I am using a VPN provider, only PPTP, and enable a tunnel to the VPN provider using the PPTP client in the router. So all LAN computers are reaching internet through the tunnel. 

In this configuration nobode outside my LAN can reach the USB share over FTP.
If I setup an OpenVPN server in the router I cannot connect to it from outside my LAN as long as the PPTP tunnel is activated. The OpenVPN server I usually setup to be on 192.168.2.1/24

**Comment by RMerl** [comment]
This is a known technical limitation.  If you have a VPN client set to forward all traffic through the tunnel, then inbound connection to the router won't work properly due to a routing conflict - it will try to forward the outbound traffic through the tunnel rather than through the WAN interface.

Proper workaround is to use OpenVPN instead of PPTP, and setup policy-based routing, with a rule forcing all traffic to the router's IP to go through the WAN interface rather than the tunnel.

**Comment by jhallenb** [comment]
Okay, a known technical limitation, but could it be resolved for PPTP?

For OpenVPN and policy routing, wouldn't I need to know the public IP to the router then? My ISP provides a dynamic IP...so that is not a solution unless one can anable this automatically for the current public WAN IP. I have seen no way to solve this, but maybe I have missed something?

**Comment by RMerl** [comment]
Please head up to the support forums if you need help.
