### ISSUE TITLE
Upload speed capped when Merlin was installed

### ISSUE THREAD

**Issue by inquam** [RMerl/asuswrt-merlin#926]
I have Fiber in my house and had my Asus ac68u connected to the fiber box. With the stock firmware I got about 245MBit/sec down and 247MBit/sec up. Since my subscription is for 250/250 it's quite close.

I then installed Merlin 380.59 and after that I still get around 240MBit/sec down, but my up speed seems to be stuck at ~145MBit/sec.

If I connect a computer directly to the fiber box I get my original speeds back, so the issue seems to be with the router and it started when I installed Merlin. Any ideas on what the cause could be?

**Comment by RMerl** [comment]
Please use the forums for support questions, this tracker is for bug reports.

**Comment by inquam** [comment]
Ahhh sorry... But I have not been able to find a forum :)

**Comment by stevek123** [comment]
http://www.snbforums.com/forums/asuswrt-merlin.42/
