### ISSUE TITLE
No way to change Language if router CFE has JP for region

### ISSUE THREAD

**Issue by omniwired** [RMerl/asuswrt-merlin#929]
![image](https://cloud.githubusercontent.com/assets/322761/15913063/eba341e8-2e12-11e6-98bd-05bb88f993a2.png)

**Comment by RMerl** [comment]
I've seen someone report the same problem with Asus's stock firmware, and he was also using Japanese.  I suspect it's related to that, as the language selector appears normally with other languages.

**Comment by RMerl** [comment]
Asus is actually doing it on purpose, hiding the language selector for the JP region:

https://github.com/RMerl/asuswrt-merlin/blob/master/release/src/router/httpd/web.c#L6687

Anyone knows why that might be the case?  Is there some odd Japanese law enforcing that kind of behavior?

**Comment by omniwired** [comment]
maybe to aid their uses, there are no laws banning to use english in products....

Also this router came with multi lingual UI.

**Comment by omniwired** [comment]
Thanks so much for your help and your amazing work in Merlin, I really love it.

For the time being I will try to downgrade the firmware to 380.57 that had English support.

Maybe we can just get rid of that IF, since there isn't a good reason that is happening.

I could make a PR if you wish.

**Comment by RMerl** [comment]
Thanks, but I'll just give it some time to see if anyone can come up with a good explanation, otherwise I will take care of it.

**Comment by omniwired** [comment]
saw your changes, thanks for the fix! :+1:

**Comment by songxinjing** [comment]
I have already flashed version 380.60 alpha 3, and I have saw the language selector, thanks for your work. **But**, I haven't changed the language, If I change the language to English or others, it remains Japanese.

**Comment by RMerl** [comment]
Found additional code where Asus were enforcing Japanese language for routers with a JP region code.

**Comment by nudls** [comment]
Hello, I've upgraded my rt-ac87u to latest firmware and now all gui in japanese. Applying RT-AC87U_380.66_alpha2 will help me get english back?
thanks
