### ISSUE TITLE
Hide passwords by default on the VPN server pages

### ISSUE THREAD

**Issue by RMerl** [RMerl/asuswrt-merlin#934]
If you configure any users on the VPN server pages, these are shown by default, which can be a security problem if you just want to access that page to create a user while someone else is watching.

Hide the passwords by default, with a checkbox allowing to reveal it, a bit similar to what is used for the router password on the Administration page.

**Comment by pepeEL** [comment]
Any plan when will be this add ?

**Comment by RMerl** [comment]
Not at this time, no.

**Comment by pepeEL** [comment]
Why :) ?

**Comment by RMerl** [comment]
Because there's one single developer who already has to do **everything** on his own.  So at this time, I don't know when it will be added.  Time is a limited resource, and I have a personal life outside of this project.

**Comment by pepeEL** [comment]
Ahh Ok sorry :) But thanks for all you good job :)
