### ISSUE TITLE
L2TP VPN Server support

### ISSUE THREAD

**Issue by hungyc** [RMerl/asuswrt-merlin#945]
Start from iOS 10, Apple has cancelled PPTP connectivity, is it possible to support L2TP VPN Server?

**Comment by RMerl** [comment]
No plan to.  OpenVPN is the recommended VPN technology for Asuswrt.

**Comment by davericher** [comment]
If thats the case this will be my last iphone

**Comment by iMocW** [comment]
OpenVPN Client didn't update for a long time.Even not support iOS 8.

**Comment by unsynaps** [comment]
OpenVPN client works fine in iOS. Using it now in 9.3.2 (current as of this post).

**Comment by iMocW** [comment]
Official Client..??I tried yesterday and it just FC right after open it.

**Comment by unsynaps** [comment]
https://itunes.apple.com/us/app/openvpn-connect/id590379981?mt=8

Some people are ranting and raving saying it does not work but it works without issue for me on the latest Merlin firmware using the config files it spits out.

**Comment by averkiev** [comment]
I'm using the official OpenVPN client on iOS10. It also worked just fine on iOS9. Still I would rather not to rely on a third-party solution for my VPN needs and would much prefer native support of L2TP in router firmware.
