### ISSUE TITLE
Dual Wan problem

### ISSUE THREAD

**Issue by trtk** [RMerl/asuswrt-merlin#947]
Hi, i don't know it can be a ISP problem too. Currently i try to use dual wan but is i turn it on on the main connection can't connect. The secondary is fine. A main is a PPPOE connection, the secondary is a simple auto ip. And both IPV6 capable. Turning off the ipv6 not helping. Thanks for your all work, these firmware's is awesome.

**Comment by RMerl** [comment]
Please use the support forums for support requests.
