### ISSUE TITLE
Per device IP broken

### ISSUE THREAD

**Issue by d2dyno** [RMerl/asuswrt-merlin#948]
On XWRT for Netgear R7000 v380.59_0, when I check the box for "Enable IPTraffic (per IP monitoring)" under Tools>Other Settings, then apply the settings, the router goes into a bootloop. This has been confirmed by one other user on the main thread at linksysinfo.org.

**Comment by RMerl** [comment]
I suggest you contact the developer of the fork you are using.  This repository is only for Asuswrt-Merlin, not for any of its forks.
