### ISSUE TITLE
After last firmware update(on official ASUS firmware to, may be asus bug) incorrectly working SIP

### ISSUE THREAD

**Issue by PRIHLOP** [RMerl/asuswrt-merlin#951]
After last firmware update 380.59 (on official ASUS firmware 3.0.0.4.380_3264 to, may be asus bug) incorrectly working RTSP Passthrough and may be SIP Passthrough.

This bug catched on RT-AC66U and RT-AC68U.

**Comment by RMerl** [comment]
Can you be more specific?  Asuswrt and Asuswrt-Merlin handle the passthrough settings differently.

**Comment by PRIHLOP** [comment]
This bug true on RT-AC68U with Asuswrt-Merlin, and also true on RT-AC66U with Asuswrt. May be new binaries made this bug?

**Comment by RMerl** [comment]
Myself and quite a few other users are using ATAs without any problem with 380.59.  I use a Cisco SP112 myself.

I recommend heading to the forums for troubleshooting.  While Asus recently changed things so that disabling passthrough will also block port 5060, that is not the case with my firmware.

**Comment by PRIHLOP** [comment]
But you may fix it?
Bug is no dial tone for outgoing calls.

Thank you for your patience and development of this firmware.

**Comment by RMerl** [comment]
If it works for everyone else, then the issue more likely to be with your configuration than with the firmware.

**Comment by PRIHLOP** [comment]
May be you're right. If the problem is not repeat at others users, then you are right.
