### ISSUE TITLE
Traffic Analyzer - Always Shows Monthly Top 5 Clients, regardless of whether Daily or Weekly is Selected

### ISSUE THREAD

**Issue by shauno100** [RMerl/asuswrt-merlin#954]
I don't know if this is an Asus bug or if  you can fix it. Its only a minor cosmetic issue. When you go to the Traffic Analyzer and change the graph display to either weekly or Daily the graph updates correctly and the label at the bottom briefly displays correctly (i.e Daily Top 5 Clients, Weekly Top 5 Clients) but then always changes back to Monthly Top 5 clients. I vaguely recall reading somewhere where other users reported it but nothing seemed to be done to fix. Unless this is how its meant to be and is by design.

**Comment by RMerl** [comment]
That page is a bit of a mess, and I'm not even sure myself how it's supposed to work, so I'd rather not touch it.
