### ISSUE TITLE
[FEATURE REQ] Allow broader range for Wireless - Roaming assistant

### ISSUE THREAD

**Issue by robert-alfaro** [RMerl/asuswrt-merlin#956]
Configuration of Wireless - Professional - Roaming assistant is limited to no higher than -70dBm.  For example, it'd be great to adjust this value to -50dBm on an RT-AC68U or RT-AC56U acting as a wireless repeater.

**Comment by RMerl** [comment]
Duplicate #932.

Already implemented in commit https://github.com/RMerl/asuswrt-merlin/commit/4db5dd7c0df3614ab244752ca34bb72dde068d30 .

**Comment by robert-alfaro** [comment]
Sweet thanks! Sorry for the dup.
