### ISSUE TITLE
Support ASUS RT-AC88U Firmware version 3.0.0.4.380.3341

### ISSUE THREAD

**Issue by henryj** [RMerl/asuswrt-merlin#957]
So from the official description:

> ASUS has been dedicated to cooperate with third party developers to come up with more innovative features. 
> To comply with regulatory amendments, we have modified firmware verification rule to ensure better firmware quality. 
> This version is not compatible with all previously released ASUS firmware and uncertified third party firmware.

Wondering if we're gonna support the new rule soon in the coming release?

**Comment by RMerl** [comment]
http://www.snbforums.com/threads/important-asuswrt-merlin-380-59-and-older-not-compatible-with-asus-3-0-0-4-380_3000-or-newer.32962/

**Comment by henryj** [comment]
Great. So the up coming 380.60 release will fix this. I guess we can keep this issue open till then. 

(Off topic, seems that forum is not accessible from Australia? I have to jump on my US VPN to see that thread...)

**Comment by RMerl** [comment]
SNB experienced some stability issues these past few days, that might be why.  Otherwise, it could be that your IP is blacklisted by Cloudflare.

I know of at least one regular who's also from Australia and doesn't seem to have any issue.

**Comment by RMerl** [comment]
Here's the official explanation of the recent SNB problems:

**Comment by RMerl** [comment]
Here's the official explanation regarding the SNB problems of late:

http://www.snbforums.com/threads/is-something-wrong-with-the-site.33399/

Email the site owner with your info if you still have problems accessing it.
