### ISSUE TITLE
pre-mount does not hold boot sequence

### ISSUE THREAD

**Issue by k-emil** [RMerl/asuswrt-merlin#962]
pre-mount running lengthy e2fsck does not prevent the system from starting.
Log:
Aug  1 02:00:06 syslogd started: BusyBox v1.20.2
Aug  1 02:00:06 kernel: klogd started: BusyBox v1.20.2 (2016-05-10 11:44:43 EDT)
Aug  1 02:00:06 kernel: start_kernel
Aug  1 02:00:06 kernel: Linux version 2.6.22.19 (root@asus) (gcc version 4.2.3) #1 Tue May 10 11:45:15 EDT 2016
Aug  1 02:00:06 kernel: CPU revision is: 00019749
Aug  1 02:00:06 kernel: Determined physical RAM map:
Aug  1 02:00:06 kernel:  memory: 07fff000 @ 00000000 (usable)
Aug  1 02:00:06 kernel:  memory: 08000000 @ 87fff000 (usable)
Aug  1 02:00:06 kernel: Built 1 zonelists.  Total pages: 585216
Aug  1 02:00:06 kernel: Kernel command line: root=/dev/mtdblock2 noinitrd console=ttyS0,115200
Aug  1 02:00:06 kernel: Primary instruction cache 32kB, physically tagged, 4-way, linesize 32 bytes.
Aug  1 02:00:06 kernel: Primary data cache 32kB, 4-way, linesize 32 bytes.
Aug  1 02:00:06 kernel: Synthesized TLB refill handler (20 instructions).
Aug  1 02:00:06 kernel: Synthesized TLB load handler fastpath (32 instructions).
Aug  1 02:00:06 kernel: Synthesized TLB store handler fastpath (32 instructions).
Aug  1 02:00:06 kernel: Synthesized TLB modify handler fastpath (31 instructions).
Aug  1 02:00:06 kernel: PID hash table entries: 2048 (order: 11, 8192 bytes)
Aug  1 02:00:06 kernel: CPU: BCM5300 rev 1 pkg 0 at 600 MHz
Aug  1 02:00:06 kernel: Using 300.000 MHz high precision timer.
Aug  1 02:00:06 kernel: console [ttyS0] enabled
Aug  1 02:00:06 kernel: Dentry cache hash table entries: 65536 (order: 6, 262144 bytes)
Aug  1 02:00:06 kernel: Inode-cache hash table entries: 32768 (order: 5, 131072 bytes)
Aug  1 02:00:06 kernel: Memory: 238608k/131068k available (2610k kernel code, 22664k reserved, 517k data, 196k init, 131072k highmem)
Aug  1 02:00:06 kernel: PCI: Enabling device 0000:01:00.1 (0004 -> 0006)
Aug  1 02:00:06 kernel: PCI: Fixing up bus 1
Aug  1 02:00:06 kernel: PCI/PCIe coreunit 1 is set to bus 2.
Aug  1 02:00:06 kernel: PCI: Fixing up bridge
Aug  1 02:00:06 kernel: PCI: Fixing up bridge
Aug  1 02:00:06 kernel: PCI: Enabling device 0000:02:00.1 (0004 -> 0006)
Aug  1 02:00:06 kernel: PCI: Fixing up bus 2
Aug  1 02:00:06 kernel: NET: Registered protocol family 2
Aug  1 02:00:06 kernel: Time: MIPS clocksource has been installed.
Aug  1 02:00:06 kernel: IP route cache hash table entries: 4096 (order: 2, 16384 bytes)
Aug  1 02:00:06 kernel: TCP established hash table entries: 16384 (order: 5, 131072 bytes)
Aug  1 02:00:06 kernel: TCP bind hash table entries: 16384 (order: 4, 65536 bytes)
Aug  1 02:00:06 kernel: TCP: Hash tables configured (established 16384 bind 16384)
Aug  1 02:00:06 kernel: TCP reno registered
Aug  1 02:00:06 kernel: highmem bounce pool size: 64 pages
Aug  1 02:00:06 kernel: squashfs: version 3.2-r2 (2007/01/15) Phillip Lougher
Aug  1 02:00:06 kernel: io scheduler noop registered (default)
Aug  1 02:00:06 kernel: HDLC line discipline: version $Revision: 4.8 $, maxframe=4096
Aug  1 02:00:06 kernel: N_HDLC line discipline registered.
Aug  1 02:00:06 kernel: Serial: 8250/16550 driver $Revision: 1.90 $ 4 ports, IRQ sharing disabled
Aug  1 02:00:06 kernel: serial8250: ttyS0 at MMIO 0xb8000300 (irq = 8) is a 16550A
Aug  1 02:00:06 kernel: serial8250: ttyS1 at MMIO 0xb8000400 (irq = 8) is a 16550A
Aug  1 02:00:06 kernel: PPP generic driver version 2.4.2
Aug  1 02:00:06 kernel: MPPE/MPPC encryption/compression module registered
Aug  1 02:00:06 kernel: NET: Registered protocol family 24
Aug  1 02:00:06 kernel: PPPoL2TP kernel driver, V0.18.3
Aug  1 02:00:06 kernel: PPTP driver version 0.8.5
Aug  1 02:00:06 kernel: Physically mapped flash: Found 1 x16 devices at 0x0 in 16-bit bank
Aug  1 02:00:06 kernel:  Amd/Fujitsu Extended Query Table at 0x0040
Aug  1 02:00:06 kernel: Enabling Spansion 65nm mode, writesize = 512 bytes
Aug  1 02:00:06 kernel: Physically mapped flash: CFI does not contain boot bank location. Assuming top.
Aug  1 02:00:06 kernel: number of CFI chips: 1
Aug  1 02:00:06 kernel: cfi_cmdset_0002: Disabling erase-suspend-program due to code brokenness.
Aug  1 02:00:06 kernel: Flash device: 0x2000000 at 0x1c000000
Aug  1 02:00:06 kernel: Creating 5 MTD partitions on "Physically mapped flash":
Aug  1 02:00:06 kernel: 0x00000000-0x00040000 : "pmon"
Aug  1 02:00:06 kernel: 0x00040000-0x01fe0000 : "linux"
Aug  1 02:00:06 kernel: 0x00176990-0x017a0000 : "rootfs"
Aug  1 02:00:06 kernel: 0x01fe0000-0x02000000 : "nvram"
Aug  1 02:00:06 kernel: 0x017e0000-0x01fe0000 : "jffs2"
Aug  1 02:00:06 kernel: Found an  serial flash with 0 0KB blocks; total size 0MB
Aug  1 02:00:06 kernel: sflash: found no supported devices
Aug  1 02:00:06 kernel: dev_nvram_init: _nvram_init
Aug  1 02:00:06 kernel: sdhci: Secure Digital Host Controller Interface driver
Aug  1 02:00:06 kernel: sdhci: Copyright(c) Pierre Ossman
Aug  1 02:00:06 kernel: u32 classifier
Aug  1 02:00:06 kernel:     OLD policer on 
Aug  1 02:00:06 kernel: Netfilter messages via NETLINK v0.30.
Aug  1 02:00:06 kernel: nf_conntrack version 0.5.0 (2048 buckets, 16384 max)
Aug  1 02:00:06 kernel: ip_tables: (C) 2000-2006 Netfilter Core Team
Aug  1 02:00:06 kernel: net/ipv4/netfilter/tomato_ct.c [May 10 2016 11:45:15]
Aug  1 02:00:06 kernel: ipt_account 0.1.21 : Piotr Gasidlo <quaker@barbara.eu.org>, http://code.google.com/p/ipt-account/
Aug  1 02:00:06 kernel: NET: Registered protocol family 1
Aug  1 02:00:06 kernel: NET: Registered protocol family 10
Aug  1 02:00:07 kernel: ip6_tables: (C) 2000-2006 Netfilter Core Team
Aug  1 02:00:07 kernel: NET: Registered protocol family 17
Aug  1 02:00:07 kernel: 802.1Q VLAN Support v1.8 Ben Greear <greearb@candelatech.com>
Aug  1 02:00:07 kernel: All bugs added by David S. Miller <davem@redhat.com>
Aug  1 02:00:07 kernel: VFS: Mounted root (squashfs filesystem) readonly.
Aug  1 02:00:07 kernel: Freeing unused kernel memory: 196k freed
Aug  1 02:00:07 kernel: Warning: unable to open an initial console.
Aug  1 02:00:07 kernel: Algorithmics/MIPS FPU Emulator v1.5
Aug  1 02:00:07 stop_nat_rules: apply the redirect_rules!
Aug  1 02:00:07 kernel: et: module license 'Proprietary' taints kernel.
Aug  1 02:00:07 kernel: et_module_init: passivemode set to 0x0
Aug  1 02:00:07 kernel: et_module_init: et_txq_thresh set to 0x400
Aug  1 02:00:07 kernel: bcm_robo_enable_switch: EEE is disabled
Aug  1 02:00:07 kernel: eth0: Broadcom BCM47XX 10/100/1000 Mbps Ethernet Controller 6.30.163.2002 (r382208)
Aug  1 02:00:07 kernel: wl_module_init: passivemode set to 0x0
Aug  1 02:00:07 kernel: PCI: Enabling device 0000:01:01.0 (0000 -> 0002)
Aug  1 02:00:07 kernel: eth1: Broadcom BCM4331 802.11 Wireless Controller 6.30.163.2002 (r382208)
Aug  1 02:00:07 kernel: PCI: Enabling device 0000:02:01.0 (0000 -> 0002)
Aug  1 02:00:07 kernel: eth2: Broadcom BCM4331 802.11 Wireless Controller 6.30.163.2002 (r382208)
Aug  1 02:00:07 kernel: JFFS2 version 2.2. (NAND) © 2001-2006 Red Hat, Inc.
Aug  1 02:00:07 kernel: br0: starting userspace STP failed, staring kernel STP
Aug  1 02:00:07 dropbear[232]: Running in background
Aug  1 02:00:07 kernel: vlan1: dev_set_allmulti(master, 1)
Aug  1 02:00:07 kernel: vlan1: dev_set_promiscuity(master, 1)
Aug  1 02:00:07 kernel: device eth0 entered promiscuous mode
Aug  1 02:00:07 kernel: device vlan1 entered promiscuous mode
Aug  1 02:00:07 kernel: device eth1 entered promiscuous mode
Aug  1 02:00:07 kernel: device eth2 entered promiscuous mode
Aug  1 02:00:07 kernel: device wl0.1 entered promiscuous mode
Aug  1 02:00:07 kernel: br0: port 4(wl0.1) entering listening state
Aug  1 02:00:07 kernel: br0: port 3(eth2) entering listening state
Aug  1 02:00:07 kernel: br0: port 2(eth1) entering listening state
Aug  1 02:00:07 kernel: br0: port 1(vlan1) entering listening state
Aug  1 02:00:07 kernel: br0: port 4(wl0.1) entering learning state
Aug  1 02:00:07 kernel: br0: port 3(eth2) entering learning state
Aug  1 02:00:07 kernel: br0: port 2(eth1) entering learning state
Aug  1 02:00:07 kernel: br0: port 1(vlan1) entering learning state
Aug  1 02:00:07 kernel: br0: topology change detected, propagating
Aug  1 02:00:07 kernel: br0: port 4(wl0.1) entering forwarding state
Aug  1 02:00:07 kernel: br0: topology change detected, propagating
Aug  1 02:00:07 kernel: br0: port 3(eth2) entering forwarding state
Aug  1 02:00:07 kernel: br0: topology change detected, propagating
Aug  1 02:00:07 kernel: br0: port 2(eth1) entering forwarding state
Aug  1 02:00:07 kernel: br0: topology change detected, propagating
Aug  1 02:00:07 kernel: br0: port 1(vlan1) entering forwarding state
Aug  1 02:00:11 dnsmasq[245]: started, version 2.76-g0007ee9 cachesize 1500
Aug  1 02:00:11 dnsmasq[245]: warning: interface ppp1* does not currently exist
Aug  1 02:00:11 dnsmasq[245]: asynchronous logging enabled, queue limit is 5 messages
Aug  1 02:00:11 dnsmasq-dhcp[245]: DHCP, IP range 192.168.200.192 -- 192.168.200.253, lease time 10m
Aug  1 02:00:11 dnsmasq[245]: using local addresses only for domain wl.ekrotech.com
Aug  1 02:00:11 dnsmasq[245]: read /etc/hosts - 5 addresses
Aug  1 02:00:11 dnsmasq[245]: read /etc/hosts.dnsmasq - 1 addresses
Aug  1 02:00:11 dnsmasq-dhcp[245]: read /etc/ethers - 1 addresses
Aug  1 02:00:11 dnsmasq[245]: using local addresses only for domain wl.ekrotech.com
Aug  1 02:00:11 RT-N66U: start httpd - SSL
Aug  1 02:00:11 syslog: Generating SSL certificate...
Aug  1 02:00:11 crond[249]: crond: crond (busybox 1.20.2) started, log level 8
Aug  1 02:00:13 disk monitor: be idle
Aug  1 02:00:14 start_nat_rules: apply the nat_rules(/tmp/nat_rules_eth0_eth0)!
Aug  1 02:00:15 kernel: nf_conntrack_rtsp v0.6.21 loading
Aug  1 02:00:15 kernel: nf_nat_rtsp v0.6.21 loading
Aug  1 02:00:15 dnsmasq[245]: read /etc/hosts - 5 addresses
Aug  1 02:00:15 dnsmasq[245]: read /etc/hosts.dnsmasq - 1 addresses
Aug  1 02:00:15 dnsmasq-dhcp[245]: read /etc/ethers - 1 addresses
Aug  1 02:00:15 dnsmasq[245]: using local addresses only for domain wl.ekrotech.com
Aug  1 02:00:15 dnsmasq[245]: using nameserver 195.187.156.13#53
Aug  1 02:00:15 dnsmasq[245]: using nameserver 87.204.204.204#53
Aug  1 02:00:16 wan: finish adding multi routes
Aug  1 02:00:16 WAN Connection: WAN was restored.
Aug  1 02:00:16 ntp: start NTP update
Jul  4 10:11:00 rc_service: ntp 343:notify_rc restart_upnp
Jul  4 10:11:01 kernel: tun: Universal TUN/TAP device driver, 1.6
Jul  4 10:11:01 kernel: tun: (C) 1999-2004 Max Krasnyansky <maxk@qualcomm.com>
Jul  4 10:11:01 kernel: device tap22 entered promiscuous mode
Jul  4 10:11:01 kernel: br0: port 5(tap22) entering listening state
Jul  4 10:11:01 kernel: br0: port 5(tap22) entering learning state
Jul  4 10:11:01 kernel: br0: topology change detected, propagating
Jul  4 10:11:01 kernel: br0: port 5(tap22) entering forwarding state
Jul  4 10:11:03 openvpn[364]: OpenVPN 2.3.10 mipsel-unknown-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [MH] [IPv6] built on May 10 2016
Jul  4 10:11:03 openvpn[364]: library versions: OpenSSL 1.0.2h  3 May 2016, LZO 2.08
Jul  4 10:11:03 openvpn[366]: Insufficient key material or header text not found in file 'static.key' (0/128/256 bytes found/min/max)
Jul  4 10:11:03 openvpn[366]: Exiting due to fatal error
Jul  4 10:11:03 openvpn-routing: Refreshing policy rules for client 1
Jul  4 10:11:04 openvpn-routing: Allow WAN access to all VPN clients
Jul  4 10:11:04 openvpn-routing: Refreshing policy rules for client 2
Jul  4 10:11:04 openvpn-routing: Allow WAN access to all VPN clients
Jul  4 10:11:04 openvpn-routing: Refreshing policy rules for client 3
Jul  4 10:11:04 openvpn-routing: Allow WAN access to all VPN clients
Jul  4 10:11:04 openvpn-routing: Refreshing policy rules for client 4
Jul  4 10:11:04 openvpn-routing: Allow WAN access to all VPN clients
Jul  4 10:11:04 openvpn-routing: Refreshing policy rules for client 5
Jul  4 10:11:04 openvpn-routing: Allow WAN access to all VPN clients
Jul  4 10:11:04 kernel: usbcore: registered new interface driver usbfs
Jul  4 10:11:04 kernel: usbcore: registered new interface driver hub
Jul  4 10:11:04 kernel: usbcore: registered new device driver usb
Jul  4 10:11:04 syslog: module ledtrig-usbdev not found in modules.dep
Jul  4 10:11:04 syslog: module leds-usb not found in modules.dep
Jul  4 10:11:04 kernel: SCSI subsystem initialized
Jul  4 10:11:04 kernel: Initializing USB Mass Storage driver...
Jul  4 10:11:04 kernel: usbcore: registered new interface driver usb-storage
Jul  4 10:11:04 kernel: USB Mass Storage support registered.
Jul  4 10:11:05 kernel: ufsd: driver (8.6 U86_r187446_b122, LBD=ON, acl, ioctl, rwm, ws, sd) loaded at c029e000
Jul  4 10:11:05 kernel: NTFS (with native replay) support included
Jul  4 10:11:05 kernel: optimized: speed
Jul  4 10:11:05 kernel: Build_for__asus_n66u_2011-10-27_U86_r187446_b122
Jul  4 10:11:05 kernel: ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
Jul  4 10:11:05 kernel: ehci_hcd 0000:00:04.1: EHCI Host Controller
Jul  4 10:11:05 kernel: ehci_hcd 0000:00:04.1: new USB bus registered, assigned bus number 1
Jul  4 10:11:05 kernel: ehci_hcd 0000:00:04.1: EHCI Fastpath: New EHCI driver starting
Jul  4 10:11:05 kernel: ehci_hcd 0000:00:04.1: irq 6, io mem 0x18004000
Jul  4 10:11:05 kernel: ehci_hcd 0000:00:04.1: USB 0.0 started, EHCI 1.00
Jul  4 10:11:05 kernel: usb usb1: configuration #1 chosen from 1 choice
Jul  4 10:11:05 kernel: hub 1-0:1.0: USB hub found
Jul  4 10:11:05 kernel: hub 1-0:1.0: 2 ports detected
Jul  4 10:11:05 kernel: ohci_hcd: USB 1.1 'Open' Host Controller (OHCI) Driver
Jul  4 10:11:05 kernel: ohci_hcd 0000:00:04.0: OHCI Host Controller
Jul  4 10:11:05 kernel: ohci_hcd 0000:00:04.0: new USB bus registered, assigned bus number 2
Jul  4 10:11:05 kernel: ohci_hcd 0000:00:04.0: irq 6, io mem 0x18009000
Jul  4 10:11:05 kernel: usb usb2: configuration #1 chosen from 1 choice
Jul  4 10:11:05 kernel: hub 2-0:1.0: USB hub found
Jul  4 10:11:05 kernel: hub 2-0:1.0: 2 ports detected
Jul  4 10:11:05 kernel: usbcore: registered new interface driver usblp
Jul  4 10:11:05 kernel: drivers/usb/class/usblp.c: v0.13: USB Printer Device Class driver
Jul  4 10:11:05 kernel: usbcore: registered new interface driver asix
Jul  4 10:11:05 kernel: usb 1-1: new high speed USB device using ehci_hcd and address 2
Jul  4 10:11:05 kernel: usb 1-1: configuration #1 chosen from 1 choice
Jul  4 10:11:05 kernel: hub 1-1:1.0: USB hub found
Jul  4 10:11:05 kernel: hub 1-1:1.0: 4 ports detected
Jul  4 10:11:05 kernel: usbcore: registered new interface driver cdc_ether
Jul  4 10:11:05 kernel: usbcore: registered new interface driver rndis_host
Jul  4 10:11:05 kernel: cdc_ncm: 14-Mar-2012
Jul  4 10:11:05 kernel: usbcore: registered new interface driver cdc_ncm
Jul  4 10:11:05 kernel: usbcore: registered new interface driver cdc_wdm
Jul  4 10:11:05 kernel: usbcore: registered new interface driver qmi_wwan
Jul  4 10:11:05 kernel: cdc_mbim: loaded
Jul  4 10:11:05 kernel: usbcore: registered new interface driver cdc_mbim
Jul  4 10:11:06 kernel: usb 1-1.1: new high speed USB device using ehci_hcd and address 3
Jul  4 10:11:06 kernel: usb 1-1.1: configuration #1 chosen from 1 choice
Jul  4 10:11:06 kernel: scsi0 : SCSI emulation for USB Mass Storage devices
Jul  4 10:11:06 kernel: usb 1-1.4: new high speed USB device using ehci_hcd and address 4
Jul  4 10:11:06 kernel: usb 1-1.4: configuration #1 chosen from 1 choice
Jul  4 10:11:06 kernel: scsi1 : SCSI emulation for USB Mass Storage devices
Jul  4 10:11:07 rc_service: ntp 343:notify_rc restart_diskmon
Jul  4 10:11:07 disk_monitor: Finish
Jul  4 10:11:07 disk monitor: be idle
Jul  4 10:11:08 kernel: scsi 0:0:0:0: Direct-Access     WD       Elements 10B8    1012 PQ: 0 ANSI: 6
Jul  4 10:11:08 kernel: sd 0:0:0:0: [sda] 976707584 512-byte hardware sectors (500074 MB)
Jul  4 10:11:08 kernel: sd 0:0:0:0: [sda] Write Protect is off
Jul  4 10:11:08 kernel: sd 0:0:0:0: [sda] Assuming drive cache: write through
Jul  4 10:11:08 kernel: sd 0:0:0:0: [sda] Assuming drive cache: write through
Jul  4 10:11:08 kernel:  sda:<5>scsi 1:0:0:0: Direct-Access     Multi    Flash Reader     1.00 PQ: 0 ANSI: 0
Jul  4 10:11:08 kernel: sd 1:0:0:0: [sdb] Attached SCSI removable disk
Jul  4 10:11:08 kernel: sd 1:0:0:0: Attached scsi generic sg0 type 0
Jul  4 10:11:14 kernel:  sda1 sda2 sda3
Jul  4 10:11:14 kernel: sd 0:0:0:0: [sda] Attached SCSI disk
Jul  4 10:11:14 kernel: sd 0:0:0:0: Attached scsi generic sg1 type 0
Jul  4 10:11:14 custom script: Running /jffs/scripts/pre-mount (args: /dev/sda3)
Jul  4 10:11:26 hour monitor: daemon is starting
Jul  4 10:11:29 dnsmasq-dhcp[245]: DHCPREQUEST(br0) 192.168.200.203 5c:0a:5b:24:89:f3 
Jul  4 10:11:29 dnsmasq-dhcp[245]: DHCPACK(br0) 192.168.200.203 5c:0a:5b:24:89:f3 android-86a37bfc7d1eb476
Jul  4 10:11:45 crond[249]: time disparity of 487211 minutes detected
Jul  4 10:11:57 dnsmasq-dhcp[245]: DHCPREQUEST(br0) 192.168.200.217 00:8c:fa:85:c8:e1 
Jul  4 10:11:57 dnsmasq-dhcp[245]: DHCPACK(br0) 192.168.200.217 00:8c:fa:85:c8:e1 Toshiba
Jul  4 10:12:24 dnsmasq-dhcp[245]: DHCPREQUEST(br0) 192.168.200.199 88:9f:fa:33:cd:3d 
Jul  4 10:12:24 dnsmasq-dhcp[245]: DHCPACK(br0) 192.168.200.199 88:9f:fa:33:cd:3d halszka
Jul  4 10:13:34 dnsmasq-dhcp[245]: DHCPREQUEST(br0) 192.168.200.253 00:1f:c6:62:1a:4d 
Jul  4 10:13:34 dnsmasq-dhcp[245]: DHCPACK(br0) 192.168.200.253 00:1f:c6:62:1a:4d dev20
Jul  4 10:14:27 dnsmasq-dhcp[245]: DHCPINFORM(br0) 192.168.200.199 88:9f:fa:33:cd:3d 
Jul  4 10:14:27 dnsmasq-dhcp[245]: DHCPACK(br0) 192.168.200.199 88:9f:fa:33:cd:3d halszka
Jul  4 10:16:17 dnsmasq-dhcp[245]: DHCPREQUEST(br0) 192.168.200.203 5c:0a:5b:24:89:f3 
Jul  4 10:16:17 dnsmasq-dhcp[245]: DHCPACK(br0) 192.168.200.203 5c:0a:5b:24:89:f3 android-86a37bfc7d1eb476
Jul  4 10:16:26 dnsmasq-dhcp[245]: DHCPREQUEST(br0) 192.168.200.217 00:8c:fa:85:c8:e1 
Jul  4 10:16:26 dnsmasq-dhcp[245]: DHCPACK(br0) 192.168.200.217 00:8c:fa:85:c8:e1 Toshiba
Jul  4 10:17:24 dnsmasq-dhcp[245]: DHCPREQUEST(br0) 192.168.200.199 88:9f:fa:33:cd:3d 
Jul  4 10:17:24 dnsmasq-dhcp[245]: DHCPACK(br0) 192.168.200.199 88:9f:fa:33:cd:3d halszka
Jul  4 10:18:34 dnsmasq-dhcp[245]: DHCPREQUEST(br0) 192.168.200.253 00:1f:c6:62:1a:4d 
Jul  4 10:18:34 dnsmasq-dhcp[245]: DHCPACK(br0) 192.168.200.253 00:1f:c6:62:1a:4d dev20
Jul  4 10:20:55 dnsmasq-dhcp[245]: DHCPREQUEST(br0) 192.168.200.217 00:8c:fa:85:c8:e1 
Jul  4 10:20:55 dnsmasq-dhcp[245]: DHCPACK(br0) 192.168.200.217 00:8c:fa:85:c8:e1 Toshiba
Jul  4 10:21:05 dnsmasq-dhcp[245]: DHCPREQUEST(br0) 192.168.200.203 5c:0a:5b:24:89:f3 
Jul  4 10:21:05 dnsmasq-dhcp[245]: DHCPACK(br0) 192.168.200.203 5c:0a:5b:24:89:f3 android-86a37bfc7d1eb476
Jul  4 10:21:19 kernel: kjournald starting.  Commit interval 5 seconds
Jul  4 10:21:19 kernel: EXT3 FS on sda3, internal journal
Jul  4 10:21:19 kernel: EXT3-fs: mounted filesystem with ordered data mode.
Jul  4 10:21:19 syslog: USB ext3 fs at /dev/sda3 mounted on /tmp/mnt/sda3
Jul  4 10:21:19 usb: USB ext3 fs at /dev/sda3 mounted on /tmp/mnt/sda3.

**Comment by RMerl** [comment]
It should not prevent the rest of the firmware from running, only the disk from mounting until the script has completed.  This is working as intended, I see a 10 minutes gap between the moment the pre-mount script gets launched and the moment the disk gets mounted under /tmp/mnt/sda3.

**Comment by k-emil** [comment]
Right, but please take into account, that overlay is on the disk, so the router boots up with the configuration being far from required.

**Comment by RMerl** [comment]
Router events are run async, so there's no way for the script to prevent the rest of the firmware from running.  Also, pre-mount isn't run by the boot process specifically, but at any point a disk gets plugged in, and udev triggers the event.  It's not a linear process.

**Comment by k-emil** [comment]
Right. Implementing overlay I will have to keep the “default” config making the router deaf and silent, opening required config after mounting the disk in question.
That is apparently the only way to go.
Thanks and apologies for raising spurious “bug”
