### ISSUE TITLE
Firmware is not compatible and uncertified

### ISSUE THREAD

**Issue by didok3003** [RMerl/asuswrt-merlin#967]
Hello, following the readme.txt instructions, I uploaded the file to flash the firmware, howere an error was shown:
![capture](https://cloud.githubusercontent.com/assets/1307828/16695500/ddde40da-4505-11e6-8721-110a77e3c248.PNG)

My router is RT-AC68U and the firmware used is Asuswrt-Merlin - build 380.59 (10-May-2016)

This is the file I used:
[README-merlin.txt](https://github.com/RMerl/asuswrt-merlin/files/354747/README-merlin.txt)

> Simply flash it like any regular update.  You should not need to 
reset to factory defaults (see note below for exceptions).
You can revert back to an original Asus firmware at any time just
by flashing a firmware downloaded from Asus's website.

any idea?

**Comment by RMerl** [comment]
Asus recently changed the validation due to new regulation requirements from bodies such as the FCC.

See this announcement for more information:

http://www.snbforums.com/threads/important-asuswrt-merlin-380-59-and-older-not-compatible-with-asus-3-0-0-4-380_3000-or-newer.32962/

**Comment by didok3003** [comment]
There is a beta but for RT-AC68U, is it working for mine too? May I wait a while?

**Comment by RMerl** [comment]
Yes, the beta would work, or you can flash 380.59 using Asus's Firmware Recovery tool.

**Comment by didok3003** [comment]
I have installed 380.59 using Asus's Firmware Recovery tool. It worked perfectly.

Is there any subscription or notification that will be sent once 380.60 is ready?

Thanks!

**Comment by RMerl** [comment]
No.  I always announce new releases to Twitter, SNBForums and on the website.

**Comment by didok3003** [comment]
Everything fine now, thanks for the support.
