### ISSUE TITLE
Help on advanced VPN configuration (support)

### ISSUE THREAD

**Issue by didok3003** [RMerl/asuswrt-merlin#973]
Hello, I'm not an advanced user and I know this is not for this matter, but I wonder if there is any option anybody in the community can help me understand and configure my VPN to work similar to what is explained [here](https://github.com/RMerl/asuswrt-merlin/wiki/How-to-setup-SSID-for-VPN-and-SSID-for-Regular-ISP-using-OpenVPN.) by @jobongo .

I hope you understan I'm very novice in this matter and I can't follow majority of terms you are using to explain the code. I have some kind of knowledge about programming, but nothing related to networks.

My need is to have cable connection  and one guest WiFi SSID clear connected to regular internet, and my 2 main SSID (5 and 2.4 GHz) protected over a VPN (I have PureVPN service). The reason I want this is because I want my devices protected (privacy) over the VPN but my SmarTV on a unprotected network, as Netflix has banned VPN connecions. Also my personal RIG would have VPN over software as I need to easily disable it when gaming online (it reduce very bad my speed and increase the latency).

Thanks for the help if you can, if not I do understand, but would appreciate some kind of "guidance" on where to read about this and learn by myself. Thanks!

**Comment by RMerl** [comment]
Please us the support forums at SNBForums for support requests.
