### ISSUE TITLE
 Error occurred when using the golang net library

### ISSUE THREAD

**Issue by xinghusp** [RMerl/asuswrt-merlin#974]
I tried to run a network program on the router,but it return error.
the same program is running successfully on the arm router (ac56u) which also run the merlin .

on the n66u with merlin,it can't create the listen port.But on the same router with openwrt,it running success.

i use the golang to build the program.
![qq 20160713131430](https://cloud.githubusercontent.com/assets/18201606/16792525/c588bb24-48fb-11e6-847a-b42235879cb2.jpg)

**Comment by xinghusp** [comment]
the merlin version is 380.59_release

**Comment by RMerl** [comment]
This isn't a problem with the firmware itself.  I recommend asking on the support forums at SNBForums, someone might be able to help you with it.  Most likely, you will need to tweak your cross compile makefile to work with the older kernel / uClibc used by the MIPS platform.
