### ISSUE TITLE
Warning: dnsmasq resolution of local ips is disabled when dns based filtering is enabled

### ISSUE THREAD

**Issue by pmagid** [RMerl/asuswrt-merlin#976]
Once you enable DNS-based filtering resolution of local ips by dnsmasq is disabled because everything is funneled through the DNS filtering service.   A warning of this behavior on the dns filtering page is desirable.

Place the following in a different color at the bottom of the text on the dns-based filtering page:

Warning: dnsmasq resolution of local ips is disabled when dns based filtering is enabled (if you do not wish to loose local ip resolution and you are ok with some DNS requests not going through the filter then override the DNS servers on the WAN page instead.)

**Comment by RMerl** [comment]
It's already mentioned in the documentation.  

https://github.com/RMerl/asuswrt-merlin/wiki/DNS-Filter

I don't want to overload the webui with notices, as people don't read them anyway if there's too much text for them to read. I still get frequent "My traffic monitoring isn't working properly" despite the webui having a notice about Hardware Acceleration not being compatible with it.
