### ISSUE TITLE
AIProtection disabled!!!

### ISSUE THREAD

**Issue by Sebi34** [RMerl/asuswrt-merlin#978]
Hello,
I'm facing the issue that I have disabled all AI Protection settings but in case of some websites or Onlineshop Weblinks, I get some screens like this..

RT-AC68U
Detailed informations:
Description:
Sites dedicated to displaying advertisements, including sites used to display banner or popup advertisement.
Host: xxxxx
URL: partners.webmasterplan.com
Wir empfehlen
For more completed security protection for your endpoint sides, Trend Micro offers you a more advanced home security solution. Please click the download link for the free trial or visit the site online scan service.

RT AC68U latest firmware.

Thanks

**Comment by RMerl** [comment]
Please use the support forums at SNBForums for support requests.
