### ISSUE TITLE
Asus loose internett

### ISSUE THREAD

**Issue by spot88** [RMerl/asuswrt-merlin#985]
Running the newest version on RT-AC3200 , i loose internett maybe 2 times a day. Just reboot Asus won't work, i need to reboot my Fiber Optic modem and then Asus, after that everything works until next time.

**Comment by spot88** [comment]
Anyone else been having the same problem, or might have a idea of what the problem is?

**Comment by RMerl** [comment]
Please head to the support forums for troubleshooting.  Most of the time these are ISP-related, not firmware-related, especially if they occur multiple times per day.

**Comment by spot88** [comment]
@RMerl Thanks for your answer, i work at my ISP, and the problem is not there. When i loose internett i get internett from the originally provided box. 
- I'm now using original Asus firmware and so far it's working. 

I was on the latest Merlin Firmware before.
