### ISSUE TITLE
Add MAC WAN to Network Map

### ISSUE THREAD

**Issue by pepeEL** [RMerl/asuswrt-merlin#988]
Hi
Is possible to add to Network Map info about address MAC WAN ? Maybe about IP and DNS and MASK. Sometimes is need...

**Comment by RMerl** [comment]
MAC address is mostly useless since this is a static parameter that will never change, and the other information are already there.

**Comment by pepeEL** [comment]
But sometime need it to send for my isp. But when i have router in place very high it is difficult.

**Comment by pepeEL** [comment]
I think about this:
![wan mac](https://cloud.githubusercontent.com/assets/16692223/17327176/955af758-58b6-11e6-82b9-96e32f2d5a7c.jpg)

For lan and wifi is add info about mac that i think that should also be add for WAN MAC
