### ISSUE TITLE
5ghz Radio on AC66U not working with 380.61

### ISSUE THREAD

**Issue by BradleyCampbell** [RMerl/asuswrt-merlin#993]
Since upgrading to the latest firmware yesterday, the 5ghz radio will not turn on.  The professional tab under wireless says that the 5ghz radio is enabled but the guest network page says that to turn on wifi to operate a guest network on the 5ghz section.

**Comment by BradleyCampbell** [comment]
I was able to restore functionality by doing a full system reset.  A word of caution when upgrading

**Comment by machnee** [comment]
I upgraded two RT-N66U units from official 3.0.0.4.380.3831 to merlin 380.61 with 5GHz still enabled.
I'll try the upgrade on a AC66U next.
