### ISSUE TITLE
No enable/disable JFFS on AC66U

### ISSUE THREAD

**Issue by dmolavi** [RMerl/asuswrt-merlin#994]
Updated to the newest release and I don't have an option to disable JFFS, even though the firmware update screen says it's enabled. It's not on the Admin -> System tab where the other JFFS options are. I checked both before and after the update and it wasn't on the prior release or this newest one.

**Comment by RMerl** [comment]
That's normal.  The option to disable JFFS was removed last year because various components of the firmware require it now.
