### ISSUE TITLE
Add a Dockerfile that provides an easy to use build environment

### ISSUE THREAD

**Issue by ograff** [RMerl/asuswrt-merlin#995]
Reduce the barrier to entry of entry for contribution / development by providing a Dockerfile that will build a docker image containing all necessary dependencies to build asuswrt-merlin. 

The docker image's entry point should be tools/build_all.

Update the development documentation to give an example using docker to build a firmware image.

**Comment by ograff** [comment]
@RMerl I'd be happy to work on this and submit a PR if its something you think you would like having in the repo.

**Comment by RMerl** [comment]
Asuswrt's build environment is quite complex and fragile.  I don't want to touch that build system, don't feel like spending time implementing any alternative build system either, and having to deal with fixing it every time a change upstream breaks it.
