### ISSUE TITLE
WiFi Calling QoS

### ISSUE THREAD

**Issue by brodyhoskins** [RMerl/asuswrt-merlin#996]
This is not a bug, but a simple request. I apologize if this isn't the appropriate place to do this.

I'm using wifi calling with my carrier (T-Mobile) and though I have a 120 Mbps WAN link, the adaptive QoS isn't prioritizing its traffic (it isn't typical VoIP). From what I've read online this can be changed manually with port numbers, but I'd really like to use adaptive QoS.

Is this trivial to implement? Thanks!

**Comment by RMerl** [comment]
Adaptive QoS is closed source, and cannot be modified.
